### ISSUE TITLE
Module use of python37.dll conflicts with this version of Python

### ISSUE THREAD

**Issue by luiandresgonzalez** [olivierfriard/BORIS#364]
Hi, I recently updated BORIS to latest version and it fails to run.
Here is the error log:
```
Traceback (most recent call last):
  File "C:\Users\luisa\BORIS\lib\runpy.py", line 184, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "C:\Users\luisa\BORIS\lib\runpy.py", line 143, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "C:\Users\luisa\BORIS\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "C:\Users\luisa\BORIS\lib\site-packages\boris\__init__.py", line 25, in <module>
    from .core import main
  File "C:\Users\luisa\BORIS\lib\site-packages\boris\core.py", line 32, in <module>
    import socket
  File "C:\Users\luisa\BORIS\lib\socket.py", line 49, in <module>
    import _socket
ImportError: Module use of python37.dll conflicts with this version of Python.
```
Running `python --version` returns `Python 3.8.2`

%PYTHONPATH% is not defined. 

Will update if I get it to work, but I believe there should be a way for a normal user to get away from this issue after updating. 

Thanks!

**Comment by luiandresgonzalez** [comment]
An update: 
This was somewhat caused probably because I did not delete the previous BORIS version before installing the latest one. 

Deleting the old folder and installing it again solved the issue. 

Thanks
