### ISSUE TITLE
Error code with BORIS for Windows 64-bit Portable v.7.10.2

### ISSUE THREAD

**Issue by BellDJ4** [olivierfriard/BORIS#370]
Hi
I have downloaded the portable version of BORIS onto a USB flashdrive and extracted all from the zip file.  When I open the batch file start_boris the command prompt appears briefly and disappears.  When I look at the error log file, the following error  is mentioned:
File "D:\boris-7.10.2-win64\lib\site-packages\matplotlib\__init__.py", line 159, in _check_versions
    from . import ft2font
ImportError: DLL load failed while importing ft2font: The specified module could not be found.

Any thoughts as to what could be causing this?

Thanks.

**Comment by olivierfriard** [comment]
Hi,
can you send me more info?
see http://www.boris.unito.it/pages/report_a_bug.html
o

**Comment by BellDJ4** [comment]
Operating system: Microsoft Windows, version 20H2

I downloaded the portable version of BORIS (7.10.2-win-64) from the website and transferred this to a USB flashdrive.  I then extracted the files from the Zip file  and from the "unzipped" folder, I ran start_boris batch file.  The cmd.exe message screen appeared saying that first launch of BORIS may take some time.  This message stays on screen for about 1 minute and then disappears.  The following error log file is created.

Error log File:
Traceback (most recent call last):
  File "D:\boris-7.10.2-win64\lib\runpy.py", line 184, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "D:\boris-7.10.2-win64\lib\runpy.py", line 143, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "D:\boris-7.10.2-win64\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "D:\boris-7.10.2-win64\lib\site-packages\boris\__init__.py", line 25, in <module>
    from .core import main
  File "D:\boris-7.10.2-win64\lib\site-packages\boris\core.py", line 44, in <module>
    import matplotlib
  File "D:\boris-7.10.2-win64\lib\site-packages\matplotlib\__init__.py", line 174, in <module>
    _check_versions()
  File "D:\boris-7.10.2-win64\lib\site-packages\matplotlib\__init__.py", line 159, in _check_versions
    from . import ft2font
ImportError: DLL load failed while importing ft2font: The specified module could not be found.

**Comment by BellDJ4** [comment]
Sorry this comment is not closed. (closed by accident 02/03/21).
Operating system - Microsoft Windows, version 20H2

I downloaded the portable version of BORIS (7.10.2 Windows 64 bit) to a USB flashdrive and extracted the files from the zip folder.  I then opened the "unzipped" folder and opened the start_boris batch file.  The cmd exe message appears saying that the first launch of BORIS may take some time.  This screen stays for about 1 minute and then goes.
The following appears in the error log file:
Traceback (most recent call last):
  File "D:\boris-7.10.2-win64\lib\runpy.py", line 184, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "D:\boris-7.10.2-win64\lib\runpy.py", line 143, in _get_module_details
    return _get_module_details(pkg_main_name, error)
  File "D:\boris-7.10.2-win64\lib\runpy.py", line 110, in _get_module_details
    __import__(pkg_name)
  File "D:\boris-7.10.2-win64\lib\site-packages\boris\__init__.py", line 25, in <module>
    from .core import main
  File "D:\boris-7.10.2-win64\lib\site-packages\boris\core.py", line 44, in <module>
    import matplotlib
  File "D:\boris-7.10.2-win64\lib\site-packages\matplotlib\__init__.py", line 174, in <module>
    _check_versions()
  File "D:\boris-7.10.2-win64\lib\site-packages\matplotlib\__init__.py", line 159, in _check_versions
    from . import ft2font
ImportError: DLL load failed while importing ft2font: The specified module could not be found.
