### ISSUE TITLE
[BORIS v8.6.2] Current Time Budget Error

### ISSUE THREAD

**Issue by rvtmsw** [olivierfriard/BORIS#509]
**Describe the bug**
BORIS version: 8.6.2
OS: Windows 10 10.0.22000
CPU: AMD64 Intel64 Family 6 Model 158 Stepping 13, GenuineIntel
Python 3.8.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.6
2022-06-26 12:14

Traceback (most recent call last):
  File "G:\Programs\BORIS\boris-8.6.2-win64\lib\site-packages\boris\connections.py", line 236, in <lambda>
    lambda: time_budget_widget.time_budget(self, mode="by_behavior", mode2="current")
  File "G:\Programs\BORIS\boris-8.6.2-win64\lib\site-packages\boris\time_budget_widget.py", line 484, in time_budget
    out, categories = time_budget_functions.time_budget_analysis(
  File "G:\Programs\BORIS\boris-8.6.2-win64\lib\site-packages\boris\time_budget_functions.py", line 953, in time_budget_analysis
    if row[cfg.SUBJECT] == subject and row[cfg.BEHAVIOR_CODE] == behavior:
KeyError: 'code'

**To Reproduce**
1. Go to 'Current Time Budget'
2. Select all the necessities
3. Click on 'OK'

**Expected behavior**
See Current Time Budget.

**Screenshots**

**Desktop (please complete the following information):**
BORIS version: 8.6.2
OS: Windows 10 10.0.22000
CPU: AMD64 Intel64 Family 6 Model 158 Stepping 13, GenuineIntel
Python 3.8.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.6
2022-06-26 12:14

**In case of crash** copy the content of the boris_error.log file (before relaunching BORIS).

**Comment by rvtmsw** [comment]
The current time budget button, Analysis > Time budget, and Analysis > Time budget by behavioral category are working fine in Mac, even with BORIS 7.13.4 and opening the same (.Boris) file.

**Comment by rvtmsw** [comment]
The bug is fixed in v.8.6.3 Windows 64bit: https://github.com/olivierfriard/BORIS/releases/tag/v8.6.3 - following the solved bug #517.
Thank you, @olivierfriard, BEST!
