### ISSUE TITLE
Analysis Error

### ISSUE THREAD

**Issue by Yaoyiyan** [olivierfriard/BORIS#517]
I saw the below error when I try to use the "time budget" function under the "analysis"

BORIS version: 8.6.2 
OS: Windows 10 10.0.22000
CPU: AMD64 Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
Python 3.8.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.6
2022-07-28 09:17

Traceback (most recent call last):
  File "C:\Users\yiyan\Downloads\boris-8.6.2-win64\lib\site-packages\boris\connections.py", line 188, in <lambda>
    self.actionTime_budget.triggered.connect(lambda: time_budget_widget.time_budget(self, mode="by_behavior"))
  File "C:\Users\yiyan\Downloads\boris-8.6.2-win64\lib\site-packages\boris\time_budget_widget.py", line 484, in time_budget
    out, categories = time_budget_functions.time_budget_analysis(
  File "C:\Users\yiyan\Downloads\boris-8.6.2-win64\lib\site-packages\boris\time_budget_functions.py", line 953, in time_budget_analysis
    if row[cfg.SUBJECT] == subject and row[cfg.BEHAVIOR_CODE] == behavior:
KeyError: 'code'

Is there anyway to solve it?
Thanks!

**Comment by olivierfriard** [comment]
This issue should be fixed in v. 8.6.3 just released:
https://github.com/olivierfriard/BORIS/releases/tag/v8.6.3

Can you confirm and eventually close the issue?
