### ISSUE TITLE
BORIS will not start

### ISSUE THREAD

**Issue by zekeb** [olivierfriard/BORIS#54]
After upgrading to python 3.6.0 BORIS no longer initiates.  Error message is:
` python boris.py
Traceback (most recent call last):                                                                                                                
  File "boris.py", line 119, in <module>                                                                                                          
    import tablib                                                                                                                                 
  File "/home/brett/BORIS/tablib/__init__.py", line 3, in <module>                                                                                
    from tablib.core import (                                                                                                                     
  File "/home/brett/BORIS/tablib/core.py", line 15, in <module>                                                                                   
    from tablib import formats                                                                                                                    
  File "/home/brett/BORIS/tablib/formats/__init__.py", line 6, in <module>                                                                        
    from . import _csv as csv                                                                                                                     
  File "/home/brett/BORIS/tablib/formats/_csv.py", line 6, in <module>                                                                            
    from tablib.compat import is_py3, csv, StringIO                                                                                               
  File "/home/brett/BORIS/tablib/compat.py", line 25, in <module>                                                                                 
    import tablib.packages.xlwt3 as xlwt                                                                                                          
  File "/home/brett/BORIS/tablib/packages/xlwt3/__init__.py", line 5, in <module>
    from .Row import Row
  File "/home/brett/BORIS/tablib/packages/xlwt3/Row.py", line 6, in <module>
    from . import ExcelFormula
  File "/home/brett/BORIS/tablib/packages/xlwt3/ExcelFormula.py", line 1, in <module>
    from . import ExcelFormulaParser, ExcelFormulaLexer
  File "/home/brett/BORIS/tablib/packages/xlwt3/ExcelFormulaLexer.py", line 52, in <module>
    VERBOSE+LOCALE+IGNORECASE)
  File "/usr/lib/python3.6/re.py", line 233, in compile
    return _compile(pattern, flags)
  File "/usr/lib/python3.6/re.py", line 301, in _compile
    p = sre_compile.compile(pattern, flags)
  File "/usr/lib/python3.6/sre_compile.py", line 562, in compile
    p = sre_parse.parse(p, flags)
  File "/usr/lib/python3.6/sre_parse.py", line 866, in parse
    p.pattern.flags = fix_flags(str, p.pattern.flags)
  File "/usr/lib/python3.6/sre_parse.py", line 833, in fix_flags
    raise ValueError("cannot use LOCALE flag with a str pattern")
ValueError: cannot use LOCALE flag with a str pattern
`

This is a fresh clone from the git repo with an updated version of xlwt on Arch Linux

Worked under 3.5.2, but regressing breaks dependencies for the current version of Libreoffice which is mission critical for me.

Sorry, can't seem to get the code formatted properly.

**Comment by olivierfriard** [comment]
Hello,

It was a problem with the tablib module that did not work under python3.6.
The problem with tablib should be fixed in the current v. 0.11.4 but BORIS still embed the old v. 0.10.0

Try to remove the tablib directory from the BORIS source directory and install the current tablib module with pip3.6

I will fix this bug in the next release.

Thank you for reporting this problem

**Comment by zekeb** [comment]
Thanks, deleting it seemed to work (I had already installed the updated
version, but had the old module in the BORIS folder.

Really nice software!  Thanks!

**Comment by olivierfriard** [comment]
The problem should be fixed in the v. 3.41 (just released).
BORIS can be launched with Python 3.6.

I am waiting for your report for closing this issue

**Comment by zekeb** [comment]
Sorry, just got this.  Yes, this bug is closed.  BORIS is working for me
again.  Thanks!
