### ISSUE TITLE
New version not working?

### ISSUE THREAD

**Issue by ftyrr** [olivierfriard/BORIS#542]
Error message:

BORIS version: 8.8
OS: Windows 10 10.0.19041
CPU: AMD64 Intel64 Family 6 Model 165 Stepping 3, GenuineIntel
Python 3.8.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.7
2022-10-12 12:42

Traceback (most recent call last):
  File "C:\Program Files\BORIS\lib\site-packages\boris\core.py", line 3624, in mpv_timer_out
    self.sync_time(n_player, ct0)  # self.seek_mediaplayer(ct0, n_player)
  File "C:\Program Files\BORIS\lib\site-packages\boris\core.py", line 3533, in sync_time
    new_time - sum(self.dw_player[n_player].media_durations[0:media_idx], player=n_player)
TypeError: 'player' is an invalid keyword argument for sum()

**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [windows 10, Ubuntu 22.04 ... ]
 - BORIS Version

**In case of crash** copy the content of the boris_error.log file (before relaunching BORIS).

**Comment by ftyrr** [comment]
Sorry this is on the v8 version and on windows, how can I resolve this to be able to playback multiple sources simultaneously?

**Comment by olivierfriard** [comment]
Hi,
as it is specified I need the **Steps to reproduce** the issue

**Comment by ftyrr** [comment]
Start an observation with multiple video players (playing simultaneously). These are media files with absolute path from an external hard drive. After a few seconds of playback, or trying to jump to a selected time, then said error comes up. It says specifically 'player' is an invalid keyword argument for sum().

**Comment by olivierfriard** [comment]
Hi,
can you reproduce the issue with the last version?
