### ISSUE TITLE
use of InvalidStateError makes boris dependent on Python 3.8

### ISSUE THREAD

**Issue by carandraug** [olivierfriard/BORIS#563]
**Describe the bug**

BORIS is marked as requiring Python 3.6 or later (in `setup.py`). However, it imports and uses `InvalidStateError` from the `concurrent.futures` module which was only added in Python 3.8. It causes this error:

```
Traceback (most recent call last):
  File "bin/boris", line 5, in <module>
    from boris import main
  File "lib/python3.7/site-packages/boris/__init__.py", line 24, in <module>
    from .core import main
  File "lib/python3.7/site-packages/boris/core.py", line 86, in <module>
    from . import advanced_event_filtering
  File "lib/python3.7/site-packages/boris/advanced_event_filtering.py", line 49, in <module>
    from . import db_functions, dialog, observation_operations
  File "lib/python3.7/site-packages/boris/db_functions.py", line 28, in <module>
    from . import project_functions
  File "lib/python3.7/site-packages/boris/project_functions.py", line 42, in <module>
    from . import observation_operations
  File "lib/python3.7/site-packages/boris/observation_operations.py", line 58, in <module>
    from . import player_dock_widget
  File "lib/python3.7/site-packages/boris/player_dock_widget.py", line 33, in <module>
    from . import mpv2 as mpv
  File "lib/python3.7/site-packages/boris/mpv2.py", line 26, in <module>
    from concurrent.futures import Future, InvalidStateError
ImportError: cannot import name 'InvalidStateError' from 'concurrent.futures' (lib/python3.7/concurrent/futures/__init__.py)
```

The easy fix is to just bump the requirements in `setup.py` to mention python 3.8. Alternatively, it can catch a different exception depending on the python version. I can do the later if you tell me how to trigger a `InvalidStateError` (I'm not super familiar with that module).

**Comment by carandraug** [comment]
I've looked at the sources for Python 3.7 and 3.11. The Python places where `concurrent.futures.InvalidStateError` is throw have simply no check done in Python 3.7. So I guess there isn't a simple alternative exception that can be used instead.

(as an aside, there is also a `asyncio.InvalidStateError` which despite having the same name is a different class)

**Comment by olivierfriard** [comment]
pull request accepted
Thanks for mentioning this issue
