### ISSUE TITLE
Extracted event frames problem

### ISSUE THREAD

**Issue by Clarasauphar** [olivierfriard/BORIS#572]
Hi :)

The function extract frames from medial files does not function completely. I am only missing very few frames and I wonder if it is because I am registering events at exact time 00:00:000 in some videos. Indeed the number of frames missing seems to be the same as the number of errors in my exported excel file with wrong video file associated to the event (cf issue #567).

**To Reproduce**
I have 16 videos in one observation file (4 observations files total), 960 events (60 per video, one event measured every minute starting from time 00:00:000 of every video). Sometimes the software does not want me to start exactly at 00:00:000 but a few milli seconds after, which is why I probably don't have the problem happening for every video. In one observation file I miss 1 frame, in one other 7, in the other two 8 frames.

 - OS: Windows 10
 - BORIS Version: v.8.9.18-2023-02-07

Thank you again :D

**Comment by Clarasauphar** [comment]
Hi,

I tried but it seems that a problem occurred while opening my file with one of the observation, I don't know why it does not work now... 3 out of 4 observations were working properly when i opened them.

Code error below

BORIS version: 8.16.6
OS: Windows 10 10.0.19045
CPU: AMD64 Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.9
2023-04-19 13:06

Traceback (most recent call last):
  File "C:\Program Files (x86)\BORIS\Lib\site-packages\boris\connections.py", line 92, in <lambda>
    lambda: observation_operations.open_observation(self, mode=cfg.OBS_START)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\BORIS\Lib\site-packages\boris\observation_operations.py", line 183, in open_observation
    return load_observation(self, selected_observations[0], mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\BORIS\Lib\site-packages\boris\observation_operations.py", line 233, in load_observation
    if not initialize_new_media_observation(self):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\BORIS\Lib\site-packages\boris\observation_operations.py", line 1429, in initialize_new_media_observation
    self.dw_player[i].player.wait_until_paused()
  File "C:\Program Files (x86)\BORIS\Lib\site-packages\boris\mpv2.py", line 983, in wait_until_paused
    self.wait_for_property('core-idle', timeout=timeout, catch_errors=catch_errors)
  File "C:\Program Files (x86)\BORIS\Lib\site-packages\boris\mpv2.py", line 1001, in wait_for_property
    with self.prepare_and_wait_for_property(name, cond, level_sensitive, timeout=timeout, catch_errors=catch_errors) as result:
  File "C:\Program Files (x86)\BORIS\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\Program Files (x86)\BORIS\Lib\site-packages\boris\mpv2.py", line 1049, in prepare_and_wait_for_property
    result.set_running_or_notify_cancel()
  File "C:\Program Files (x86)\BORIS\Lib\concurrent\futures\_base.py", line 535, in set_running_or_notify_cancel
    raise RuntimeError('Future in unexpected state')
RuntimeError: Future in unexpected state

System info:

Host Name:                 NTNU23833
OS Name:                   Microsoft Windows 10 Education
OS Version:                10.0.19045 N/A Build 19045
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          NTNU
Registered Organization:   NTNU
Product ID:                00328-10000-00001-AA459
Original Install Date:     19.04.2023, 09:32:06
System Boot Time:          19.04.2023, 10:51:11
System Manufacturer:       Dell Inc.
System Model:              Latitude 7420
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 140 Stepping 1 GenuineIntel ~1498 Mhz
BIOS Version:              Dell Inc. 1.22.0, 15.11.2022
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              no;Norwegian (Bokmal)
Time Zone:                 (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
Total Physical Memory:     16ÿ106 MB
Available Physical Memory: 8ÿ847 MB
Virtual Memory: Max Size:  19ÿ050 MB
Virtual Memory: Available: 10ÿ484 MB
Virtual Memory: In Use:    8ÿ566 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    win.ntnu.no
Logon Server:              \\WIN-DC1
Hotfix(s):                 11 Hotfix(s) Installed.
                           [01]: KB5020872
                           [02]: KB5012170
                           [03]: KB5015684
                           [04]: KB5021043
                           [05]: KB5026037
                           [06]: KB5023696
                           [07]: KB5014032
                           [08]: KB5016705
                           [09]: KB5018506
                           [10]: KB5020372
                           [11]: KB5022924
Network Card(s):           4 NIC(s) Installed.
                           [01]: Intel(R) Wi-Fi 6 AX201 160MHz
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.0.2.1
                                 IP address(es)
                                 [01]: 10.24.92.152
                                 [02]: fe80::b692:30f:e53c:5360
                                 [03]: 2001:700:300:4117:19b9:3706:59ca:56a6
                                 [04]: 2001:700:300:4117:a779:8a98:cad9:6a38
                           [02]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
                           [03]: Realtek USB GbE Family Controller
                                 Connection Name: Ethernet 2
                                 DHCP Enabled:    Yes
                                 DHCP Server:     129.241.0.206
                                 IP address(es)
                                 [01]: 10.50.99.65
                                 [02]: fe80::1df0:f458:c215:52f3
                                 [03]: 2001:700:301:c:8dc6:8917:38c4:3c69
                                 [04]: 2001:700:301:c:c2de:e297:8274:4d68
                           [04]: Realtek USB GbE Family Controller
                                 Connection Name: Ethernet 3
                                 Status:          Media disconnected
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

**Comment by olivierfriard** [comment]
Hi,

I worked to fix this issue. Please try the version 8.16.7 and let me know.
You can download it at https://github.com/olivierfriard/BORIS/releases/tag/v8.16.7
Thank you for your collaboration

**Comment by Clarasauphar** [comment]
Hi, 
Sorry I did not have time to check before today. I am sorry it still does not work. Still missing between 1 to 10 frames per observations (with 960 expected events to be extracted as frames).
