### ISSUE TITLE
BORIS Error Occurred after update when using coding pad

### ISSUE THREAD

**Issue by mx-blood** [olivierfriard/BORIS#582]
The following error occurs when starting a project and pressing any key on the coding pad:

BORIS version: 8.11.1
OS: Windows 10 10.0.19044
CPU: AMD64 Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.9
2023-02-27 12:17

Traceback (most recent call last):
  File "C:\Users\bloodworth.7\BORIS\Lib\site-packages\boris\core.py", line 562, in click_signal_from_coding_pad
    self.keyPressEvent(q)
  File "C:\Users\bloodworth.7\BORIS\Lib\site-packages\boris\core.py", line 4708, in keyPressEvent
    self.write_event(event, memLaps)
  File "C:\Users\bloodworth.7\BORIS\Lib\site-packages\boris\core.py", line 4222, in write_event
    [mem_time, subject, event[cfg.BEHAVIOR_CODE], modifier_str, comment, frame_idx],
                                                                         ^^^^^^^^^
UnboundLocalError: cannot access local variable 'frame_idx' where it is not associated with a value

![boris error](https://user-images.githubusercontent.com/126504594/221634397-34e42b21-cb4e-4cf3-ad08-9d55a0382d4c.PNG)

**Comment by olivierfriard** [comment]
Hi,
this issue should be fixed in v. 8.11.2 (see https://github.com/olivierfriard/BORIS/releases/tag/v8.11.2).

Please test and let me know.
