### ISSUE TITLE
cannot close and reopen after openning the latest version the first time

### ISSUE THREAD

**Issue by chris201286** [olivierfriard/BORIS#583]
After closing for the first time
BORIS version: 8.11
OS: Windows 10 10.0.19044
CPU: AMD64 Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
Python 3.11.1 (64-bit)
Qt 5.15.2 - PyQt 5.15.9
2023-02-27 12:21

Traceback (most recent call last):
  File "C:\Users\chenlab\BORIS\Lib\site-packages\boris\core.py", line 4988, in closeEvent
    config_file.save(self)
  File "C:\Users\chenlab\BORIS\Lib\site-packages\boris\config_file.py", line 362, in save
    settings.setValue("frame_bitmap_format", self.frame_bitmap_format)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MainWindow' object has no attribute 'frame_bitmap_format'

Try to reopen:
BORIS version: 8.11
OS: Windows 10 10.0.19044
CPU: AMD64 Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
Python 3.11.1 (64-bit)
Qt 5.15.2 - PyQt 5.15.9
2023-02-27 12:25

Traceback (most recent call last):
  File "C:\Users\chenlab\BORIS\Lib\site-packages\boris\config_file.py", line 224, in read
    self.frame_bitmap_format = cfg.FRAME_DEFAULT_BITMAP_FORMAT
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'boris.config' has no attribute 'FRAME_DEFAULT_BITMAP_FORMAT'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\Users\chenlab\BORIS\Lib\site-packages\boris\__main__.py", line 25, in <module>
    main()
  File "C:\Users\chenlab\BORIS\Lib\site-packages\boris\core.py", line 5208, in main
    window = MainWindow(ffmpeg_bin)
             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\chenlab\BORIS\Lib\site-packages\boris\core.py", line 366, in __init__
    config_file.read(self)
  File "C:\Users\chenlab\BORIS\Lib\site-packages\boris\config_file.py", line 226, in read
    self.frame_bitmap_format = cfg.FRAME_DEFAULT_BITMAP_FORMAT
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'boris.config' has no attribute 'FRAME_DEFAULT_BITMAP_FORMAT'

**Comment by olivierfriard** [comment]
Hi,
this issue should be fixed in v. 8.11.2 (see https://github.com/olivierfriard/BORIS/releases/tag/v8.11.2).

Please test and let me know.
