### ISSUE TITLE
Divide by zero when observing mixed image / video files

### ISSUE THREAD

**Issue by vandenbergrf** [olivierfriard/BORIS#585]
BORIS version: 8.11.2

**Description**
When observing a mix of .jpg still images and .AVI videos, BORIS reports a divide by zero error when calculating using the total duration of an image (presumably 0). I did not encounter this bug while using the last big-number version of BORIS (7.X.X, unfortunately I don't remember the exact version). 

**To Reproduce**
1. Create a new observation that includes both still images in .jpg format and videos in .avi format (though presumably this will work for any combination of still images and video)
2. Start the observation
3. Wait for the first transition from image to video or vice-versa.

**Expected behavior**
Still images pass through the observation, allowing enough time to look at them. (For version 7.X.X, images would be parsed as 10-second "videos" of a single frame. This had its own issues in terms of the temporal accuracy of observations made during this 10-second window, but threw up no error and allowed for presence/absence scoring)

**Screenshots**
NA

**Desktop (please complete the following information):**
 - OS:  Windows 10 10.0.22621
 - Type of BORIS installation: Setup
CPU: AMD64 Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.9
2023-03-01 10:29
CPU: AMD64 Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.9
2023-03-01 10:29

**In case of crash** 
No crash results from this bug

**Traceback (most recent call last):**
  File "C:\Users\Reinier\BORIS\Lib\site-packages\boris\core.py", line 3786, in mpv_timer_out
    round(current_media_time_pos / current_media_duration * (cfg.SLIDER_MAXIMUM - 1))
          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: float division by zero

**Comment by vandenbergrf** [comment]
Addendum two:

I figured I may as well look at line 3786 in core.py.

Replaced the code after # set video  scroll bar at line 3783 with the following:

`            # set video scroll bar
            if scroll_slider and not self.user_move_slider:
                if current_media_duration > 0:
                    self.video_slider.setValue(
                        round(current_media_time_pos / current_media_duration * (cfg.SLIDER_MAXIMUM - 1))
                    )
                else: 
                    self.video_slider.setValue(0)`

This fixed the issue, at least on the user side. It's a quick and dirty fix, so I have no idea about the impact on performance or program integrity.

**Comment by olivierfriard** [comment]
Hi,

thank you for reporting this.

Observation from a mix of images and videos is not a feature of BORIS. I never did that ;-)
The possibility you had to do it was a side effect of the VLC player used in version <=7
In v. 8 the MPV libraries replaced the VLC libraries and so the behavior of BORIS is different when handling images.

Note that observation from directories of pictures (jpg, tiff, png ...) was added in v. 8.
See https://boris.readthedocs.io/en/latest/#observation-from-pictures

Thank you for the **Addendum two**

**Comment by vandenbergrf** [comment]
Thank you for the quick response!

As the images and videos alternate over the same timeline of events (Image -> Video -> Image etc.), for now I will try to continue with this imperfect system which coincidentally works as I'd like it to. It's already much, much more efficient than without BORIS!

(My bungled code insertion still results in some errors, particularly when manually dragging the seeker button)

I'll also take this opportunity to thank you for implementing the specification of the frame in which the behaviour occurs, that's very helpful to me.

**Comment by olivierfriard** [comment]
Hi,
I tried to reproduce the issue by mixing images (jpeg) and video but the value of the current_media_duration variable is 1 (second) for the images (so no division by zero). I tried with PNG images but BORIS does not allow me to add them during the observation creation because it cannot access the duration of media. 
Could you give me more details about your mixed observations and maybe an image sample?

Thank you for your collaboration

**Comment by vandenbergrf** [comment]
Hi,

the pictures and images were taken with a trap camera, 'Victure' brand - model 'HC300'. The trap camera was set to capture both images and video when triggered by a motion sensitive sensor (taking the image first, then switching to video). 
Images are encoded as .JPG, while videos are encoded as .AVI.

Each image "duration" is reported as 0.04 seconds. 
As the videos don't compress well, I'm attaching a few sample images which also seem to work on their own (second image).
I'm using "add media -> with absolute path" to load them in. 

Please let me know if you want any more information and I'll be happy to send more, and good luck!

All the best,
R

![New Observation](https://user-images.githubusercontent.com/79840761/222176267-102da777-5fb6-4a02-b273-de0ff216208b.png)


![New_Observation_02](https://user-images.githubusercontent.com/79840761/222177429-4afa45bc-6f7a-4527-a7f1-84a76c416b3d.png)

[DSCF0067.zip](https://github.com/olivierfriard/BORIS/files/10862254/DSCF0067.zip)


Tracebacks below:

**Loading the observation just after creation:**
BORIS version: 8.11.2
OS: Windows 10 10.0.22621
CPU: AMD64 Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.9
2023-03-01 15:50

Traceback (most recent call last):
  File "C:\Users\Reinier\BORIS\Lib\site-packages\boris\connections.py", line 91, in <lambda>
    lambda: observation_operations.new_observation(self, mode=cfg.NEW, obsId="")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Reinier\BORIS\Lib\site-packages\boris\observation_operations.py", line 1079, in new_observation
    initialize_new_media_observation(self)
  File "C:\Users\Reinier\BORIS\Lib\site-packages\boris\observation_operations.py", line 1661, in initialize_new_media_observation
    self.mpv_timer_out(value=0.0)
  File "C:\Users\Reinier\BORIS\Lib\site-packages\boris\core.py", line 3786, in mpv_timer_out
    round(current_media_time_pos / current_media_duration * (cfg.SLIDER_MAXIMUM - 1))
          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: float division by zero


**Loading an image after finishing a video:**
BORIS version: 8.11.2
OS: Windows 10 10.0.22621
CPU: AMD64 Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.9
2023-03-01 15:55

Traceback (most recent call last):
  File "C:\Users\Reinier\BORIS\Lib\site-packages\boris\core.py", line 3786, in mpv_timer_out
    round(current_media_time_pos / current_media_duration * (cfg.SLIDER_MAXIMUM - 1))
          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: float division by zero

**Starting the observation after reloading BORIS:**

BORIS version: 8.11.2
OS: Windows 10 10.0.22621
CPU: AMD64 Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.9
2023-03-01 15:56

Traceback (most recent call last):
  File "C:\Users\Reinier\BORIS\Lib\site-packages\boris\connections.py", line 95, in <lambda>
    lambda: observation_operations.open_observation(self, mode=cfg.OBS_START)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Reinier\BORIS\Lib\site-packages\boris\observation_operations.py", line 183, in open_observation
    return load_observation(self, selected_observations[0], mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Reinier\BORIS\Lib\site-packages\boris\observation_operations.py", line 233, in load_observation
    if not initialize_new_media_observation(self):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Reinier\BORIS\Lib\site-packages\boris\observation_operations.py", line 1661, in initialize_new_media_observation
    self.mpv_timer_out(value=0.0)
  File "C:\Users\Reinier\BORIS\Lib\site-packages\boris\core.py", line 3786, in mpv_timer_out
    round(current_media_time_pos / current_media_duration * (cfg.SLIDER_MAXIMUM - 1))
          ~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~
ZeroDivisionError: float division by zero

**Comment by olivierfriard** [comment]
Thanks!
I now able to obtain an error (but not your error for now).
Strangely, the FPS value obtained for your pictures is 0 on my system (Linux) and 25 on your system (windows).

![Screenshot_2023-03-01_17-04-29](https://user-images.githubusercontent.com/6529122/222195386-eca17f93-602d-451e-959d-beab24509a0d.png)

**Comment by vandenbergrf** [comment]
Another note on the durations:

Occasionally, it would throw up an error about the length of the .JPG's being 'NoneType'. So not all of the JPG's apparently get assigned a duration.

I worked around this by adding another 'if' check that bars any current_media_duration that's assigned "None" from triggering the first workaround check at line 3786.
I then put the same two checks around line 3745 where it prints the current media's "time / duration". 
Somehow, this works out alright and doesn't mess with the layout of the status window too much. 


![Status 2](https://user-images.githubusercontent.com/79840761/222207070-7d2403b6-98b1-4913-9e66-b6cbb6457eef.png)


![Status 1](https://user-images.githubusercontent.com/79840761/222207069-6a7469f4-1278-432a-a0f0-fdb3224c8708.png)
