### ISSUE TITLE
New bug refering to config_param!

### ISSUE THREAD

**Issue by paulagsotres** [olivierfriard/BORIS#589]
Hey everyone,

I just started playing around with BORIS and I found a bug I can't work around...am I missing something?
Thanks in advance for the help!

BORIS version: 8.11.1
OS: Windows 10 10.0.19044
CPU: AMD64 Intel64 Family 6 Model 165 Stepping 5, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.9
2023-03-02 19:10

Traceback (most recent call last):
  File "C:\Users\pgomez\Desktop\BORIS\Lib\site-packages\boris\project.py", line 236, in <lambda>
    self.pbExportEthogram.clicked.connect(lambda: project_import_export.export_ethogram(self))
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pgomez\Desktop\BORIS\Lib\site-packages\boris\project_import_export.py", line 135, in export_ethogram
    file_indentation = self.config_param.get(
                       ^^^^^^^^^^^^^^^^^
AttributeError: 'projectDialog' object has no attribute 'config_param'

**Comment by olivierfriard** [comment]
Hi,
thank you for reporting this issue.
It should be fixed in v. 8.11.3.
Please let me know.
