### ISSUE TITLE
BORIS 8.1.11 crashes when attempting to start new observation

### ISSUE THREAD

**Issue by PavoPavan** [olivierfriard/BORIS#594]
**Indicate the version of BORIS**
BORIS version: 8.11.1

**Describe the bug**
Crashing when attempting to start new observation

**To Reproduce**
1. Open project
2. Observations -> New obervation
3. From media file -> absolute path
4. Add video
5. Use media file name as observation id
6. Start observation
7. See error below

**Expected behavior**
The new observation should start

**Screenshots**

**Desktop (please complete the following information):**
BORIS version: 8.11.1 (setup)
OS: Windows 10 10.0.19045
CPU: AMD64 Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.9

**In case of crash** attach or copy the content of the boris.log file (before relaunching BORIS).

Traceback (most recent call last):
  File "C:\Users\utente\BORIS\Lib\site-packages\boris\connections.py", line 91, in <lambda>
    lambda: observation_operations.new_observation(self, mode=cfg.NEW, obsId="")
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\utente\BORIS\Lib\site-packages\boris\observation_operations.py", line 1079, in new_observation
    initialize_new_media_observation(self)
  File "C:\Users\utente\BORIS\Lib\site-packages\boris\observation_operations.py", line 1420, in initialize_new_media_observation
    self.dw_player[i].player.wait_until_paused()
  File "C:\Users\utente\BORIS\Lib\site-packages\boris\mpv2.py", line 1048, in wait_until_paused
    self.wait_for_property("core-idle", timeout=timeout)
  File "C:\Users\utente\BORIS\Lib\site-packages\boris\mpv2.py", line 1066, in wait_for_property
    with self.prepare_and_wait_for_property(name, cond, level_sensitive, timeout=timeout) as result:
  File "C:\Users\utente\BORIS\Lib\contextlib.py", line 144, in __exit__
    next(self.gen)
  File "C:\Users\utente\BORIS\Lib\site-packages\boris\mpv2.py", line 1125, in prepare_and_wait_for_property
    result.set_result(rv)
  File "C:\Users\utente\BORIS\Lib\concurrent\futures\_base.py", line 544, in set_result
    raise InvalidStateError('{}: {!r}'.format(self._state, self))
concurrent.futures._base.InvalidStateError: FINISHED: <Future at 0x200becec190 state=finished returned bool>

**Comment by olivierfriard** [comment]
Hi,
can you reproduce this issue with the current version (v. 8.13)?

**Comment by PavoPavan** [comment]
Version 8.13 has not this issue, thanks
