### ISSUE TITLE
wrong output in synthetic time budget

### ISSUE THREAD

**Issue by kicsibo** [olivierfriard/BORIS#604]
Hi,

When I try to get the coding results of at least two observations using the synthetic time budget option, I found that when the value would be 0 in a duration variable, if the value of the same variable is not 0 in the previous observation (row), then 0 is replaced by that number in the next observation (row).

For example, it looks like this, if the observation is chosen alone:
![image](https://user-images.githubusercontent.com/83514262/230367438-b89f810c-0a94-43df-bccb-647dfa5b0dd7.png)

But looks like this, if I select also a previous observation with values different from 0:
![image](https://user-images.githubusercontent.com/83514262/230366861-e4ebc8e7-e0bd-4f93-afac-78da805bd7f2.png)

It seems that it happens only with duration variables, but pls check all types.

I tried it out with previous Boris versions too, and it stayed the same.

Thanks in advance.

**Comment by olivierfriard** [comment]
Hi,
this issue should be fixed in v. 8.16.4
Please try and let me know
Thank you for your collaboration

**Comment by kicsibo** [comment]
Hi,
I downloaded the latest version to check, but when I tried to save the data as a .csv, suddenly I got the following error message. 

BORIS version: 8.16.5
OS: Windows 10 10.0.19045
CPU: AMD64 Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.9
2023-04-18 11:38

Traceback (most recent call last):
  File "C:\Users\Bogi\BORIS\Lib\site-packages\boris\connections.py", line 215, in <lambda>
    self.actionTime_budget_report.triggered.connect(lambda: synthetic_time_budget.synthetic_time_budget(self))
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bogi\BORIS\Lib\site-packages\boris\synthetic_time_budget.py", line 150, in synthetic_time_budget
    f.write(str.encode(data_report.export(output_format)))
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bogi\BORIS\Lib\site-packages\tablib\core.py", line 432, in export
    fmt = registry.get_format(format)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Bogi\BORIS\Lib\site-packages\tablib\formats\__init__.py", line 129, in get_format
    raise UnsupportedFormat("Tablib has no format '%s' or it is not registered." % key)
tablib.exceptions.UnsupportedFormat: Tablib has no format 'cvs' or it is not registered.

System info:

Host Name:                 DESKTOP-JD4SJ61
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19045 N/A Build 19045
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Windows-felhaszn l˘
Registered Organization:   
Product ID:                00330-80000-00000-AA573
Original Install Date:     2020. 08. 24., 17:28:01
System Boot Time:          2023. 04. 13., 7:06:57
System Manufacturer:       ASUSTeK COMPUTER INC.
System Model:              X550VX
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 94 Stepping 3 GenuineIntel ~2592 Mhz
BIOS Version:              American Megatrends Inc. X550VX.302, 2017. 05. 04.
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume3
System Locale:             hu;magyar
Input Locale:              hu;magyar
Time Zone:                 (UTC+01:00) Budapest, Belgr d, Ljubljana, Pozsony, Pr ga
Total Physical Memory:     24˙472 MB
Available Physical Memory: 17˙304 MB
Virtual Memory: Max Size:  28˙056 MB
Virtual Memory: Available: 20˙333 MB
Virtual Memory: In Use:    7˙723 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\DESKTOP-JD4SJ61
Hotfix(s):                 29 Hotfix(s) Installed.
                           [01]: KB5022502
                           [02]: KB4561600
                           [03]: KB4570334
                           [04]: KB4577266
                           [05]: KB4577586
                           [06]: KB4580325
                           [07]: KB4586864
                           [08]: KB4589212
                           [09]: KB4593175
                           [10]: KB4598481
                           [11]: KB5000736
                           [12]: KB5003791
                           [13]: KB5012170
                           [14]: KB5015684
                           [15]: KB5025221
                           [16]: KB5006753
                           [17]: KB5007273
                           [18]: KB5011352
                           [19]: KB5011651
                           [20]: KB5014032
                           [21]: KB5014035
                           [22]: KB5014671
                           [23]: KB5015895
                           [24]: KB5016705
                           [25]: KB5018506
                           [26]: KB5020372
                           [27]: KB5022924
                           [28]: KB5023794
                           [29]: KB5005699
Network Card(s):           4 NIC(s) Installed.
                           [01]: Realtek 8821AE Wireless LAN 802.11ac PCI-E NIC
                                 Connection Name: Wi-Fi
                                 Status:          Media disconnected
                           [02]: Realtek PCIe GbE Family Controller
                                 Connection Name: Ethernet
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.100.1
                                 IP address(es)
                                 [01]: 192.168.100.20
                                 [02]: fe80::8bb3:75da:a1da:f2a6
                                 [03]: 2a01:36d:103:7d5:f8aa:b03:4d68:3c8e
                                 [04]: 2a01:36d:103:7d5:af20:ba7c:c6c7:9a08
                           [03]: Fortinet Virtual Ethernet Adapter (NDIS 6.30)
                                 Connection Name: Ethernet 3
                                 Status:          Media disconnected
                           [04]: Fortinet SSL VPN Virtual Ethernet Adapter
                                 Connection Name: Ethernet 4
                                 Status:          Hardware not present
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by kicsibo** [comment]
It saves the results as .xlsx, but then the .xlsx file cannot be opened.

It works with .tsv, in that extension I could check that the bug is fixed, thank you.

Although pls check the saving options, because it seems that some of extensions are not working.

**Comment by olivierfriard** [comment]
Hi,
v. 8.16.6 should fix these 2 issues.
Thank you for your collaboration
