### ISSUE TITLE
Boris crashes frequently after switching from editing one observation to another

### ISSUE THREAD

**Issue by clearwingMSV** [olivierfriard/BORIS#609]
BORIS version: 8.16.3
OS: Windows 10 10.0.22000
CPU: AMD64 Intel64 Family 6 Model 158 Stepping 13, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.9
2023-04-19 12:34

Traceback (most recent call last):
  File "C:\Users\marta\BORIS\Lib\site-packages\boris\connections.py", line 96, in 
    self.actionObservationsList.triggered.connect(lambda: observation_operations.observations_list(self))
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marta\BORIS\Lib\site-packages\boris\observation_operations.py", line 142, in observations_list
    new_observation(self, mode=cfg.EDIT, obsId=selected_obs[0])  # observation id to edit
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\marta\BORIS\Lib\site-packages\boris\observation_operations.py", line 1088, in new_observation
    initialize_new_media_observation(self)
  File "C:\Users\marta\BORIS\Lib\site-packages\boris\observation_operations.py", line 1429, in initialize_new_media_observation
    self.dw_player[i].player.wait_until_paused()
  File "C:\Users\marta\BORIS\Lib\site-packages\boris\mpv2.py", line 981, in wait_until_paused
    self.wait_for_property('core-idle', timeout=timeout, catch_errors=catch_errors)
  File "C:\Users\marta\BORIS\Lib\site-packages\boris\mpv2.py", line 999, in wait_for_property
    with self.prepare_and_wait_for_property(name, cond, level_sensitive, timeout=timeout, catch_errors=catch_errors) as result:
  File "C:\Users\marta\BORIS\Lib\contextlib.py", line 137, in __enter__
    return next(self.gen)
           ^^^^^^^^^^^^^^
  File "C:\Users\marta\BORIS\Lib\site-packages\boris\mpv2.py", line 1047, in prepare_and_wait_for_property
    result.set_running_or_notify_cancel()
  File "C:\Users\marta\BORIS\Lib\concurrent\futures\_base.py", line 535, in set_running_or_notify_cancel
    raise RuntimeError('Future in unexpected state')
RuntimeError: Future in unexpected state

System info

Host Name:                 MARTA-SV
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22000 N/A Build 22000
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          marta.a.skowron@gmail.com
Registered Organization:   N/A
Product ID:                00330-52336-99264-AAOEM
Original Install Date:     19/12/2021, 12:45:14
System Boot Time:          16/04/2023, 21:54:52
System Manufacturer:       Dell Inc.
System Model:              OptiPlex 7470 AIO
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 158 Stepping 13 GenuineIntel ~2904 Mhz
BIOS Version:              Dell Inc. 1.11.0, 27/09/2021
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              pl;Polish
Time Zone:                 (UTC+01:00) Sarajevo, Skopje, Warsaw, Zagreb
Total Physical Memory:     7,991 MB
Available Physical Memory: 1,928 MB
Virtual Memory: Max Size:  12,343 MB
Virtual Memory: Available: 4,317 MB
Virtual Memory: In Use:    8,026 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\MARTA-SV
Hotfix(s):                 5 Hotfix(s) Installed.
                           [01]: KB5022505
                           [02]: KB5007575
                           [03]: KB5012170
                           [04]: KB5025224
                           [05]: KB5025388
Network Card(s):           2 NIC(s) Installed.
                           [01]: Intel(R) Wireless-AC 9560 160MHz
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.1.1
                                 IP address(es)
                                 [01]: 192.168.1.173
                                 [02]: fe80::8d9c:9fc9:e76f:a816
                           [02]: Intel(R) Ethernet Connection (7) I219-LM
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

**Comment by clearwingMSV** [comment]
[boris.log](https://github.com/olivierfriard/BORIS/files/11273349/boris.log)

And here is the log file after yet another crash. It has become impossible to work, Boris crashes constantly. Interestingly, it only occurs on one of my computers. I have also tried deleting the configuration file and relaunching Boris, however this only helped for several minutes.

**Comment by olivierfriard** [comment]
Hi,

I worked to fix this issue. Please try the version 8.16.7 and let me know.
You can download it at https://github.com/olivierfriard/BORIS/releases/tag/v8.16.7
Thank you for your collaboration

**Comment by clearwingMSV** [comment]
Dear Olivier,
thank you very much for helping in such short notice - all works fine now with the new version.

My best regards,
Marta
