### ISSUE TITLE
Unable to Open Any Observations 

### ISSUE THREAD

**Issue by ScubaSoule** [olivierfriard/BORIS#610]
BORIS version: 8.11.4
OS: Windows 10 10.0.22621
CPU: AMD64 Intel64 Family 6 Model 158 Stepping 13, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.9
2023-04-20 17:18

Traceback (most recent call last):
  File "C:\Users\samsoule\BORIS_8.11.4\Lib\site-packages\boris\connections.py", line 98, in <lambda>
    self.actionEdit_observation_2.triggered.connect(lambda: observation_operations.edit_observation(self))
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samsoule\BORIS_8.11.4\Lib\site-packages\boris\observation_operations.py", line 274, in edit_observation
    _, selected_observations = select_observations.select_observations2(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samsoule\BORIS_8.11.4\Lib\site-packages\boris\select_observations.py", line 80, in select_observations2
    interval = project_functions.observed_interval(pj[cfg.OBSERVATIONS][obs])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samsoule\BORIS_8.11.4\Lib\site-packages\boris\project_functions.py", line 1112, in observed_interval
    min(observation[cfg.EVENTS])[cfg.PJ_OBS_FIELDS[observation[cfg.TYPE]][cfg.TIME]],
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'str' and 'int'
j

**Comment by olivierfriard** [comment]
Hi,

can you repeat this issue with the last version (8.16.6)?

**Comment by ScubaSoule** [comment]
Hi there,

Yes I downloaded the latest issue of BORIS and created a new project and
imported my ethogram and observations from the previous project and i ended
up getting the same error.

I will post it now on github.

Cheers,
Sam

**Comment by ScubaSoule** [comment]
BORIS version: 8.16.6
OS: Windows 10 10.0.22621
CPU: AMD64 Intel64 Family 6 Model 158 Stepping 13, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.9
2023-04-21 13:37

Traceback (most recent call last):
  File "C:\Users\samsoule\Lib\site-packages\boris\connections.py", line 95, in <lambda>
    self.actionEdit_observation_2.triggered.connect(lambda: observation_operations.edit_observation(self))
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samsoule\Lib\site-packages\boris\observation_operations.py", line 274, in edit_observation
    _, selected_observations = select_observations.select_observations2(
                               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samsoule\Lib\site-packages\boris\select_observations.py", line 80, in select_observations2
    interval = project_functions.observed_interval(pj[cfg.OBSERVATIONS][obs])
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\samsoule\Lib\site-packages\boris\project_functions.py", line 1363, in observed_interval
    min(observation[cfg.EVENTS])[
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: '<' not supported between instances of 'str' and 'int'

System info:

Host Name:                 SAMUELELLIN9568
OS Name:                   Microsoft Windows 11 Home
OS Version:                10.0.22621 N/A Build 22621
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Samuel Ellington Soule
Registered Organization:   
Product ID:                00326-10000-00000-AA155
Original Install Date:     10/9/2022, 11:07:33 PM
System Boot Time:          4/11/2023, 1:25:13 PM
System Manufacturer:       Parallels Software International Inc.
System Model:              Parallels Virtual Platform
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 158 Stepping 13 GenuineIntel ~2304 Mhz
BIOS Version:              Parallels Software International Inc. 18.2.0 (53488), 2/10/2023
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume2
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC+01:00) Belgrade, Bratislava, Budapest, Ljubljana, Prague
Total Physical Memory:     6,125 MB
Available Physical Memory: 2,210 MB
Virtual Memory: Max Size:  9,581 MB
Virtual Memory: Available: 3,887 MB
Virtual Memory: In Use:    5,694 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\SAMUELELLIN9568
Hotfix(s):                 5 Hotfix(s) Installed.
                           [01]: KB5022497
                           [02]: KB5012170
                           [03]: KB5022845
                           [04]: KB5022610
                           [05]: KB5020487
Network Card(s):           1 NIC(s) Installed.
                           [01]: Parallels VirtIO Ethernet Adapter
                                 Connection Name: Ethernet
                                 DHCP Enabled:    Yes
                                 DHCP Server:     10.211.55.1
                                 IP address(es)
                                 [01]: 10.211.55.3
                                 [02]: fe80::64c4:72bb:672d:14fa
                                 [03]: fdb2:2c26:f4e4:0:55f5:e4ec:c57a:21e
                                 [04]: fdb2:2c26:f4e4:0:4211:b78c:1d8b:5b26
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by olivierfriard** [comment]
Could you send me a copy of your project (by email) and a detailed procedure to repeat the issue?

**Comment by olivierfriard** [comment]
I did not receive your project file.
Please send it to me by email (check http://www.boris.unito.it/pages/about.html )
I will keep it for my eyes only.

Did you copy/paste events from BORIS or from another sources?

**Comment by olivierfriard** [comment]
Hi Sam,
this issue should be fixed in v. 8.18.1 just released.
Can you test it and let me know?

You should also check your project file with the Check project integrity function (See Project > ...) as some observations have errors

Thank you for your collaboration

**Comment by ScubaSoule** [comment]
Hi there, after downloading and extracting the newest version, boris-8.18.1-win64.zip, I am unable to open this version from the "start boris.wbf" file. It opens for a second then immediately closes.

**Comment by olivierfriard** [comment]
Hi,
can you send me the boris.log and boris_error.log files just after the crash?

**Comment by ScubaSoule** [comment]
Hi There, 
Where would i find those log files?

**Comment by olivierfriard** [comment]
See http://www.boris.unito.it/pages/report_a_bug.html
Now you can try v. 8.19: https://github.com/olivierfriard/BORIS/releases/tag/v8.19
