### ISSUE TITLE
Unable to open observations

### ISSUE THREAD

**Issue by daclein** [olivierfriard/BORIS#618]
**Indicate the version of BORIS**
8.19.1

**Describe the bug**
I am unable to upload observation video files in the new version of Boris, I am trying to use multiple players to view multiple videos at the same time

**To Reproduce**
1. Select new observation
2. Click on 'observation from media file'
3. Add media with absolute path 
4. Select media file
5. See error

BORIS version: 8.19.1
OS: Windows 10 10.0.19045
CPU: AMD64 Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.9
2023-05-11 10:01

Traceback (most recent call last):
  File "C:\Users\daclein99\BORIS-New\Lib\site-packages\boris\observation.py", line 140, in 
    menu.triggered.connect(lambda x: self.add_media(mode=x.statusTip()))
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daclein99\BORIS-New\Lib\site-packages\boris\observation.py", line 1138, in add_media
    (error, msg) = self.check_media(file_path, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daclein99\BORIS-New\Lib\site-packages\boris\observation.py", line 1040, in check_media
    media_info = util.accurate_media_analysis(self.ffmpeg_bin, file_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daclein99\BORIS-New\Lib\site-packages\boris\utilities.py", line 1241, in accurate_media_analysis
    ffprobe_results = ffprobe_media_analysis(ffmpeg_bin, file_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\daclein99\BORIS-New\Lib\site-packages\boris\utilities.py", line 1208, in ffprobe_media_analysis
    "audio_duration": audio_duration,
                      ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'audio_duration' where it is not associated with a value

System info

Host Name:                 IF-ANS-1S1DF42
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19045 N/A Build 19045
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          IFAS
Registered Organization:   University of Florida
Product ID:                00329-00000-00003-AA638
Original Install Date:     7/20/2021, 8:58:42 AM
System Boot Time:          4/27/2023, 5:32:00 AM
System Manufacturer:       Dell Inc.
System Model:              OptiPlex 9020
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 60 Stepping 3 GenuineIntel ~3601 Mhz
BIOS Version:              Dell Inc. A11, 4/1/2015
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume2
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     16,292 MB
Available Physical Memory: 7,764 MB
Virtual Memory: Max Size:  18,724 MB
Virtual Memory: Available: 7,511 MB
Virtual Memory: In Use:    11,213 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    ad.ufl.edu
Logon Server:              \\MC-AZ1DCP1
Hotfix(s):                 25 Hotfix(s) Installed.
                           [01]: KB5022502
                           [02]: KB4562830
                           [03]: KB4570334
                           [04]: KB4577266
                           [05]: KB4577586
                           [06]: KB4580325
                           [07]: KB4589212
                           [08]: KB4598481
                           [09]: KB5012170
                           [10]: KB5015684
                           [11]: KB5025221
                           [12]: KB5006753
                           [13]: KB5007273
                           [14]: KB5011352
                           [15]: KB5011651
                           [16]: KB5014032
                           [17]: KB5014035
                           [18]: KB5014671
                           [19]: KB5015895
                           [20]: KB5016705
                           [21]: KB5018506
                           [22]: KB5020372
                           [23]: KB5022924
                           [24]: KB5023794
                           [25]: KB5005699
Network Card(s):           1 NIC(s) Installed.
                           [01]: Intel(R) Ethernet Connection I217-LM
                                 Connection Name: Ethernet
                                 DHCP Enabled:    Yes
                                 DHCP Server:     10.36.24.11
                                 IP address(es)
                                 [01]: 10.250.30.110
                                 [02]: fe80::8ff0:ba30:c4b6:df8c
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

**Comment by olivierfriard** [comment]
Hi,
v. 8.19.3 should fix this issue.
Can you try and let me know?
