### ISSUE TITLE
Cannot export observation as an Excel file

### ISSUE THREAD

**Issue by calstudent24** [olivierfriard/BORIS#622]
**Indicate the version of BORIS**
8.19.3

**Describe the bug**
Whenever I try to export the aggregated observation as an excel file, an error message pops up.

**To Reproduce**
1. Go to 'Observations'
2. Click on 'Export events'
4. Click on 'Aggregated events'
5. Select observation
6. Click 'OK'
7. Select all for both subjects and behaviors
8. Click 'OK'
9. Save file as a Microsoft excel file.

**Expected behavior**
The observation is exported as an excel file.

**Screenshots**
BORIS version: 8.19.3
OS: Windows 10 10.0.19043
CPU: AMD64 Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.9
2023-05-25 14:50

Traceback (most recent call last):
  File "C:\Users\sydne\BORIS\Lib\site-packages\boris\export_events.py", line 505, in export_aggregated_events
    *sorted(list(data_single_obs), key=lambda x: float(x[index])),
     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sydne\BORIS\Lib\site-packages\boris\export_events.py", line 505, in 
    *sorted(list(data_single_obs), key=lambda x: float(x[index])),
                                                 ^^^^^^^^^^^^^^^
ValueError: could not convert string to float: 'STATE'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\sydne\BORIS\Lib\site-packages\boris\connections.py", line 143, in 
    self.actionExport_aggregated_events.triggered.connect(lambda: export_events.export_aggregated_events(self))
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\sydne\BORIS\Lib\site-packages\boris\export_events.py", line 518, in export_aggregated_events
    data_single_obs_sorted = tablib.Dataset(
                             ^^^^^^^^^^^^^^^
  File "C:\Users\sydne\BORIS\Lib\site-packages\tablib\core.py", line 158, in __init__
    self.headers = kwargs.get('headers')
    ^^^^^^^^^^^^
  File "C:\Users\sydne\BORIS\Lib\site-packages\tablib\core.py", line 301, in _set_headers
    self._validate(collection)
  File "C:\Users\sydne\BORIS\Lib\site-packages\tablib\core.py", line 254, in _validate
    raise InvalidDimensions
tablib.exceptions.InvalidDimensions

System info

Host Name:                 DESKTOP-IT76SD7
OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.19043 N/A Build 19043
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          sydneytran02@gmail.com
Registered Organization:   
Product ID:                00326-10000-00000-AA710
Original Install Date:     8/27/2021, 4:55:31 PM
System Boot Time:          5/25/2023, 2:43:12 PM
System Manufacturer:       Apple Inc.
System Model:              MacBookPro16,1
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 158 Stepping 10 GenuineIntel ~2601 Mhz
BIOS Version:              Apple Inc. 1968.100.17.0.0 (iBridge: 20.16.4252.0.0,0), 3/4/2023
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-08:00) Pacific Time (US & Canada)
Total Physical Memory:     16,278 MB
Available Physical Memory: 12,117 MB
Virtual Memory: Max Size:  19,222 MB
Virtual Memory: Available: 11,715 MB
Virtual Memory: In Use:    7,507 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\DESKTOP-IT76SD7
Hotfix(s):                 4 Hotfix(s) Installed.
                           [01]: KB5004331
                           [02]: KB5000736
                           [03]: KB5005033
                           [04]: KB5005260
Network Card(s):           2 NIC(s) Installed.
                           [01]: Broadcom 802.11ac Network Adapter
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     10.0.0.1
                                 IP address(es)
                                 [01]: 10.0.0.3
                                 [02]: fe80::60f6:fa15:7467:94d1
                                 [03]: 2601:204:e97f:f620:74ee:5e03:be04:799b
                                 [04]: 2601:204:e97f:f620:60f6:fa15:7467:94d1
                                 [05]: 2601:204:e97f:f620::7931
                           [02]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

**Comment by olivierfriard** [comment]
Hi,
I am not able to reproduce this issue.
Is it possible to send me your project file and a detailed procedure to reproduce the issue?
Thank you for your collaboration

**Comment by alliofroggio** [comment]
I'm also having this issue. I have six observations that I'm exporting, the others have exported aggregated events without issue. This observation will not generate an export events. The observation is viewable with no issues (no unpaired events, etc.). My expected behaviour though was a TSV files (as that is how the other observations exported; I do open them in Excel after).

Was there a fix for the above? 

Here is my error code:

An error has occured

to improve the software please report this problem at:
https://github.com/olivierfriard/BORIS/issues
Please no screenshot, the error message was copied to the clipboard.

Thank you for your collaboration!


BORIS version: 8.22.15
OS: Windows 10 10.0.19045
CPU: AMD64 Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.10
2024-01-15 09:07

Traceback (most recent call last):
  File "C:\Users\Allison Van Beek\BORIS\Lib\site-packages\boris\connections.py", line 147, in 
    self.actionExport_aggregated_events.triggered.connect(lambda: export_events.export_aggregated_events(self))
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Allison Van Beek\BORIS\Lib\site-packages\boris\export_events.py", line 460, in export_aggregated_events
    _, max_modifiers = export_observation.export_aggregated_events(self.pj, parameters, obs_id)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Allison Van Beek\BORIS\Lib\site-packages\boris\export_observation.py", line 774, in export_aggregated_events
    media_file_name = observation_operations.event2media_file_name(observation, row["start"])
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Allison Van Beek\BORIS\Lib\site-packages\boris\observation_operations.py", line 2044, in event2media_file_name
    media_duration = dec(str(observation[cfg.MEDIA_INFO][cfg.LENGTH][media_file]))
                             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'C:/Users/Alli/Videos/Temp Lecture Capture Storage/ALC04/Cam1_Aud_ALC04_Blueberry_20200311_1710.mp4'


System info

Host Name:                 ALLI-DOCKED
OS Name:                   Microsoft Windows 10 Pro
OS Version:                10.0.19045 N/A Build 19045
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Allison Van Beek
Registered Organization:   N/A
Product ID:                00330-52697-68683-AAOEM
Original Install Date:     2021-03-23, 4:12:34 PM
System Boot Time:          2024-01-13, 7:15:36 PM
System Manufacturer:       Dell Inc.
System Model:              XPS 15 7590
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 158 Stepping 10 GenuineIntel ~2592 Mhz
BIOS Version:              Dell Inc. 1.12.0, 2021-06-10
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     32,495 MB
Available Physical Memory: 17,257 MB
Virtual Memory: Max Size:  37,359 MB
Virtual Memory: Available: 14,660 MB
Virtual Memory: In Use:    22,699 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\ALLI-DOCKED
Hotfix(s):                 34 Hotfix(s) Installed.
                           [01]: KB5033918
                           [02]: KB5028853
                           [03]: KB4562830
                           [04]: KB4577586
                           [05]: KB4580325
                           [06]: KB4589212
                           [07]: KB5003791
                           [08]: KB5011048
                           [09]: KB5012170
                           [10]: KB5015684
                           [11]: KB5034122
                           [12]: KB5006753
                           [13]: KB5007273
                           [14]: KB5011352
                           [15]: KB5011651
                           [16]: KB5014032
                           [17]: KB5014035
                           [18]: KB5014671
                           [19]: KB5015895
                           [20]: KB5016705
                           [21]: KB5018506
                           [22]: KB5020372
                           [23]: KB5022924
                           [24]: KB5023794
                           [25]: KB5025315
                           [26]: KB5026879
                           [27]: KB5028318
                           [28]: KB5028380
                           [29]: KB5029709
                           [30]: KB5031539
                           [31]: KB5032392
                           [32]: KB5032907
                           [33]: KB5005699
                           [34]: KB5034441
Network Card(s):           5 NIC(s) Installed.
                           [01]: Cisco AnyConnect Secure Mobility Client Virtual Miniport Adapter for Windows x64
                                 Connection Name: Ethernet 2
                                 Status:          Hardware not present
                           [02]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
                           [03]: Killer(R) Wi-Fi 6 AX1650x 160MHz Wireless Network Adapter (200NGW)
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.7.1
                                 IP address(es)
                                 [01]: 192.168.7.43
                                 [02]: fe80::ab9c:7065:204a:d405
                           [04]: OpenVPN Data Channel Offload
                                 Connection Name: PrivadoVPN (OpenVPN DCO)
                                 Status:          Media disconnected
                           [05]: TAP-Windows Adapter V9
                                 Connection Name: PrivadoVPN (OpenVPN)
                                 Status:          Media disconnected
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

**Comment by olivierfriard** [comment]
@alliofroggio

is it possible to access your project file?
You can contact me by email if you prefer (olivier.friard@unito.it)

**Comment by alliofroggio** [comment]
This is my bad. A colleague resolved the issue by re uploading the media
file. I'm not sure what caused it but this fixed it.
