### ISSUE TITLE
Error on opening observation

### ISSUE THREAD

**Issue by DigDigDig** [olivierfriard/BORIS#637]
BORIS version: 8.20.4
OS: Windows 10 10.0.19045
CPU: AMD64 Intel64 Family 6 Model 85 Stepping 4, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.9
2023-08-01 10:57

Traceback (most recent call last):
  File "C:\Users\StevenSabo\BORIS\Lib\site-packages\boris\connections.py", line 223, in 
    self.action_obs_list.triggered.connect(lambda: observation_operations.observations_list(self))
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\StevenSabo\BORIS\Lib\site-packages\boris\observation_operations.py", line 127, in observations_list
    load_observation(self, selected_obs[0], cfg.OBS_START)
  File "C:\Users\StevenSabo\BORIS\Lib\site-packages\boris\observation_operations.py", line 221, in load_observation
    if not initialize_new_media_observation(self):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\StevenSabo\BORIS\Lib\site-packages\boris\observation_operations.py", line 1581, in initialize_new_media_observation
    self.seek_mediaplayer(int(self.pj[cfg.OBSERVATIONS][self.observationId][cfg.OBSERVATION_TIME_INTERVAL][0]), player=i)
  File "C:\Users\StevenSabo\BORIS\Lib\site-packages\boris\core.py", line 1395, in seek_mediaplayer
    self.dw_player[player].player.seek(
  File "C:\Users\StevenSabo\BORIS\Lib\site-packages\boris\mpv2.py", line 1235, in seek
    self.command('seek', amount, reference, precision)
  File "C:\Users\StevenSabo\BORIS\Lib\site-packages\boris\mpv2.py", line 1228, in command
    _mpv_command_node(self.handle, ppointer, out)
  File "C:\Users\StevenSabo\BORIS\Lib\site-packages\boris\mpv2.py", line 148, in raise_for_ec
    raise ex
SystemError: ('Error running mpv command', -12, (, , ))

System info

Host Name:                 IE-STEVEN2019
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19045 N/A Build 19045
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          ssabo
Registered Organization:   N/A
Product ID:                00391-70000-00000-AA193
Original Install Date:     9/26/2020, 11:33:45 PM
System Boot Time:          7/31/2023, 5:05:31 PM
System Manufacturer:       Dell Inc.
System Model:              Precision 5820 Tower
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 85 Stepping 4 GenuineIntel ~3696 Mhz
BIOS Version:              Dell Inc. 2.30.0, 5/30/2023
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     65,207 MB
Available Physical Memory: 48,558 MB
Virtual Memory: Max Size:  81,207 MB
Virtual Memory: Available: 56,054 MB
Virtual Memory: In Use:    25,153 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\IE-STEVEN2019
Hotfix(s):                 34 Hotfix(s) Installed.
                           [01]: KB5028849
                           [02]: KB5027122
                           [03]: KB4561600
                           [04]: KB4562830
                           [05]: KB4577266
                           [06]: KB4577586
                           [07]: KB4580325
                           [08]: KB4586864
                           [09]: KB4589212
                           [10]: KB4593175
                           [11]: KB4598481
                           [12]: KB5000736
                           [13]: KB5003791
                           [14]: KB5011048
                           [15]: KB5012170
                           [16]: KB5015684
                           [17]: KB5028166
                           [18]: KB5006753
                           [19]: KB5007273
                           [20]: KB5011352
                           [21]: KB5011651
                           [22]: KB5014032
                           [23]: KB5014035
                           [24]: KB5014671
                           [25]: KB5015895
                           [26]: KB5016705
                           [27]: KB5018506
                           [28]: KB5020372
                           [29]: KB5022924
                           [30]: KB5023794
                           [31]: KB5025315
                           [32]: KB5026879
                           [33]: KB5028318
                           [34]: KB5005699
Network Card(s):           3 NIC(s) Installed.
                           [01]: TAP-Windows Adapter V9
                                 Connection Name: Ethernet 2
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.117.254
                                 IP address(es)
                                 [01]: 192.168.117.5
                                 [02]: fe80::e9b1:353c:97e5:2d30
                           [02]: Intel(R) Ethernet Connection (5) I219-LM
                                 Connection Name: Ethernet
                                 DHCP Enabled:    Yes
                                 DHCP Server:     10.0.0.1
                                 IP address(es)
                                 [01]: 10.0.0.32
                                 [02]: fe80::917e:3d0c:88d7:1a2d
                                 [03]: 2601:403:c100:f8a0:5cde:86ae:5c5e:57d4
                                 [04]: 2601:403:c100:f8a0:4a33:4dc4:9b4c:7bd7
                                 [05]: 2601:403:c100:f8a0::6986
                           [03]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: No
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

**Comment by DigDigDig** [comment]
I receive this error when I start any observation in BORIS.  I can ignore and try to continue but this removes functionality like timeline plotting, playback speed adjustments, and others.  It also results in N/A being listed in the frame count of events I log to the timeline.

**Comment by olivierfriard** [comment]
Hi,
did you set some parameters in your observation (like offset, observation interval ...)?

**Comment by igutermes** [comment]
I have the same problem. 
Running on Ubuntu 23.04

**Comment by DigDigDig** [comment]
@olivierfriard 

I updated to the most recent BORIS version (8.21.8) and am receiving the same error as in prior releases.  

Any idea what could be causing this or how I could resolve it?

An error has occured

to improve the software please report this problem at:
https://github.com/olivierfriard/BORIS/issues
Please no screenshot, the error message was copied to the clipboard.

Thank you for your collaboration!


BORIS version: 8.21.8
OS: Windows 10 10.0.19045
CPU: AMD64 Intel64 Family 6 Model 85 Stepping 4, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.9
2023-11-03 09:30

Traceback (most recent call last):
  File "C:\Users\StevenSabo\BORIS\Lib\site-packages\boris\connections.py", line 224, in 
    self.action_obs_list.triggered.connect(lambda: observation_operations.observations_list(self))
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\StevenSabo\BORIS\Lib\site-packages\boris\observation_operations.py", line 127, in observations_list
    load_observation(self, selected_obs[0], cfg.OBS_START)
  File "C:\Users\StevenSabo\BORIS\Lib\site-packages\boris\observation_operations.py", line 221, in load_observation
    if not initialize_new_media_observation(self):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\StevenSabo\BORIS\Lib\site-packages\boris\observation_operations.py", line 1580, in initialize_new_media_observation
    self.seek_mediaplayer(int(self.pj[cfg.OBSERVATIONS][self.observationId][cfg.OBSERVATION_TIME_INTERVAL][0]), player=i)
  File "C:\Users\StevenSabo\BORIS\Lib\site-packages\boris\core.py", line 1406, in seek_mediaplayer
    self.dw_player[player].player.seek(
  File "C:\Users\StevenSabo\BORIS\Lib\site-packages\boris\mpv2.py", line 1235, in seek
    self.command('seek', amount, reference, precision)
  File "C:\Users\StevenSabo\BORIS\Lib\site-packages\boris\mpv2.py", line 1228, in command
    _mpv_command_node(self.handle, ppointer, out)
  File "C:\Users\StevenSabo\BORIS\Lib\site-packages\boris\mpv2.py", line 148, in raise_for_ec
    raise ex
SystemError: ('Error running mpv command', -12, (, , ))


System info

Host Name:                 IE-STEVEN2019
OS Name:                   Microsoft Windows 10 Pro for Workstations
OS Version:                10.0.19045 N/A Build 19045
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          ssabo
Registered Organization:   N/A
Product ID:                00391-70000-00000-AA193
Original Install Date:     9/26/2020, 11:33:45 PM
System Boot Time:          10/30/2023, 3:23:54 PM
System Manufacturer:       Dell Inc.
System Model:              Precision 5820 Tower
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 85 Stepping 4 GenuineIntel ~3696 Mhz
BIOS Version:              Dell Inc. 2.30.0, 5/30/2023
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     65,207 MB
Available Physical Memory: 32,639 MB
Virtual Memory: Max Size:  113,207 MB
Virtual Memory: Available: 47,403 MB
Virtual Memory: In Use:    65,804 MB
Page File Location(s):     C:\pagefile.sys
                           D:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\IE-STEVEN2019
Hotfix(s):                 37 Hotfix(s) Installed.
                           [01]: KB5030649
                           [02]: KB5027122
                           [03]: KB4561600
                           [04]: KB4562830
                           [05]: KB4577266
                           [06]: KB4577586
                           [07]: KB4580325
                           [08]: KB4586864
                           [09]: KB4589212
                           [10]: KB4593175
                           [11]: KB4598481
                           [12]: KB5000736
                           [13]: KB5003791
                           [14]: KB5011048
                           [15]: KB5012170
                           [16]: KB5015684
                           [17]: KB5031356
                           [18]: KB5006753
                           [19]: KB5007273
                           [20]: KB5011352
                           [21]: KB5011651
                           [22]: KB5014032
                           [23]: KB5014035
                           [24]: KB5014671
                           [25]: KB5015895
                           [26]: KB5016705
                           [27]: KB5018506
                           [28]: KB5020372
                           [29]: KB5022924
                           [30]: KB5023794
                           [31]: KB5025315
                           [32]: KB5026879
                           [33]: KB5028318
                           [34]: KB5028380
                           [35]: KB5029709
                           [36]: KB5031539
                           [37]: KB5005699
Network Card(s):           3 NIC(s) Installed.
                           [01]: TAP-Windows Adapter V9
                                 Connection Name: Ethernet 2
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.117.254
                                 IP address(es)
                                 [01]: 192.168.117.8
                                 [02]: fe80::e9b1:353c:97e5:2d30
                           [02]: Intel(R) Ethernet Connection (5) I219-LM
                                 Connection Name: Ethernet
                                 DHCP Enabled:    Yes
                                 DHCP Server:     10.0.0.1
                                 IP address(es)
                                 [01]: 10.0.0.32
                                 [02]: fe80::917e:3d0c:88d7:1a2d
                                 [03]: 2601:403:c100:f8a0:8cee:7bcb:8a73:e872
                                 [04]: 2601:403:c100:f8a0:2d27:2c87:a86d:b1fe
                                 [05]: 2601:403:c100:f8a0:4a33:4dc4:9b4c:7bd7
                                 [06]: 2601:403:c100:f8a0::6a0
                           [03]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: No
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes
