### ISSUE TITLE
Suggestions for UI improvements

### ISSUE THREAD

**Issue by BenCallisto** [olivierfriard/BORIS#639]
**The following observations and suggestions are mainly regarding the observation UI**

Would it be possible to exclude certain codes from the code pad? I use my numpad for position codes blindly and a code pad on a touchscreen for everything more specific, but haven't found a way yet to remove the numpad codes.

In regards to my point above, the standard widgets like events list and code list can be docked straight into the main frame of the BORIS window, yet the code pad for example is an external new window. pushing a button on the code pad changes the keyboard input to that window, hence you cannot continue your observation playback with the space bar unless you click back on the main window of BORIS. Can we also dock the code pad?

(Lastly regarding project codes, could it be possible to drag shift codes in the code list of the project under "edit project"? I colorcode and categorize all my codes, but sometimes add new ones down the line to an earlier category. It would be useful to be able to visually group all connected codes in the edit window.) <- Clarified and fixed by DigDigDig

Thank you for your work!

**Comment by DigDigDig** [comment]
I just discovered that you can sort codes by category, name, etc in the ethogram window.  

I've been wanting a way to organize my ethogram codes better after I've entered them in and discovering that I can click that window has been really helpful.

**Comment by BenCallisto** [comment]
> I just discovered that you can sort codes by category, name, etc in the ethogram window.
> 
> I've been wanting a way to organize my ethogram codes better after I've entered them in and discovering that I can click that window has been really helpful.

You are right, I haven't seen that earlier, thank you!

**Comment by olivierfriard** [comment]
you can also filter the behaviors in the ethogram table by right-clicking in the table header.
This will filter behaviors in the ethogram table and in the coding pad.
The filtered behaviors will be saved for the current observation.

**Comment by BenCallisto** [comment]
Thank you for your work! The time scrubbing works indeed much more stable now, however, have you removed the player controls from the main window to the top menu bar? (see screenshot)

![image](https://github.com/olivierfriard/BORIS/assets/141143791/6e8faea6-55b3-4f24-a19e-c7daadd6f021)

And, when I tried to plot all occured events, the following crash log showed up:

BORIS version: 8.21.7
OS: Windows 10 10.0.22621
CPU: AMD64 Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.9
2023-10-03 21:59

Traceback (most recent call last):
  File "C:\Users\user\BORIS\Lib\site-packages\boris\connections.py", line 208, in <lambda>
    self.actionPlot_events2.triggered.connect(lambda: self.plot_events_triggered(mode="list"))
                                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\BORIS\Lib\site-packages\boris\core.py", line 2470, in plot_events_triggered
    plot_events.create_events_plot(
  File "C:\Users\user\BORIS\Lib\site-packages\boris\plot_events.py", line 410, in create_events_plot
    fig, ax = plt.subplots(figsize=(20, 8), nrows=len(selected_subjects), ncols=1, sharex=True)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\BORIS\Lib\site-packages\matplotlib\pyplot.py", line 1598, in subplots
    fig = figure(**fig_kw)
          ^^^^^^^^^^^^^^^^
  File "C:\Users\user\BORIS\Lib\site-packages\matplotlib\pyplot.py", line 934, in figure
    manager = new_figure_manager(
              ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\BORIS\Lib\site-packages\matplotlib\pyplot.py", line 465, in new_figure_manager
    return _get_backend_mod().new_figure_manager(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\BORIS\Lib\site-packages\matplotlib\backend_bases.py", line 3396, in new_figure_manager
    return cls.new_figure_manager_given_figure(num, fig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\BORIS\Lib\site-packages\matplotlib\backend_bases.py", line 3401, in new_figure_manager_given_figure
    return cls.FigureCanvas.new_manager(figure, num)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\BORIS\Lib\site-packages\matplotlib\backend_bases.py", line 1785, in new_manager
    return cls.manager_class.create_with_canvas(cls, figure, num)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\BORIS\Lib\site-packages\matplotlib\backend_bases.py", line 2680, in create_with_canvas
    return cls(canvas_class(figure), num)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\BORIS\Lib\site-packages\matplotlib\backends\backend_qt.py", line 522, in __init__
    super().__init__(canvas, num)
  File "C:\Users\user\BORIS\Lib\site-packages\matplotlib\backend_bases.py", line 2654, in __init__
    self.toolbar = self._toolbar2_class(self.canvas)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\BORIS\Lib\site-packages\matplotlib\backends\backend_qt.py", line 669, in __init__
    NavigationToolbar2.__init__(self, canvas)
  File "C:\Users\user\BORIS\Lib\site-packages\matplotlib\backend_bases.py", line 2844, in __init__
    self._nav_stack = cbook._Stack()
                      ^^^^^^^^^^^^
  File "C:\Users\user\BORIS\Lib\site-packages\matplotlib\_api\__init__.py", line 217, in __getattr__
    raise AttributeError(
AttributeError: module 'matplotlib.cbook' has no attribute '_Stack'

System info:

Host Name:                 SURFACE_STUDIO
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22621 N/A Build 22621
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          user
Registered Organization:   N/A
Product ID:                00330-80000-00000-AA918
Original Install Date:     12/04/2023, 13:33:25
System Boot Time:          18/09/2023, 21:06:20
System Manufacturer:       Microsoft Corporation
System Model:              Surface Studio 2
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 158 Stepping 9 GenuineIntel ~2904 Mhz
BIOS Version:              Microsoft Corporation 536.645.768, 05/04/2015
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume2
System Locale:             de;German (Germany)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
Total Physical Memory:     32,725 MB
Available Physical Memory: 25,025 MB
Virtual Memory: Max Size:  34,773 MB
Virtual Memory: Available: 22,198 MB
Virtual Memory: In Use:    12,575 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\SURFACE_STUDIO
Hotfix(s):                 4 Hotfix(s) Installed.
                           [01]: KB5029921
                           [02]: KB5012170
                           [03]: KB5030219
                           [04]: KB5028756
Network Card(s):           4 NIC(s) Installed.
                           [01]: Xbox Wireless Adapter for Windows
                                 Connection Name: LAN-Verbindung
                                 DHCP Enabled:    No
                                 IP address(es)
                           [02]: Intel(R) Ethernet Connection (2) I219-V
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [03]: Marvell AVASTAR Wireless-AC Network Controller
                                 Connection Name: WLAN
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.178.1
                                 IP address(es)
                                 [01]: 192.168.178.50
                                 [02]: fe80::b1e2:ccf3:2c37:e96e
                                 [03]: 2001:1c06:2712:d00:b4c6:6b28:be4:3bd4
                                 [04]: 2001:1c06:2712:d00:4c4c:8d33:1e8f:99b2
                           [04]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth-Netzwerkverbindung
                                 Status:          Media disconnected
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes
