### ISSUE TITLE
Error when one media file ends and the next starts

### ISSUE THREAD

**Issue by Asajoh** [olivierfriard/BORIS#646]
The problem occurs when I have several media files in one observation. As I am watching the videos and coding behaviours, the error pasted below happens as the video ends and the next starts. I have ticked the box to ask Boris to end state events at the end of each media file. Not sure if this bug is related to that. Also, Boris interprets the media files as having 1000 frames per second (but plays back at right speed regardless). This may be important as the bug seems to happen as a consequence of trying to convert time (utilities.py lines 196 and 979). The error output is below.

BORIS version: 8.20.4
OS: Windows 10 10.0.22621
CPU: AMD64 Intel64 Family 6 Model 154 Stepping 3, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.9
2023-09-01 13:39

Traceback (most recent call last):
  File "C:\Users\asajoh\BORIS\Lib\site-packages\boris\core.py", line 4063, in mpv_timer_out
    f"{util.convertTime(self.timeFormat, current_media_duration)} frame: {frame_idx}"
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\asajoh\BORIS\Lib\site-packages\boris\utilities.py", line 196, in convertTime
    return seconds2time(sec)
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\asajoh\BORIS\Lib\site-packages\boris\utilities.py", line 979, in seconds2time
    if math.isnan(sec):
       ^^^^^^^^^^^^^^^
TypeError: must be real number, not NoneType

System info

Host Name:                 LAPTOP-ASAJOH
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22621 N/A Build 22621
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          install
Registered Organization:   N/A
Product ID:                00355-62922-64788-AAOEM
Original Install Date:     27.02.2023, 08:49:48
System Boot Time:          22.08.2023, 08:25:49
System Manufacturer:       LENOVO
System Model:              21D8000EMX
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 154 Stepping 3 GenuineIntel ~2300 Mhz
BIOS Version:              LENOVO N3EET27W (1.13 ), 09.12.2022
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              fo;Faeroese
Time Zone:                 (UTC+00:00) Dublin, Edinburgh, Lisbon, London
Total Physical Memory:     32.466 MB
Available Physical Memory: 16.632 MB
Virtual Memory: Max Size:  34.514 MB
Virtual Memory: Available: 14.253 MB
Virtual Memory: In Use:    20.261 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    Fiskaaling.local
Logon Server:              \\AMB-ALING-01
Hotfix(s):                 4 Hotfix(s) Installed.
                           [01]: KB5028948
                           [02]: KB5012170
                           [03]: KB5029263
                           [04]: KB5028756
Network Card(s):           6 NIC(s) Installed.
                           [01]: Intel(R) Wi-Fi 6E AX211 160MHz
                                 Connection Name: Wi-Fi
                                 Status:          Media disconnected
                           [02]: TAP-Windows Adapter V9 for OpenVPN Connect
                                 Connection Name: Local Area Connection
                                 Status:          Media disconnected
                           [03]: Intel(R) Ethernet Connection (16) I219-V
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [04]: Sophos TAP Adapter
                                 Connection Name: Ethernet 2
                                 Status:          Media disconnected
                           [05]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
                           [06]: Realtek USB GbE Family Controller
                                 Connection Name: Ethernet 4
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.43.31
                                 IP address(es)
                                 [01]: 192.168.42.39
                                 [02]: fe80::3b23:462e:b046:5f91
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by olivierfriard** [comment]
Hi,
thank you for reporting this.
Can you send me info about your video? (See Tools >Media file > Media file information)

**Comment by Asajoh** [comment]
Hi, see below :)

MPV information
Video format: h264
Number of media in media list: 21
Current time position: 0.0
Duration: 635.438
FPS: None
Video size: 1920x1080
Aspect ratio: 1.778

ffprobe analysis
File path: C:\Users\asajoh\OneDrive - Fiskaaling\Fiskaaling\Gransking\FHF AkvaNest\Video\Ringur 1\At brúka\04.08.2023 06_01_16 (UTC+01_00).mkv

Duration: 634.377 seconds (00:10:34.377)
Format long name: Matroska / WebM
Creation time: NA
Resolution: 1920x1080
Number of frames: 634377
Bitrate: 3.8 Mb 
FPS: 1000.0
Has video: True
Has audio: False
File size: 298.7 Mb
Video codec: Motion JPEG
Audio codec: None

**Comment by Asajoh** [comment]
There is a possibility that these videos have variable frame rate, but I'm not too familiar with the recording software (xprotect). Windows just says they have 0 fps.

**Comment by Philippe-s-Levi** [comment]
test can be done converting videos from VariableFrameRate to ConstantFrameRate

google "converting video variable frame rate to fixed frame rate"
