### ISSUE TITLE
Issue with MPV player

### ISSUE THREAD

**Issue by RaccoonKoaler** [olivierfriard/BORIS#654]
Hello, I received the bug info listed at the bottom.
I am not sure that it is related but I am having troubles with the video's window. When I start an observation, the video's window opens separately, in wide screen and cannot be incrusted back to BORIS observation window.
I just got the new BORIS Version but sadly it didn't solve the issue.
It seems that MPV player is not collaborating well...

Thanks anyway for the BORIS dev, it's amazing!
PS: Nice new logo <3

BORIS version: 8.21.5
OS: Linux 6.2.0-32-generic #32~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 18 10:40:13 UTC 2
CPU: x86_64 x86_64
Python 3.10.12 (64-bit)
Qt 5.15.3 - PyQt 5.15.6
2023-09-18 12:21

Traceback (most recent call last):
  File "/opt/boris/boris/core.py", line 5029, in closeEvent
    observation_operations.close_observation(self)
  File "/opt/boris/boris/observation_operations.py", line 1124, in close_observation
    dw.player.log_handler = None
  File "/opt/boris/boris/mpv.py", line 1932, in __setattr__
    self._set_property(_py_to_mpv(name), value)
  File "/opt/boris/boris/mpv.py", line 1918, in _set_property
    self.check_core_alive()
  File "/opt/boris/boris/mpv.py", line 1014, in check_core_alive
    raise ShutdownError("libmpv core has been shutdown")
boris.mpv.ShutdownError: libmpv core has been shutdown

System info
DISTRIB_ID=Ubuntu
DISTRIB_RELEASE=22.04
DISTRIB_CODENAME=jammy
DISTRIB_DESCRIPTION="Ubuntu 22.04.3 LTS"
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy
Linux kazewind 6.2.0-32-generic #32~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 18 10:40:13 UTC 2 x86_64 x86_64 x86_64 GNU/Linux

**Comment by zemogoravla** [comment]
Hi,

I see the same issue of the video in a separate window (out of the dockable window) for Ubuntu 22.04 and BORIS 8.21.10

It happens with the default Wayland windowing system.
It doesn't happen if you use the X11 windowing system.

How to switch between Wayland and X:
https://askubuntu.com/questions/1410256/how-do-i-use-x-instead-of-wayland-on-22-04

**Comment by olivierfriard** [comment]
@zemogoravla 
thank you for this very useful information

**Comment by olivierfriard** [comment]
Hi,
it seems that the issue is also present when using libmpv v.2 (on Debian 12 with x11 for example).
The v. 8.27.8 should fix this case:
https://github.com/olivierfriard/BORIS/releases/tag/v8.27.8

Can you test it and let me know?
Thank you for you collaboration
