### ISSUE TITLE
Unable to use the Plot function for observations

### ISSUE THREAD

**Issue by jordan3182** [olivierfriard/BORIS#657]
**Indicate the version of BORIS**
BORIS version: 7.13.9

**Describe the bug**
An error message pops up when I try to use the Plot function under Analysis

**To Reproduce**
1. Open an observation
2. Hover over Analysis and click into Plot
3. Select Observations, Subjects, and Behaviours for the analysis 
4. Execute and see error

**Expected behavior**
A plot graph showing subjects, behaviours, and their duration

**Error message**
Traceback (most recent call last):
File "/Users/jordan/Desktop/BORIS.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/boris/core.py", line 893, in 
self.actionPlot_events2.triggered.connect(lambda: self.plot_events_triggered(mode="list"))
File "/Users/jordan/Desktop/BORIS.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/boris/core.py", line 8473, in plot_events_triggered
plot_events.create_events_plot(
File "/Users/jordan/Desktop/BORIS.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/boris/plot_events.py", line 611, in create_events_plot
plt.tight_layout()
File "/Users/jordan/Desktop/BORIS.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py", line 451, in wrapper
return func(*args, **kwargs)
File "/Users/jordan/Desktop/BORIS.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/matplotlib/pyplot.py", line 1506, in tight_layout
gcf().tight_layout(pad=pad, h_pad=h_pad, w_pad=w_pad, rect=rect)
File "/Users/jordan/Desktop/BORIS.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/matplotlib/cbook/deprecation.py", line 411, in wrapper
return func(*inner_args, **inner_kwargs)
File "/Users/jordan/Desktop/BORIS.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/matplotlib/figure.py", line 2613, in tight_layout
kwargs = get_tight_layout_figure(
File "/Users/jordan/Desktop/BORIS.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/matplotlib/tight_layout.py", line 303, in get_tight_layout_figure
kwargs = auto_adjust_subplotpars(fig, renderer,
File "/Users/jordan/Desktop/BORIS.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/matplotlib/tight_layout.py", line 84, in auto_adjust_subplotpars
bb += [ax.get_tightbbox(renderer, for_layout_only=True)]
File "/Users/jordan/Desktop/BORIS.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/matplotlib/axes/_base.py", line 4162, in get_tightbbox
bb_yaxis = self.yaxis.get_tightbbox(
File "/Users/jordan/Desktop/BORIS.app/Contents/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/matplotlib/axis.py", line 1111, in get_tightbbox
self._update_label_position(renderer)

**Desktop (please complete the following information):**
 OS: Darwin 21.5.0 Darwin Kernel Version 21.5.0: Tue Apr 26 20:57:23 PDT 2022; root:xnu-8020.121.3~2/RELEASE_ARM64_T8110
CPU: x86_64 i386
Python 3.8.1 (64-bit)

**In case of crash** attach or copy the content of the boris.log file (before relaunching BORIS).
(see http://www.boris.unito.it/pages/report_a_bug.html for its location)

**Comment by olivierfriard** [comment]
Hi,
I am sorry but v. 7.13.9 is no longer supported and contains many bugs.
See http://www.boris.unito.it/pages/download_mac to run the last version of BORIS on your Mac
