### ISSUE TITLE
Error when trying to add/edit media

### ISSUE THREAD

**Issue by kcsandoval88** [olivierfriard/BORIS#664]
An error has occured

to improve the software please report this problem at:
https://github.com/olivierfriard/BORIS/issues
Please no screenshot, the error message was copied to the clipboard.

Thank you for your collaboration!

BORIS version: 8.19.1
OS: Windows 10 10.0.22621
CPU: AMD64 Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.9
2023-10-13 09:24

Traceback (most recent call last):
  File "C:\Users\katyc\BORIS19\Lib\site-packages\boris\observation.py", line 140, in 
    menu.triggered.connect(lambda x: self.add_media(mode=x.statusTip()))
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\katyc\BORIS19\Lib\site-packages\boris\observation.py", line 1138, in add_media
    (error, msg) = self.check_media(file_path, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\katyc\BORIS19\Lib\site-packages\boris\observation.py", line 1040, in check_media
    media_info = util.accurate_media_analysis(self.ffmpeg_bin, file_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\katyc\BORIS19\Lib\site-packages\boris\utilities.py", line 1241, in accurate_media_analysis
    ffprobe_results = ffprobe_media_analysis(ffmpeg_bin, file_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\katyc\BORIS19\Lib\site-packages\boris\utilities.py", line 1208, in ffprobe_media_analysis
    "audio_duration": audio_duration,
                      ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'audio_duration' where it is not associated with a value

System info

Host Name:                 SANDOVAL-KC
OS Name:                   Microsoft Windows 11 Home
OS Version:                10.0.22621 N/A Build 22621
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          katycelina@outlook.com
Registered Organization:   N/A
Product ID:                00325-82281-57978-AAOEM
Original Install Date:     2023-06-16, 5:46:52 PM
System Boot Time:          2023-10-12, 11:50:50 AM
System Manufacturer:       LENOVO
System Model:              82BC
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 165 Stepping 2 GenuineIntel ~2304 Mhz
BIOS Version:              LENOVO FDCN27WW, 2020-08-31
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     16,183 MB
Available Physical Memory: 6,199 MB
Virtual Memory: Max Size:  19,895 MB
Virtual Memory: Available: 4,778 MB
Virtual Memory: In Use:    15,117 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\SANDOVAL-KC
Hotfix(s):                 5 Hotfix(s) Installed.
                           [01]: KB5030651
                           [02]: KB5012170
                           [03]: KB5031354
                           [04]: KB5028756
                           [05]: KB5031592
Network Card(s):           3 NIC(s) Installed.
                           [01]: Intel(R) Wi-Fi 6 AX201 160MHz
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.1.1
                                 IP address(es)
                                 [01]: 192.168.1.205
                                 [02]: fe80::23d9:f17c:c35f:d648
                           [02]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
                           [03]: Cisco AnyConnect Secure Mobility Client Virtual Miniport Adapter for Windows x64
                                 Connection Name: Ethernet
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 172.18.217.160
                                 [02]: fe80::b6f7:7886:4f59:5b66
                                 [03]: fe80::8a5d:2afb:c04e:fa1
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

**Comment by olivierfriard** [comment]
Hi,
can you reproduce the issue with the last version 8.21.8 ?

**Comment by kcsandoval88** [comment]
that fixed the issue. I somehow thought I had the latest version. Thank you!
