### ISSUE TITLE
BORIS version: 8.21.8

### ISSUE THREAD

**Issue by ELOTRAVEL** [olivierfriard/BORIS#666]
An error has occured

to improve the software please report this problem at:
https://github.com/olivierfriard/BORIS/issues
Please no screenshot, the error message was copied to the clipboard.

Thank you for your collaboration!

BORIS version: 8.21.8
OS: Windows 10 10.0.22621
CPU: AMD64 Intel64 Family 6 Model 154 Stepping 4, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.9
2023-10-18 15:04

Traceback (most recent call last):
  File "C:\Users\elifak\BORIS\Lib\site-packages\boris\core.py", line 3982, in mpv_timer_out
    self.currentStates = util.get_current_states_modifiers_by_subject(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\elifak\BORIS\Lib\site-packages\boris\utilities.py", line 493, in get_current_states_modifiers_by_subject
    if (x[cfg.EVENT_BEHAVIOR_FIELD_IDX], x[cfg.EVENT_MODIFIER_FIELD_IDX]) not in current_states[x[cfg.EVENT_SUBJECT_FIELD_IDX]]:
                                                                                 ~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'Gesture embodied'


System info

Host Name:                 OZUARCH-EA
OS Name:                   Microsoft Windows 11 Enterprise
OS Version:                10.0.22621 N/A Build 22621
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          User
Registered Organization:   
Product ID:                00329-00000-00003-AA729
Original Install Date:     10.08.2023, 18:56:27
System Boot Time:          29.09.2023, 11:25:24
System Manufacturer:       HP
System Model:              HP EliteBook 640 14 inch G9 Notebook PC
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 154 Stepping 4 GenuineIntel ~1700 Mhz
BIOS Version:              HP U75 Ver. 01.08.00, 26.06.2023
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              tr;Turkish
Time Zone:                 (UTC+03:00) Istanbul
Total Physical Memory:     16.016 MB
Available Physical Memory: 6.925 MB
Virtual Memory: Max Size:  18.448 MB
Virtual Memory: Available: 6.258 MB
Virtual Memory: In Use:    12.190 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\OZUARCH-EA
Hotfix(s):                 3 Hotfix(s) Installed.
                           [01]: KB5029921
                           [02]: KB5030219
                           [03]: KB5028756
Network Card(s):           5 NIC(s) Installed.
                           [01]: Intel(R) Ethernet Connection (16) I219-V
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [02]: Intel(R) Wi-Fi 6E AX211 160MHz
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.1.1
                                 IP address(es)
                                 [01]: 192.168.1.184
                                 [02]: fe80::154:c06e:5bff:e162
                                 [03]: 2a02:4e0:2d06:bb3:3d1c:6f58:f253:fe85
                                 [04]: 2a02:4e0:2d06:bb3:3a07:3c76:e857:9d7a
                           [03]: Fortinet Virtual Ethernet Adapter (NDIS 6.30)
                                 Connection Name: Ethernet 2
                                 Status:          Media disconnected
                           [04]: Fortinet SSL VPN Virtual Ethernet Adapter
                                 Connection Name: Ethernet 3
                                 Status:          Media disconnected
                           [05]: Realtek USB GbE Family Controller
                                 Connection Name: Ethernet 4
                                 Status:          Media disconnected
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by olivierfriard** [comment]
Hi,
thank you for reporting this.
I need your project file and a procedure to reproduce this issue
(please send it by email, see the BORIS web site)
