### ISSUE TITLE
Extract sequences from media files - crashes

### ISSUE THREAD

**Issue by Philippe-s-Levi** [olivierfriard/BORIS#676]
observations / extract sequences from media files
select media file
select subjects and behavior ... I don't remember what I did and I have not been able to reproduce it !!!
OK
1 second

I tried to reproduce ... nothing
I close Boris
I open Boris ... don't  open anymore !!

Please check comment below! :)

BORIS version: 8.21.8
OS: Windows 10 10.0.19045
CPU: AMD64 Intel64 Family 6 Model 165 Stepping 3, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.9
2023-10-27 13:47

Traceback (most recent call last):
  File "C:\Users\WindowsX\BORIS\Lib\site-packages\boris\connections.py", line 148, in <lambda>
    self.actionExtract_events_from_media_files.triggered.connect(lambda: events_snapshots.extract_events(self))
                                                                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WindowsX\BORIS\Lib\site-packages\boris\events_snapshots.py", line 344, in extract_events
    parameters = select_subj_behav.choose_obs_subj_behav_category(
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\WindowsX\BORIS\Lib\site-packages\boris\select_subj_behav.py", line 254, in choose_obs_subj_behav_category
    "time": time_param,
    ^^^^^^
UnboundLocalError: cannot access local variable 'time_param' where it is not associated with a value

System info:

Nome do host:                              PC-PHILIPPE
Nome do sistema operacional:               Microsoft Windows 10 Pro
VersÆo do sistema operacional:             10.0.19045 N/A compila‡Æo 19045
Fabricante do sistema operacional:         Microsoft Corporation
Configura‡Æo do SO:                        Esta‡Æo de trabalho aut“noma
Tipo de compila‡Æo do sistema operacional: Multiprocessor Free
Propriet rio registrado:                   WindowsX
Organiza‡Æo registrada:                    
Identifica‡Æo do produto:                  00331-10000-00001-AA630
Data da instala‡Æo original:               18/06/2022, 16:28:23
Tempo de Inicializa‡Æo do Sistema:         25/10/2023, 16:17:14
Fabricante do sistema:                     ASUS
Modelo do sistema:                         System Product Name
Tipo de sistema:                           x64-based PC
Processador(es):                           1 processador(es) instalado(s).
                                           [01]: Intel64 Family 6 Model 165 Stepping 3 GenuineIntel ~3600 Mhz
VersÆo do BIOS:                            American Megatrends Inc. 1301, 25/11/2021
Pasta do Windows:                          C:\Windows
Pasta do sistema:                          C:\Windows\system32
Inicializar dispositivo:                   \Device\HarddiskVolume1
Localidade do sistema:                     pt-br;Portuguˆs (Brasil)
Localidade de entrada:                     pt-br;Portuguˆs (Brasil)
Fuso hor rio:                              (UTC-03:00) Bras¡lia
Mem¢ria f¡sica total:                      8.005 MB
Mem¢ria f¡sica dispon¡vel:                 1.842 MB
Mem¢ria Virtual: Tamanho M ximo:           11.845 MB
Mem¢ria Virtual: Dispon¡vel:               2.440 MB
Mem¢ria Virtual: Em Uso:                   9.405 MB
Local(is) de arquivo de pagina‡Æo:         C:\pagefile.sys
Dom¡nio:                                   WORKGROUP
Servidor de Logon:                         \\PC-PHILIPPE
Hotfix(es):                                26 hotfix(es) instalado(s).
                                           [01]: KB5030649
                                           [02]: KB5028951
                                           [03]: KB4562830
                                           [04]: KB4570334
                                           [05]: KB4577266
                                           [06]: KB4580325
                                           [07]: KB5003791
                                           [08]: KB5011048
                                           [09]: KB5011067
                                           [10]: KB5012170
                                           [11]: KB5015684
                                           [12]: KB5031356
                                           [13]: KB5014032
                                           [14]: KB5014671
                                           [15]: KB5015895
                                           [16]: KB5016705
                                           [17]: KB5018506
                                           [18]: KB5020372
                                           [19]: KB5022924
                                           [20]: KB5023794
                                           [21]: KB5025315
                                           [22]: KB5026879
                                           [23]: KB5028318
                                           [24]: KB5028380
                                           [25]: KB5029709
                                           [26]: KB5031539
Placa(s) de Rede:                          1 NIC(s) instalado(s).
                                           [01]: Intel(R) Ethernet Connection (14) I219-V
                                                 Nome da conexÆo: Ethernet
                                                 DHCP ativado:    Sim
                                                 Servidor DHCP:   192.168.1.1
                                                 Endere‡o(es) IP
                                                 [01]: 192.168.1.4
                                                 [02]: fe80::3d44:2058:4c6:9d5c
Requisitos do Hyper-V:                     ExtensÆo de Modo de Monitor VM: Sim
                                           Virtualiza‡Æo Habilitada no Firmware: NÆo
                                           ConversÆo de Endere‡os de Segundo N¡vel: Sim
                                           Preven‡Æo de Execu‡Æo de Dados Dispon¡vel: Sim

**Comment by olivierfriard** [comment]
Hi,
Thank you for reporting.
The v. 8.21.10 should fix this issue.
Can you check and let me know?
