### ISSUE TITLE
Transition Matrix After Behaviors Aborting

### ISSUE THREAD

**Issue by CKnau9** [olivierfriard/BORIS#688]
**Indicate the version of BORIS**
 I am using 8.22.6, I updated from 8.20.7 after I first encountered this issue and it is still occurring.

**Describe the bug**
I am trying to create the transition matrix for the: Frequencies of transitions after behaviors and when I select this option it sits doing nothing for a second and then gives the following error report. The regular frequencies of transitions works just fine.

**Expected behavior**
I should get a screen to select which observation I would like to create the matrix for and then get the txt file for the transition matrix for the transitions after behaviors.

**Bug Report**
BORIS version: 8.22.6
OS: Windows 10 10.0.22621
CPU: AMD64 Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.10
2023-12-07 01:48

Traceback (most recent call last):
  File "C:\Users\orego\BORIS\Lib\site-packages\boris\connections.py", line 160, in <lambda>
    self.actionFrequencies_of_transitions_after_behaviors.triggered.connect(lambda: self.transitions_matrix("frequencies_after_behaviors"))
                                                                                    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MainWindow' object has no attribute 'transitions_matrix'

System info:

Host Name:                 LAPTOP-SBUCGLIR
OS Name:                   Microsoft Windows 11 Home
OS Version:                10.0.22621 N/A Build 22621
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          oregon93@comcast.net
Registered Organization:   N/A
Product ID:                00325-81462-86677-AAOEM
Original Install Date:     1/4/2023, 4:58:34 PM
System Boot Time:          12/4/2023, 1:11:40 PM
System Manufacturer:       LENOVO
System Model:              81SX
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 158 Stepping 10 GenuineIntel ~2592 Mhz
BIOS Version:              LENOVO BHCN42WW, 5/21/2021
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume3
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     16,303 MB
Available Physical Memory: 4,824 MB
Virtual Memory: Max Size:  39,855 MB
Virtual Memory: Available: 17,235 MB
Virtual Memory: In Use:    22,620 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\LAPTOP-SBUCGLIR
Hotfix(s):                 4 Hotfix(s) Installed.
                           [01]: KB5032007
                           [02]: KB5012170
                           [03]: KB5032190
                           [04]: KB5032393
Network Card(s):           4 NIC(s) Installed.
                           [01]: Cisco AnyConnect Secure Mobility Client Virtual Miniport Adapter for Windows x64
                                 Connection Name: Ethernet 2
                                 Status:          Hardware not present
                           [02]: TAP-Windows Adapter V9
                                 Connection Name: Local Area Connection
                                 Status:          Media disconnected
                           [03]: Intel(R) Wireless-AC 9560 160MHz
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.0.1
                                 IP address(es)
                                 [01]: 192.168.0.146
                                 [02]: fe80::3862:9bef:33e3:6332
                           [04]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by CKnau9** [comment]
Following up as I would love to use this feature in my data analysis. I had updated to the most recent version and was still getting this same issue. I had to jump back to an older version because I was having an error with plotting my events in the newest version. So this is from version 8.22.20, but it did happen on version 8.24.1 as well.

BORIS version: 8.22.20
OS: Windows 10 10.0.22621
CPU: AMD64 Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.10
MPV library version: 2.1
MPV library file path: C:\Users\orego\BORIS\Lib\site-packages\boris\misc\mpv-2.dll

Error succeded at 2024-03-04 23:28

Traceback (most recent call last):
  File "C:\Users\orego\BORIS\Lib\site-packages\boris\connections.py", line 160, in <lambda>
    self.actionFrequencies_of_transitions_after_behaviors.triggered.connect(lambda: self.transitions_matrix("frequencies_after_behaviors"))
                                                                                    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MainWindow' object has no attribute 'transitions_matrix'


System info
===========


Host Name:                 LAPTOP-SBUCGLIR
OS Name:                   Microsoft Windows 11 Home
OS Version:                10.0.22621 N/A Build 22621
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          oregon93@comcast.net
Registered Organization:   N/A
Product ID:                00325-81462-86677-AAOEM
Original Install Date:     1/4/2023, 4:58:34 PM
System Boot Time:          3/4/2024, 12:19:24 PM
System Manufacturer:       LENOVO
System Model:              81SX
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 158 Stepping 10 GenuineIntel ~2592 Mhz
BIOS Version:              LENOVO BHCN42WW, 5/21/2021
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume3
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     16,303 MB
Available Physical Memory: 4,921 MB
Virtual Memory: Max Size:  33,711 MB
Virtual Memory: Available: 9,600 MB
Virtual Memory: In Use:    24,111 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\LAPTOP-SBUCGLIR
Hotfix(s):                 4 Hotfix(s) Installed.
                           [01]: KB5034467
                           [02]: KB5012170
                           [03]: KB5034765
                           [04]: KB5034225
Network Card(s):           5 NIC(s) Installed.
                           [01]: Cisco AnyConnect Secure Mobility Client Virtual Miniport Adapter for Windows x64
                                 Connection Name: Ethernet 2
                                 Status:          Hardware not present
                           [02]: TAP-Windows Adapter V9
                                 Connection Name: Local Area Connection
                                 Status:          Media disconnected
                           [03]: Intel(R) Wireless-AC 9560 160MHz
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.0.1
                                 IP address(es)
                                 [01]: 192.168.0.146
                                 [02]: fe80::3862:9bef:33e3:6332
                           [04]: Realtek PCIe GbE Family Controller
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [05]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by lihao881230** [comment]
I am encountering the exact same issue...but I would also love to use this feature

**Comment by olivierfriard** [comment]
This is fixed
