### ISSUE TITLE
Set to Current Time Failure

### ISSUE THREAD

**Issue by CKnau9** [olivierfriard/BORIS#690]
**Indicate the version of BORIS**
8.22.6

**Describe the bug**
I am trying to update the current time of a single observation and right click edit selected events and hit the set to current time. The screen pauses and then the bug report pops up.

**Expected behavior**
It should just update the time to where the video is currently at.

BORIS version: 8.22.6
OS: Windows 10 10.0.22621
CPU: AMD64 Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.10
2023-12-11 13:50

Traceback (most recent call last):
  File "C:\Users\orego\BORIS\Lib\site-packages\boris\edit_event.py", line 118, in set_to_current_time
    self.time_widget.set_time(float(self.current_time))
  File "C:\Users\orego\BORIS\Lib\site-packages\boris\duration_widget.py", line 188, in set_time
    if new_time.is_nan():
       ^^^^^^^^^^^^^^^
AttributeError: 'float' object has no attribute 'is_nan'

System info:

Host Name:                 LAPTOP-SBUCGLIR
OS Name:                   Microsoft Windows 11 Home
OS Version:                10.0.22621 N/A Build 22621
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          oregon93@comcast.net
Registered Organization:   N/A
Product ID:                00325-81462-86677-AAOEM
Original Install Date:     1/4/2023, 4:58:34 PM
System Boot Time:          12/4/2023, 1:11:40 PM
System Manufacturer:       LENOVO
System Model:              81SX
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 158 Stepping 10 GenuineIntel ~2592 Mhz
BIOS Version:              LENOVO BHCN42WW, 5/21/2021
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume3
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     16,303 MB
Available Physical Memory: 3,918 MB
Virtual Memory: Max Size:  39,855 MB
Virtual Memory: Available: 14,126 MB
Virtual Memory: In Use:    25,729 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\LAPTOP-SBUCGLIR
Hotfix(s):                 4 Hotfix(s) Installed.
                           [01]: KB5032007
                           [02]: KB5012170
                           [03]: KB5032190
                           [04]: KB5032393
Network Card(s):           4 NIC(s) Installed.
                           [01]: Cisco AnyConnect Secure Mobility Client Virtual Miniport Adapter for Windows x64
                                 Connection Name: Ethernet 2
                                 Status:          Hardware not present
                           [02]: TAP-Windows Adapter V9
                                 Connection Name: Local Area Connection
                                 Status:          Media disconnected
                           [03]: Intel(R) Wireless-AC 9560 160MHz
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.0.1
                                 IP address(es)
                                 [01]: 192.168.0.146
                                 [02]: fe80::3862:9bef:33e3:6332
                           [04]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by CKnau9** [comment]
Also anytime I edit and save an observation it jumps back to the top of the observation list and I have to scroll back down hundreds of lines to get back to what I edited.

**Comment by CKnau9** [comment]
> Also anytime I edit and save an observation it jumps back to the top of the observation list and I have to scroll back down hundreds of lines to get back to what I edited.

This is still an issue anytime I edit an observation, I am using version 8.22.20, but this was also an issue in 8.24.1.

**Comment by olivierfriard** [comment]
Hi,
can you check the last version please?
