### ISSUE TITLE
Error when starting observation 

### ISSUE THREAD

**Issue by jocelyn816** [olivierfriard/BORIS#704]
The following error occurs when I start an observation after opening the project. If I ignore the error, I can code behaviors but it will pop up periodically. I tried to set the preferences with the video replay from auto to no but that did not work. 

Thanks!

An error has occured

to improve the software please report this problem at:
https://github.com/olivierfriard/BORIS/issues
Please no screenshot, the error message was copied to the clipboard.

Thank you for your collaboration!

BORIS version: 8.22.14
OS: Windows 10 10.0.22000
CPU: AMD64 Intel64 Family 6 Model 94 Stepping 3, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.10
2024-01-22 13:31

Traceback (most recent call last):
  File "C:\Users\lpfeiffer\BORIS\Lib\site-packages\boris\connections.py", line 88, in 
    self.actionOpen_observation.triggered.connect(lambda: observation_operations.open_observation(self, mode=cfg.OBS_START))
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lpfeiffer\BORIS\Lib\site-packages\boris\observation_operations.py", line 176, in open_observation
    return load_observation(self, selected_observations[0], mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lpfeiffer\BORIS\Lib\site-packages\boris\observation_operations.py", line 223, in load_observation
    if not initialize_new_media_observation(self):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\lpfeiffer\BORIS\Lib\site-packages\boris\observation_operations.py", line 1613, in initialize_new_media_observation
    self.seek_mediaplayer(int(self.pj[cfg.OBSERVATIONS][self.observationId][cfg.OBSERVATION_TIME_INTERVAL][0]), player=i)
  File "C:\Users\lpfeiffer\BORIS\Lib\site-packages\boris\core.py", line 1455, in seek_mediaplayer
    self.dw_player[player].player.seek(
  File "C:\Users\lpfeiffer\BORIS\Lib\site-packages\boris\mpv2.py", line 1235, in seek
    self.command('seek', amount, reference, precision)
  File "C:\Users\lpfeiffer\BORIS\Lib\site-packages\boris\mpv2.py", line 1228, in command
    _mpv_command_node(self.handle, ppointer, out)
  File "C:\Users\lpfeiffer\BORIS\Lib\site-packages\boris\mpv2.py", line 148, in raise_for_ec
    raise ex
SystemError: ('Error running mpv command', -12, (, , ))

System info

Host Name:                 MADALINA-MINC-B
OS Name:                   Microsoft Windows 11 Education
OS Version:                10.0.22000 N/A Build 22000
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          xComputer Guys
Registered Organization:   
Product ID:                00328-20090-00000-AA430
Original Install Date:     8/29/2022, 8:32:02 AM
System Boot Time:          1/22/2024, 11:00:17 AM
System Manufacturer:       Dell Inc.
System Model:              OptiPlex 7050
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 94 Stepping 3 GenuineIntel ~2496 Mhz
BIOS Version:              Dell Inc. 1.27.0, 9/18/2023
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume2
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-06:00) Central Time (US & Canada)
Total Physical Memory:     32,472 MB
Available Physical Memory: 26,381 MB
Virtual Memory: Max Size:  37,336 MB
Virtual Memory: Available: 31,241 MB
Virtual Memory: In Use:    6,095 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\MADALINA-MINC-B
Hotfix(s):                 7 Hotfix(s) Installed.
                           [01]: KB5033919
                           [02]: KB5028856
                           [03]: KB5007575
                           [04]: KB5011048
                           [05]: KB5012170
                           [06]: KB5034121
                           [07]: KB5034287
Network Card(s):           3 NIC(s) Installed.
                           [01]: Intel(R) Ethernet Connection (5) I219-LM
                                 Connection Name: Ethernet 6
                                 Status:          Media disconnected
                           [02]: Intel(R) Dual Band Wireless-AC 8265
                                 Connection Name: Wi-Fi 4
                                 DHCP Enabled:    Yes
                                 DHCP Server:     10.142.1.7
                                 IP address(es)
                                 [01]: 10.140.145.35
                                 [02]: fe80::a4d6:748b:5946:7fe4
                           [03]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection 2
                                 Status:          Media disconnected
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by jocelyn816** [comment]
As a follow up, I have gotten this error on multiple different computers when trying to start a new observation.
