### ISSUE TITLE
Cannot start observations 

### ISSUE THREAD

**Issue by MonicaMoeller** [olivierfriard/BORIS#713]
I can make a project, but whenever I try to start new observations or start old ones this error message pops up:

BORIS version: 8.22.16
OS: Windows 10 10.0.22631
CPU: AMD64 AMD64 Family 23 Model 96 Stepping 1, AuthenticAMD
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.10
2024-02-06 16:01

Traceback (most recent call last):
  File "C:\Users\Monica\BORIS\Lib\site-packages\boris\connections.py", line 91, in 
    self.actionObservationsList.triggered.connect(lambda: observation_operations.observations_list(self))
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Monica\BORIS\Lib\site-packages\boris\observation_operations.py", line 129, in observations_list
    load_observation(self, selected_obs[0], cfg.OBS_START)
  File "C:\Users\Monica\BORIS\Lib\site-packages\boris\observation_operations.py", line 215, in load_observation
    initialize_new_live_observation(self)
  File "C:\Users\Monica\BORIS\Lib\site-packages\boris\observation_operations.py", line 2137, in initialize_new_live_observation
    current_time = util.seconds_of_day(dt.datetime.now())
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Monica\BORIS\Lib\site-packages\boris\utilities.py", line 762, in seconds_of_day
    return dec((timestamp - dt.datetime.combine(dt.date(), dt.time(0))).total_seconds()).quantize(dec("0.001"))
                                                ^^^^^^^^^
TypeError: function missing required argument 'year' (pos 1)

System info

Host Name:                 LAPTOP-RT8MU196
OS Name:                   Microsoft Windows 11 Home
OS Version:                10.0.22631 N/A Build 22631
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Monica
Registered Organization:   N/A
Product ID:                00325-81941-34926-AAOEM
Original Install Date:     16-12-2022, 12:26:28
System Boot Time:          06-02-2024, 14:18:38
System Manufacturer:       ASUSTeK COMPUTER INC.
System Model:              VivoBook_ASUSLaptop X421IA_M433IA
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: AMD64 Family 23 Model 96 Stepping 1 AuthenticAMD ~1400 Mhz
BIOS Version:              American Megatrends Inc. X421IA.305, 27-07-2020
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             da;Dansk
Input Locale:              da;Dansk
Time Zone:                 (UTC+01:00) K›benhavn, Stockholm, Oslo, Madrid, Paris
Total Physical Memory:     7.600 MB
Available Physical Memory: 2.042 MB
Virtual Memory: Max Size:  12.208 MB
Virtual Memory: Available: 5.458 MB
Virtual Memory: In Use:    6.750 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\LAPTOP-RT8MU196
Hotfix(s):                 5 Hotfix(s) Installed.
                           [01]: KB5033920
                           [02]: KB5012170
                           [03]: KB5027397
                           [04]: KB5034123
                           [05]: KB5032393
Network Card(s):           4 NIC(s) Installed.
                           [01]: TAP-Windows Adapter V9
                                 Connection Name: McAfee VPN
                                 Status:          Media disconnected
                           [02]: Intel(R) Wi-Fi 6 AX200 160MHz
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.145.108
                                 IP address(es)
                                 [01]: 192.168.145.166
                                 [02]: fe80::649c:590c:90df:a1ba
                           [03]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth-netv‘rksforbindelse
                                 Status:          Media disconnected
                           [04]: Wintun Userspace Tunnel
                                 Connection Name: McAfee_VPN
                                 Status:          Media disconnected
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

**Comment by olivierfriard** [comment]
Hi,
this issue should be fixed in last version (8.24).
Can you confirm?

**Comment by MonicaMoeller** [comment]
Hi,

Due to the issues I removed the program from my computer and downloaded 
the portable version, which is working. I unfortunately cannot say if 
the bug is fixed in the other version due to that.

Best,

Monica

Olivier Friard skrev den 06.02.2024 16:24:

> Hi,
> this issue should be fixed in last version (8.24).
> Can you confirm?
> 
> --
> Reply to this email directly, view it on GitHub [1], or unsubscribe 
> [2].
> You are receiving this because you authored the thread.Message ID: 
> ***@***.***>


Links:
------
[1] 
https://github.com/olivierfriard/BORIS/issues/713#issuecomment-1930041804
[2]
