### ISSUE TITLE
Unable to add a comment or edit modifiers

### ISSUE THREAD

**Issue by Th225sa** [olivierfriard/BORIS#717]
BORIS version: 8.22.14
OS: Windows 10 10.0.19045
CPU: AMD64 Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.10
2024-02-09 12:20

Traceback (most recent call last):
  File "C:\Users\th225\BORIS\Lib\site-packages\boris\connections.py", line 120, in 
    self.actionEdit_selected_events.triggered.connect(lambda: event_operations.edit_selected_events(self))
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\th225\BORIS\Lib\site-packages\boris\event_operations.py", line 458, in edit_selected_events
    edit_event(self)
  File "C:\Users\th225\BORIS\Lib\site-packages\boris\event_operations.py", line 673, in edit_event
    new_time = edit_window.time_widget.get_time()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\th225\BORIS\Lib\site-packages\boris\dialog.py", line 377, in get_time
    return dec(time_sec)
               ^^^^^^^^
UnboundLocalError: cannot access local variable 'time_sec' where it is not associated with a value

System info

Host Name:                 PC19826
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19045 N/A Build 19045
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          IT Services
Registered Organization:   University of St Andrews
Product ID:                00329-00000-00003-AA864
Original Install Date:     11/05/2022, 12:20:21
System Boot Time:          31/01/2024, 12:11:25
System Manufacturer:       HP
System Model:              HP EliteBook 840 G7 Notebook PC
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 142 Stepping 12 GenuineIntel ~1803 Mhz
BIOS Version:              HP S70 Ver. 01.01.07, 24/08/2020
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-gb;English (United Kingdom)
Input Locale:              en-gb;English (United Kingdom)
Time Zone:                 (UTC-10:00) Hawaii
Total Physical Memory:     16,153 MB
Available Physical Memory: 8,721 MB
Virtual Memory: Max Size:  18,585 MB
Virtual Memory: Available: 9,297 MB
Virtual Memory: In Use:    9,288 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    st-andrews.ac.uk
Logon Server:              \\SYS-AD-DC04
Hotfix(s):                 21 Hotfix(s) Installed.
                           [01]: KB5033918
                           [02]: KB5030841
                           [03]: KB4562830
                           [04]: KB4577266
                           [05]: KB4580325
                           [06]: KB5007401
                           [07]: KB5011048
                           [08]: KB5012170
                           [09]: KB5015684
                           [10]: KB5034122
                           [11]: KB5014032
                           [12]: KB5014035
                           [13]: KB5014671
                           [14]: KB5020372
                           [15]: KB5026879
                           [16]: KB5028318
                           [17]: KB5028380
                           [18]: KB5031539
                           [19]: KB5032392
                           [20]: KB5032907
                           [21]: KB5005260
Network Card(s):           3 NIC(s) Installed.
                           [01]: Cisco AnyConnect Secure Mobility Client Virtual Miniport Adapter for Windows x64
                                 Connection Name: Ethernet 2
                                 Status:          Hardware not present
                           [02]: Intel(R) Wi-Fi 6 AX201 160MHz
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.1.1
                                 IP address(es)
                                 [01]: 192.168.1.22
                                 [02]: fe80::8f1f:f72e:eb9d:bef0
                                 [03]: fd15:3ad3:b83a:10:81dd:eddc:2b:2b83
                                 [04]: 2605:59c8:31c4:1b10:f99a:9e28:4f72:47f1
                                 [05]: fd15:3ad3:b83a:10:f2a8:3c43:811f:a563
                                 [06]: fd15:3ad3:b83a:10::fa7
                                 [07]: 2605:59c8:31c4:1b10:3856:5269:1940:995c
                                 [08]: 2605:59c8:31c4:1b10::fa7
                           [03]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.**Indicate the version of BORIS**
 Verify you are using the last version (http://www.boris.unito.it/pages/download.html)

**Describe the bug**
Every time I try to edit an observation, either to add a comment or edit subject or behavior (no option available to edit modifiers) it brings up the above error message. any help would be great. Thanks

**Comment by olivierfriard** [comment]
Hi,
can you repeat this issue with the current version (8.24)?
