### ISSUE TITLE
Issue with geometric measurements

### ISSUE THREAD

**Issue by sofiapanzetta** [olivierfriard/BORIS#721]
Using BORIS version 8.24. I attempted to get the latest version and try this again but the same error pops up.

I'm trying to use the Polyline tool under Geometric Measurements but an error message pops up every time I try to use it. I attempted to do the same with the other tools in Geometric Measurements but none of them wanted to work (the same error message shows up).

1. Go to 'Geometric Measurements'
2. Click on 'Polyline' or any tool in it
3. Try to calculate distance
4. See error message

The following message pops up:

An error has occured!

to improve the software please report this problem at:
https://github.com/olivierfriard/BORIS/issues

Please no screenshot, the error message was copied to the clipboard.

Thank you for your collaboration!

BORIS version: 8.24
OS: Windows 10 10.0.19045
CPU: AMD64 Intel64 Family 6 Model 85 Stepping 4, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.10
MPV library version: 2.1
MPV library file path: C:\Users\SPanzetta\BORIS\Lib\site-packages\boris\misc\mpv-2.dll

Error succeded at 2024-02-12 10:08

Traceback (most recent call last):
  File "C:\Users\SPanzetta\BORIS\Lib\site-packages\boris\core.py", line 1713, in frame_image_clicked
    geometric_measurement.image_clicked(self, n_player, event)
  File "C:\Users\SPanzetta\BORIS\Lib\site-packages\boris\geometric_measurement.py", line 553, in image_clicked
    media_file_name = str(pl.Path(fn).relative_to(pl.Path(self.projectFileName).parent))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\SPanzetta\BORIS\Lib\pathlib.py", line 730, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"
ValueError: 'E:\\EGC001_C1_Videos\\EGC001_C1_001.LRV' is not in the subpath of '' OR one path is relative and the other is absolute.

System info
===========

Host Name:                 DESKTOP-2S4SJ8F
OS Name:                   Microsoft Windows 10 Education
OS Version:                10.0.19045 N/A Build 19045
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          BioSciIT
Registered Organization:   University of Alberta
Product ID:                00328-10000-00001-AA126
Original Install Date:     2022-07-27, 5:45:04 PM
System Boot Time:          2024-01-24, 12:10:18 PM
System Manufacturer:       Dell Inc.
System Model:              Precision 7920 Tower
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 85 Stepping 4 GenuineIntel ~2195 Mhz
BIOS Version:              Dell Inc. 2.6.3, 2020-05-04
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume2
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-07:00) Mountain Time (US & Canada)
Total Physical Memory:     129,694 MB
Available Physical Memory: 114,070 MB
Virtual Memory: Max Size:  148,126 MB
Virtual Memory: Available: 129,046 MB
Virtual Memory: In Use:    19,080 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\DESKTOP-2S4SJ8F
Hotfix(s):                 9 Hotfix(s) Installed.
                           [01]: KB5028951
                           [02]: KB5003791
                           [03]: KB5007401
                           [04]: KB5015684
                           [05]: KB5029244
                           [06]: KB5014671
                           [07]: KB5016705
                           [08]: KB5028318
                           [09]: KB5028380
Network Card(s):           3 NIC(s) Installed.
                           [01]: Cisco AnyConnect Secure Mobility Client Virtual Miniport Adapter for Windows x64
                                 Connection Name: Ethernet 2
                                 Status:          Hardware not present
                           [02]: Intel(R) Ethernet Connection (3) I219-LM
                                 Connection Name: Ethernet
                                 DHCP Enabled:    Yes
                                 DHCP Server:     129.128.3.250
                                 IP address(es)
                                 [01]: 129.128.82.62
                                 [02]: fe80::e0da:35bd:eee:dfc2
                           [03]: Intel(R) I210 Gigabit Network Connection
                                 Connection Name: Ethernet 3
                                 Status:          Media disconnected
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by olivierfriard** [comment]
Hi,
thank you for reporting this.
Can you give me the minimal detailed procedure to reproduce this issue?
Did you add media with relative path?

**Comment by sofiapanzetta** [comment]
Sorry for the late reply! It started to work but now has crashed and is no
longer working again. To reproduce the issue, we first started a new
project and added a new observation with an absolute path for the media
file. We then clicked geometric measurements and then polyline. As soon as
we clicked once with polyline, the error message popped up and no
measurements could be taken.

**Comment by olivierfriard** [comment]
I need your project file to reproduce this issue.
Is it possible?
You can send it by email (see www.boris.unito.it > About)

**Comment by sofiapanzetta** [comment]
I sent the file via email last week. Did you receive it/were you able to
open it?

**Comment by olivierfriard** [comment]
Hi,
I got your email (it was in the spam).
I will try to reproduce the issue.
Sorry for the delay.

**Comment by lysyyds06** [comment]
Has this issue been resolved? I’m encountering the same problem and can’t use geometric measurement.

**Comment by leonalea** [comment]
Similarly requesting a follow up - am also having what seems to be the exact same issue. When attempting to use Polyline on a fresh file, I select the radio button and then right or left click on the video, which immediately causes an error, making using that feature impossible.

**Comment by bergmanryan15-dot** [comment]
Also requesting a follow-up for this issue. I am attempting to measure distance, and after opening the geometric measurement menu and going to click a point (Polyline), I receive the following error message. I am also having difficulty setting a scale, as there is no distance tool that becomes available to measure the distance in pixels of my known distance. Maybe this is tied to the same issue as I am unable to add initial points for distance measurements. I am using an absolute path, and encountered a similar error message when trying to use a relative path.


System info
===========

BORIS version: 9.5
OS: Windows 11 10.0.22631
CPU: AMD64 Intel64 Family 6 Model 165 Stepping 2, GenuineIntel
Python 3.12.4 (64-bit)
Qt 6.9.0 - PySide 6.9.0
MPV library version: 2.3
MPV API version: (2, 3)
MPV library file path: C:\Users\rbergman\BORIS\Lib\site-packages\boris\misc\libmpv-2.dll

Memory (RAM)  Total: 65246.69 Mb  Free: 50654.67 Mb

Error succeded at 2025-09-22 10:29

Traceback (most recent call last):
  File "C:\Users\rbergman\BORIS\Lib\site-packages\boris\core.py", line 1734, in frame_image_clicked
    geometric_measurement.image_clicked(self, n_player, event)
  File "C:\Users\rbergman\BORIS\Lib\site-packages\boris\geometric_measurement.py", line 570, in image_clicked
    media_file_name = str(pl.Path(fn).relative_to(pl.Path(self.projectFileName).parent))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\rbergman\BORIS\Lib\pathlib.py", line 682, in relative_to
    raise ValueError(f"{str(self)!r} is not in the subpath of {str(other)!r}")
ValueError: 'E:\\Summer 2025 Videos\\20250716_PgH_101\\20250716_PgH_101_GP019793.MP4' is not in the subpath of 'C:\\Users\\rbergman\\BORIS\\Projects'
