### ISSUE TITLE
It stops working when I include coding map modifiers.

### ISSUE THREAD

**Issue by MarisolParadaS** [olivierfriard/BORIS#724]
**Indicate the version of BORIS** -> **v.8.24.1**
 Verify you are using the last version (http://www.boris.unito.it/pages/download.html)

**Describe the bug**
I created a coding map to analyze behaviors during the open field and novel object tests. The coding map has three floor regions (lateral, middle, and central). When I start a new observation and code some behavior (which has coding map) the coding map opens, I click in the region, then I click in done, and then the error pops up.

**To Reproduce**

**Expected behavior**
The expected action is that the behavior will be added to the events window, and I can continue coding the video.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [windows 11 Pro ]
 - Type of BORIS instalaltion (setup)

**In case of crash** attach or copy the content of the boris.log file (before relaunching BORIS).
(see http://www.boris.unito.it/pages/report_a_bug.html for its location)

BORIS version: 8.24.1
OS: Windows 10 10.0.22000
CPU: AMD64 Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.10
MPV library version: 2.1
MPV library file path: C:\Users\mpsar\BORIS\Lib\site-packages\boris\misc\mpv-2.dll

Error succeded at 2024-02-21 09:56

Traceback (most recent call last):
  File "C:\Users\mpsar\BORIS\Lib\site-packages\boris\core.py", line 4989, in keyPressEvent
    event = self.full_event(behavior_idx)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mpsar\BORIS\Lib\site-packages\boris\core.py", line 4644, in full_event
    if flag_player_playing:
       ^^^^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'flag_player_playing' where it is not associated with a value

System info
===========

Host Name:                 NBC-LAP-MPSAR
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22000 N/A Build 22000
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          vetadmin
Registered Organization:   
Product ID:                00355-62924-00915-AAOEM
Original Install Date:     7/6/2022, 11:06:27 AM
System Boot Time:          2/21/2024, 7:35:02 AM
System Manufacturer:       Dell Inc.
System Model:              Latitude 3520
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 140 Stepping 1 GenuineIntel ~1382 Mhz
BIOS Version:              Dell Inc. 1.20.0, 7/12/2022
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     16,123 MB
Available Physical Memory: 5,967 MB
Virtual Memory: Max Size:  18,555 MB
Virtual Memory: Available: 4,278 MB
Virtual Memory: In Use:    14,277 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    vet.upenn.edu
Logon Server:              \\DC67
Hotfix(s):                 7 Hotfix(s) Installed.
                           [01]: KB5030650
                           [02]: KB5030842
                           [03]: KB5010690
                           [04]: KB5011048
                           [05]: KB5012170
                           [06]: KB5031358
                           [07]: KB5031591
Network Card(s):           3 NIC(s) Installed.
                           [01]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
                           [02]: Realtek 8822CE Wireless LAN 802.11ac PCI-E NIC
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.1.1
                                 IP address(es)
                                 [01]: 192.168.1.113
                                 [02]: fe80::30d9:a56e:ddfc:55fa
                           [03]: Realtek PCIe GbE Family Controller
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by olivierfriard** [comment]
Hi,
can you reproduce this issue with the last version ?
Thank you for your collaboration

**Comment by olivierfriard** [comment]
Hi,
thank you for reporting this.
The issue should be fixed in the pre-release 9.8.6rc2.
You can test it before the release following the procedure described in https://www.boris.unito.it/run_source_code
