### ISSUE TITLE
Error when I open an observation for review.

### ISSUE THREAD

**Issue by DigDigDig** [olivierfriard/BORIS#725]
**Indicate the version of BORIS**
I am using the most recent version of BORIS.

**Describe the bug**
BORIS sends me an error when I open an observation

**To Reproduce**
1. Open a BORIS project.
2. Start an Observation

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Type of BORIS installation: Portable

An error has occured!

to improve the software please report this problem at:
https://github.com/olivierfriard/BORIS/issues

Please no screenshot, the error message was copied to the clipboard.

Thank you for your collaboration!

BORIS version: 8.24.1
OS: Windows 10 10.0.22631
CPU: AMD64 AMD64 Family 25 Model 8 Stepping 2, AuthenticAMD
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.10
MPV library version: 2.1
MPV library file path: D:\BORIS_Portable\Lib\site-packages\boris\misc\mpv-2.dll

Error succeded at 2024-02-23 16:36

Traceback (most recent call last):
  File "D:\BORIS_Portable\Lib\site-packages\boris\connections.py", line 229, in <lambda>
    self.action_obs_list.triggered.connect(lambda: observation_operations.observations_list(self))
                                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\BORIS_Portable\Lib\site-packages\boris\observation_operations.py", line 128, in observations_list
    load_observation(self, selected_obs[0], cfg.OBS_START)
  File "D:\BORIS_Portable\Lib\site-packages\boris\observation_operations.py", line 222, in load_observation
    if not initialize_new_media_observation(self):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\BORIS_Portable\Lib\site-packages\boris\observation_operations.py", line 1848, in initialize_new_media_observation
    self.seek_mediaplayer(int(self.pj[cfg.OBSERVATIONS][self.observationId][cfg.OBSERVATION_TIME_INTERVAL][0]), player=i)
  File "D:\BORIS_Portable\Lib\site-packages\boris\core.py", line 1424, in seek_mediaplayer
    self.dw_player[player].player.seek(
  File "D:\BORIS_Portable\Lib\site-packages\boris\mpv2.py", line 1235, in seek
    self.command('seek', amount, reference, precision)
  File "D:\BORIS_Portable\Lib\site-packages\boris\mpv2.py", line 1228, in command
    _mpv_command_node(self.handle, ppointer, out)
  File "D:\BORIS_Portable\Lib\site-packages\boris\mpv2.py", line 148, in raise_for_ec
    raise ex
SystemError: ('Error running mpv command', -12, (<MpvHandle object at 0x000002596E9CD6D0>, <boris.mpv2.LP_MpvNode object at 0x00000259794B9FD0>, <boris.mpv2.LP_MpvNode object at 0x00000259794BA2D0>))

System info
===========

Host Name:                 IE-D-STEVE2024
OS Name:                   Microsoft Windows 11 Business
OS Version:                10.0.22631 N/A Build 22631
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          N/A
Registered Organization:   N/A
Product ID:                00355-61348-28641-AAOEM
Original Install Date:     1/18/2024, 2:16:30 PM
System Boot Time:          2/22/2024, 5:55:14 PM
System Manufacturer:       Dell Inc.
System Model:              Precision 7865 Tower
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: AMD64 Family 25 Model 8 Stepping 2 AuthenticAMD ~4001 Mhz
BIOS Version:              Dell Inc. 1.6.1, 1/5/2024
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     65,421 MB
Available Physical Memory: 43,791 MB
Virtual Memory: Max Size:  69,517 MB
Virtual Memory: Available: 37,130 MB
Virtual Memory: In Use:    32,387 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\IE-D-STEVE2024
Hotfix(s):                 6 Hotfix(s) Installed.
                           [01]: KB5034467
                           [02]: KB5027397
                           [03]: KB5033055
                           [04]: KB5033204
                           [05]: KB5034765
                           [06]: KB5034225
Network Card(s):           4 NIC(s) Installed.
                           [01]: Realtek PCIe GbE Family Controller
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [02]: Marvell AQtion 10Gbit Network Adapter
                                 Connection Name: Ethernet 2
                                 DHCP Enabled:    Yes
                                 DHCP Server:     10.0.0.1
                                 IP address(es)
                                 [01]: 10.0.0.152
                                 [02]: fe80::84c5:8148:581c:1f0a
                                 [03]: 2601:403:c101:1dd0:c163:ae71:1ffd:226a
                                 [04]: 2601:403:c101:1dd0:59d2:c88d:31eb:76b7
                                 [05]: 2601:403:c101:1dd0::2210
                           [03]: TAP-Windows Adapter V9
                                 Connection Name: Local Area Connection
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.117.254
                                 IP address(es)
                                 [01]: 192.168.117.4
                                 [02]: fe80::1939:5663:6c0b:c3a2
                           [04]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by DigDigDig** [comment]
My coworker received the same error this morning when opening observations on a different file.    This was a fresh project file that he had just set up.

-----------------

**Indicate the version of BORIS**
I am using the most recent version of BORIS.

**Describe the bug**
BORIS sends me an error when I open an observation

**To Reproduce**
Steps to reproduce the behavior:

    Create a new BORIS project.
    Set up an ethogram and load .MOV videos from NAS into observations.
    Start an Observation.
    Error.

Expected behavior
A clear and concise description of what you expected to happen.

Desktop (please complete the following information):

    OS: Windows 11
    Type of BORIS installation: Portable

-----------------

An error has occurred.

to improve the software please report this problem at:
https://github.com/olivierfriard/BORIS/issues
Please no screenshot, the error message was copied to the clipboard.

Thank you for your collaboration!


BORIS version: 8.21.8
OS: Windows 10 10.0.22631
CPU: AMD64 Intel64 Family 6 Model 183 Stepping 1, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.9
2024-03-11 09:45

Traceback (most recent call last):
  File "C:\Users\JackReynolds\BORIS\Lib\site-packages\boris\connections.py", line 88, in 
    self.actionOpen_observation.triggered.connect(lambda: observation_operations.open_observation(self, mode=cfg.OBS_START))
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JackReynolds\BORIS\Lib\site-packages\boris\observation_operations.py", line 174, in open_observation
    return load_observation(self, selected_observations[0], mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JackReynolds\BORIS\Lib\site-packages\boris\observation_operations.py", line 221, in load_observation
    if not initialize_new_media_observation(self):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\JackReynolds\BORIS\Lib\site-packages\boris\observation_operations.py", line 1580, in initialize_new_media_observation
    self.seek_mediaplayer(int(self.pj[cfg.OBSERVATIONS][self.observationId][cfg.OBSERVATION_TIME_INTERVAL][0]), player=i)
  File "C:\Users\JackReynolds\BORIS\Lib\site-packages\boris\core.py", line 1406, in seek_mediaplayer
    self.dw_player[player].player.seek(
  File "C:\Users\JackReynolds\BORIS\Lib\site-packages\boris\mpv2.py", line 1235, in seek
    self.command('seek', amount, reference, precision)
  File "C:\Users\JackReynolds\BORIS\Lib\site-packages\boris\mpv2.py", line 1228, in command
    _mpv_command_node(self.handle, ppointer, out)
  File "C:\Users\JackReynolds\BORIS\Lib\site-packages\boris\mpv2.py", line 148, in raise_for_ec
    raise ex
SystemError: ('Error running mpv command', -12, (, , ))


System info

Host Name:                 IE-D-JREYNOLDS
OS Name:                   Microsoft Windows 11 Business
OS Version:                10.0.22631 N/A Build 22631
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          N/A
Registered Organization:   N/A
Product ID:                00330-80000-00000-AA750
Original Install Date:     2/16/2024, 4:23:10 AM
System Boot Time:          3/8/2024, 10:45:16 AM
System Manufacturer:       Dell Inc.
System Model:              Precision 3660
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 183 Stepping 1 GenuineIntel ~2100 Mhz
BIOS Version:              Dell Inc. 2.4.0, 4/12/2023
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     32,457 MB
Available Physical Memory: 663 MB
Virtual Memory: Max Size:  61,416 MB
Virtual Memory: Available: 7,229 MB
Virtual Memory: In Use:    54,187 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\IE-D-JREYNOLDS
Hotfix(s):                 5 Hotfix(s) Installed.
                           [01]: KB5034467
                           [02]: KB5027397
                           [03]: KB5029517
                           [04]: KB5034765
                           [05]: KB5034225
Network Card(s):           1 NIC(s) Installed.
                           [01]: Intel(R) Ethernet Connection (17) I219-LM
                                 Connection Name: Ethernet
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.17.1
                                 IP address(es)
                                 [01]: 192.168.17.113
                                 [02]: fe80::84e8:63a8:30fa:def9
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.
