### ISSUE TITLE
Error while exporting events as aggregated events

### ISSUE THREAD

**Issue by cjyun103** [olivierfriard/BORIS#732]
**8.24.1 & 8.21.8**
 
**Describe the bug**
Please see the crash report below:

An error has occured!

to improve the software please report this problem at:
https://github.com/olivierfriard/BORIS/issues

Please no screenshot, the error message was copied to the clipboard.

Thank you for your collaboration!

BORIS version: 8.24.1
OS: Windows 10 10.0.22631
CPU: AMD64 Intel64 Family 6 Model 141 Stepping 1, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.10
MPV library version: 2.1
MPV library file path: D:\Downloads\BORIS 8.24.1\Lib\site-packages\boris\misc\mpv-2.dll

Error succeded at 2024-03-24 21:42

Traceback (most recent call last):
  File "D:\Downloads\BORIS 8.24.1\Lib\site-packages\boris\export_events.py", line 478, in export_aggregated_events
    data_single_obs_sorted = tablib.Dataset(
                             ^^^^^^^^^^^^^^^
  File "D:\Downloads\BORIS 8.24.1\Lib\site-packages\tablib\core.py", line 158, in __init__
    self.headers = kwargs.get('headers')
    ^^^^^^^^^^^^
  File "D:\Downloads\BORIS 8.24.1\Lib\site-packages\tablib\core.py", line 301, in _set_headers
    self._validate(collection)
  File "D:\Downloads\BORIS 8.24.1\Lib\site-packages\tablib\core.py", line 254, in _validate
    raise InvalidDimensions
tablib.exceptions.InvalidDimensions

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Downloads\BORIS 8.24.1\Lib\site-packages\boris\connections.py", line 149, in <lambda>
    self.actionExport_aggregated_events.triggered.connect(lambda: export_events.export_aggregated_events(self))
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Downloads\BORIS 8.24.1\Lib\site-packages\boris\export_events.py", line 493, in export_aggregated_events
    data_single_obs_sorted = tablib.Dataset(
                             ^^^^^^^^^^^^^^^
  File "D:\Downloads\BORIS 8.24.1\Lib\site-packages\tablib\core.py", line 158, in __init__
    self.headers = kwargs.get('headers')
    ^^^^^^^^^^^^
  File "D:\Downloads\BORIS 8.24.1\Lib\site-packages\tablib\core.py", line 301, in _set_headers
    self._validate(collection)
  File "D:\Downloads\BORIS 8.24.1\Lib\site-packages\tablib\core.py", line 254, in _validate
    raise InvalidDimensions
tablib.exceptions.InvalidDimensions

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Tried both portable and setup 

**Solution**
Revert back to Boris 8.0 and the export worked without issues.

**Comment by olivierfriard** [comment]
Hi,
is it possible to access you BORIS project file to reproduce this issue?
You can send it by email 
Thank you for your collaboration
