### ISSUE TITLE
Picture observation bug

### ISSUE THREAD

**Issue by kamikroft** [olivierfriard/BORIS#736]
BORIS version: 8.22.6
OS: Windows 10 10.0.19045
CPU: AMD64 Intel64 Family 6 Model 78 Stepping 3, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.10
2024-04-04 22:33

Traceback (most recent call last):
  File "C:\Users\User\Desktop\boris\Lib\site-packages\boris\core.py", line 1754, in signal_from_widget
    self.keyPressEvent(event)
  File "C:\Users\User\Desktop\boris\Lib\site-packages\boris\core.py", line 4739, in keyPressEvent
    self.next_frame()
  File "C:\Users\User\Desktop\boris\Lib\site-packages\boris\core.py", line 3647, in next_frame
    self.extract_frame(self.dw_player[0])
  File "C:\Users\User\Desktop\boris\Lib\site-packages\boris\core.py", line 1705, in extract_frame
    seconds_from_1st_formated = util.seconds2time(seconds_from_1st).split(".")[0]  # remove milliseconds
                                                  ^^^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'seconds_from_1st' where it is not associated with a value

System info

Host Name:                 DESKTOP-6HB44H3
OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.19045 N/A Build 19045
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          User
Registered Organization:   N/A
Product ID:                00325-80791-23995-AAOEM
Original Install Date:     14.03.2021, 23:35:57
System Boot Time:          24.03.2024, 14:24:19
System Manufacturer:       Acer
System Model:              Aspire A315-51
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 78 Stepping 3 GenuineIntel ~1992 Mhz
BIOS Version:              Insyde Corp. V1.01, 20.03.2017
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume2
System Locale:             cs;¬eçtina
Input Locale:              cs;¬eçtina
Time Zone:                 (UTC+01:00) Praha, Bratislava, Budapeçś, BŘlehrad, Lublaĺ
Total Physical Memory:     3˙972 MB
Available Physical Memory: 700 MB
Virtual Memory: Max Size:  5˙530 MB
Virtual Memory: Available: 755 MB
Virtual Memory: In Use:    4˙775 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\DESKTOP-6HB44H3
Hotfix(s):                 30 Hotfix(s) Installed.
                           [01]: KB5034466
                           [02]: KB5030841
                           [03]: KB4580325
                           [04]: KB5000736
                           [05]: KB5011048
                           [06]: KB5011052
                           [07]: KB5012170
                           [08]: KB5015684
                           [09]: KB5035845
                           [10]: KB5006753
                           [11]: KB5007273
                           [12]: KB5011352
                           [13]: KB5011651
                           [14]: KB5014032
                           [15]: KB5014035
                           [16]: KB5015895
                           [17]: KB5016705
                           [18]: KB5018506
                           [19]: KB5020372
                           [20]: KB5022924
                           [21]: KB5025315
                           [22]: KB5026879
                           [23]: KB5028318
                           [24]: KB5028380
                           [25]: KB5029709
                           [26]: KB5031539
                           [27]: KB5032392
                           [28]: KB5032907
                           [29]: KB5036447
                           [30]: KB5005699
Network Card(s):           3 NIC(s) Installed.
                           [01]: Realtek PCIe GbE Family Controller
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [02]: Intel(R) Dual Band Wireless-AC 3168
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.1.1
                                 IP address(es)
                                 [01]: 192.168.1.233
                                 [02]: fe80::b579:6701:beb1:8892
                           [03]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Sˇśov‚ pýipojenˇ Bluetooth
                                 Status:          Media disconnected
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

**Comment by olivierfriard** [comment]
Hello,

can you reproduce this issue with the current version (8.24.3)?
