### ISSUE TITLE
Error produced when attempting geometric measurements

### ISSUE THREAD

**Issue by JManning-reefeco** [olivierfriard/BORIS#737]
An error has occured!

to improve the software please report this problem at:
https://github.com/olivierfriard/BORIS/issues

Please no screenshot, the error message was copied to the clipboard.

Thank you for your collaboration!

BORIS version: 8.24.3
OS: Windows 10 10.0.19045
CPU: AMD64 Intel64 Family 6 Model 142 Stepping 10, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.10
MPV library version: 2.1
MPV library file path: D:\Program Files\BORIS\Lib\site-packages\boris\misc\mpv-2.dll

Error succeded at 2024-04-07 16:12

Traceback (most recent call last):
  File "D:\Program Files\BORIS\Lib\site-packages\boris\core.py", line 1713, in frame_image_clicked
    geometric_measurement.image_clicked(self, n_player, event)
  File "D:\Program Files\BORIS\Lib\site-packages\boris\geometric_measurement.py", line 556, in image_clicked
    media_file_name = str(pl.Path(fn).relative_to(pl.Path(self.projectFileName).parent))
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\Program Files\BORIS\Lib\pathlib.py", line 730, in relative_to
    raise ValueError("{!r} is not in the subpath of {!r}"
ValueError: 'G:\\.shortcut-targets-by-id\\1tHpWt1tB2cFJR68_BO95WRNDb5MzfGTC\\autocut_clips\\0623MG35_B_TR_SO_FL_SH_X.mp4' is not in the subpath of 'C:\\Users\\joshu\\Desktop' OR one path is relative and the other is absolute.

System info
===========

Host Name:                 LAPTOP-96UUIR4R
OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.19045 N/A Build 19045
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          joshua.c.manning@gmail.com
Registered Organization:   N/A
Product ID:                00325-96555-33171-AAOEM
Original Install Date:     1/30/2021, 2:36:42 PM
System Boot Time:          3/20/2024, 8:06:09 PM
System Manufacturer:       ASUSTeK COMPUTER INC.
System Model:              X510UAR
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 142 Stepping 10 GenuineIntel ~1792 Mhz
BIOS Version:              American Megatrends Inc. X510UAR.309, 7/24/2018
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume3
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-07:00) Mountain Time (US & Canada)
Total Physical Memory:     8,075 MB
Available Physical Memory: 700 MB
Virtual Memory: Max Size:  21,387 MB
Virtual Memory: Available: 4,562 MB
Virtual Memory: In Use:    16,825 MB
Page File Location(s):     D:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\LAPTOP-96UUIR4R
Hotfix(s):                 35 Hotfix(s) Installed.
                           [01]: KB5034466
                           [02]: KB5028853
                           [03]: KB4577586
                           [04]: KB4580325
                           [05]: KB4589212
                           [06]: KB4598481
                           [07]: KB5000736
                           [08]: KB5011048
                           [09]: KB5012170
                           [10]: KB5015684
                           [11]: KB5035845
                           [12]: KB5006753
                           [13]: KB5007273
                           [14]: KB5011352
                           [15]: KB5011651
                           [16]: KB5014032
                           [17]: KB5014035
                           [18]: KB5014671
                           [19]: KB5015895
                           [20]: KB5016705
                           [21]: KB5018506
                           [22]: KB5020372
                           [23]: KB5022924
                           [24]: KB5023794
                           [25]: KB5025315
                           [26]: KB5026879
                           [27]: KB5028318
                           [28]: KB5028380
                           [29]: KB5029709
                           [30]: KB5031539
                           [31]: KB5032392
                           [32]: KB5032907
                           [33]: KB5034224
                           [34]: KB5036447
                           [35]: KB5005699
Network Card(s):           1 NIC(s) Installed.

**Comment by olivierfriard** [comment]
Hi,
can you give me more info about your project and how your media are organized?
The G:\.shortcut-targets-by-id ... seems a little bit strange

**Comment by JManning-reefeco** [comment]
We have video files (on a Google Drive) that we are attempting frame by frame analysis of (using ethogram to identify when behaviors occur for each subject in the video). For one frame, we want to record the positions (add a point geometry) of each subject in the frame and save the locations as a separate file.
