### ISSUE TITLE
Unable to Import Project from Noldus the Observer

### ISSUE THREAD

**Issue by gracegliu** [olivierfriard/BORIS#739]
**Indicate the version of BORIS**
 8.24.1

**Describe the bug**
Unable to import Noldus Observer project (.odx) from Observer 15.

**To Reproduce**
1. Export Noldus project as .odx file (exported with and without media files--same error occurs. Also tried exporting different projects)
2. Import Project From --> Noldus the Observer
3. Error occurs.

**Expected behavior**
Noldus project opens in Boris for editing and exporting.

BORIS log:

> An error has occured!

to improve the software please report this problem at:
https://github.com/olivierfriard/BORIS/issues

Please no screenshot, the error message was copied to the clipboard.

Thank you for your collaboration!

BORIS version: 8.24.1
OS: Windows 10 10.0.19045
CPU: AMD64 Intel64 Family 6 Model 158 Stepping 10, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.10
MPV library version: 2.1
MPV library file path: C:\Users\AhmariLab\BORIS\Lib\site-packages\boris\misc\mpv-2.dll

Error succeded at 2024-04-10 11:37

Traceback (most recent call last):
  File "C:\Users\AhmariLab\BORIS\Lib\site-packages\boris\core.py", line 3013, in import_project_from_observer_template
    pj = otx_parser.otx_to_boris(file_name)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\AhmariLab\BORIS\Lib\site-packages\boris\otx_parser.py", line 376, in otx_to_boris
    event.getElementsByTagName("OBS_EVENT_BEHAVIOR")[0]
IndexError: list index out of range

System info
===========

Host Name:                 OAC-BSPAHM6
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19045 N/A Build 19045
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          AhmariLab
Registered Organization:   N/A
Product ID:                00330-80000-00000-AA727
Original Install Date:     6/26/2020, 1:53:04 AM
System Boot Time:          3/12/2024, 7:23:02 PM
System Manufacturer:       Alienware
System Model:              Alienware Aurora R8
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 158 Stepping 10 GenuineIntel ~3192 Mhz
BIOS Version:              Alienware 1.0.26, 11/22/2022
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume4
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     32,590 MB
Available Physical Memory: 22,473 MB
Virtual Memory: Max Size:  67,964 MB
Virtual Memory: Available: 37,201 MB
Virtual Memory: In Use:    30,763 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    univ.pitt.edu
Logon Server:              \\OAC-BSPAHM6
Hotfix(s):                 38 Hotfix(s) Installed.
                           [01]: KB5034466
                           [02]: KB5036618
                           [03]: KB5028951
                           [04]: KB4560366
                           [05]: KB4561600
                           [06]: KB4566785
                           [07]: KB4570334
                           [08]: KB4576754
                           [09]: KB4577266
                           [10]: KB4580325
                           [11]: KB4586864
                           [12]: KB4593175
                           [13]: KB4598481
                           [14]: KB5000736
                           [15]: KB5011048
                           [16]: KB5012170
                           [17]: KB5015684
                           [18]: KB5036892
                           [19]: KB5006753
                           [20]: KB5015895
                           [21]: KB5016705
                           [22]: KB5018506
                           [23]: KB5020372
                           [24]: KB5022924
                           [25]: KB5023794
                           [26]: KB5025315
                           [27]: KB5026879
                           [28]: KB5028318
                           [29]: KB5028380
                           [30]: KB5029709
                           [31]: KB5031539
                           [32]: KB5032392
                           [33]: KB5032907
                           [34]: KB5034224
                           [35]: KB5036447
                           [36]: KB5037018
                           [37]: KB5005699
                           [38]: KB5034441
Network Card(s):           3 NIC(s) Installed.
                           [01]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
                           [02]: Killer E2500 Gigabit Ethernet Controller
                                 Connection Name: Ethernet
                                 DHCP Enabled:    Yes
                                 DHCP Server:     136.142.57.13
                                 IP address(es)
                                 [01]: 10.221.5.32
                                 [02]: fe80::eeb0:2f9b:3b2d:1164
                           [03]: Qualcomm QCA9377 802.11ac Wireless Adapter
                                 Connection Name: Wi-Fi
                                 Status:          Media disconnected
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

**Comment by olivierfriard** [comment]
Hi,
thank you for reporting this.
Is it possible to have the Noldus project to test?
You can send me by email (see the about page of the BORIS web site)

**Comment by gracegliu** [comment]
Thank you--I've sent over the project

**Comment by olivierfriard** [comment]
Hi,

did you try the new version of BORIS (8.25.4)?
It should fix the issue you have reported.
Please let me know

**Comment by gracegliu** [comment]
Hi Olivier,

I'm so sorry for the late response! We did try it—it now loads in the Observer file properly. Thank you so much! The only thing is that state events are loaded in as point events (I'm not sure how point events coded in Noldus are loaded—we didn't have any in the file). It's an easy fix in the project edit though.

Thanks again!
Grace
________________________________
