### ISSUE TITLE
Unable to open observation of a high speed camera video file

### ISSUE THREAD

**Issue by Karlijnkooij** [olivierfriard/BORIS#741]
**Indicate the version of BORIS**
8.19.1

**Describe the bug**
I have used a High speed camera (120 frames per second). However I am unable to upload this video file. 

**To Reproduce**

Select new observation
Click on 'observation from media file'
Add media with absolute path
Select media file
See error

BORIS version: 8.19.1
OS: Windows 10 10.0.19045
CPU: AMD64 Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.9
2024-04-24 17:12

Traceback (most recent call last):
  File "C:\Users\kk194\BORIS\Lib\site-packages\boris\observation.py", line 140, in 
    menu.triggered.connect(lambda x: self.add_media(mode=x.statusTip()))
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kk194\BORIS\Lib\site-packages\boris\observation.py", line 1138, in add_media
    (error, msg) = self.check_media(file_path, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kk194\BORIS\Lib\site-packages\boris\observation.py", line 1040, in check_media
    media_info = util.accurate_media_analysis(self.ffmpeg_bin, file_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kk194\BORIS\Lib\site-packages\boris\utilities.py", line 1241, in accurate_media_analysis
    ffprobe_results = ffprobe_media_analysis(ffmpeg_bin, file_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kk194\BORIS\Lib\site-packages\boris\utilities.py", line 1208, in ffprobe_media_analysis
    "audio_duration": audio_duration,
                      ^^^^^^^^^^^^^^
UnboundLocalError: cannot access local variable 'audio_duration' where it is not associated with a value

System info

Host Name:                 LP194
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19045 N/A Build 19045
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          LP194
Registered Organization:   
Product ID:                00329-10331-43630-AA995
Original Install Date:     16-11-2021, 10:19:47
System Boot Time:          24-4-2024, 14:14:27
System Manufacturer:       HP
System Model:              HP EliteBook 840 G7 Notebook PC
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 142 Stepping 12 GenuineIntel ~1609 Mhz
BIOS Version:              HP S70 Ver. 01.06.01, 5-8-2021
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;Engels (Verenigde Staten)
Input Locale:              en-us;Engels (Verenigde Staten)
Time Zone:                 (UTC+01:00) Amsterdam, Berlijn, Bern, Rome, Stockholm, Wenen
Total Physical Memory:     7.965 MB
Available Physical Memory: 2.687 MB
Virtual Memory: Max Size:  13.341 MB
Virtual Memory: Available: 6.887 MB
Virtual Memory: In Use:    6.454 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    arthur.nscr.nl
Logon Server:              \\LP194
Hotfix(s):                 26 Hotfix(s) Installed.
                           [01]: KB5037587
                           [02]: KB5028951
                           [03]: KB5000736
                           [04]: KB5011048
                           [05]: KB5012170
                           [06]: KB5015684
                           [07]: KB5036892
                           [08]: KB5006753
                           [09]: KB5011651
                           [10]: KB5014032
                           [11]: KB5014035
                           [12]: KB5020372
                           [13]: KB5022924
                           [14]: KB5023794
                           [15]: KB5025315
                           [16]: KB5026879
                           [17]: KB5028318
                           [18]: KB5028380
                           [19]: KB5029709
                           [20]: KB5031539
                           [21]: KB5032392
                           [22]: KB5032907
                           [23]: KB5034224
                           [24]: KB5036447
                           [25]: KB5037018
                           [26]: KB5003742
Network Card(s):           4 NIC(s) Installed.
                           [01]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
                           [02]: Intel(R) Wi-Fi 6 AX201 160MHz
                                 Connection Name: Wi-Fi
                                 Status:          Media disconnected
                           [03]: TAP-Windows Adapter V9 for OpenVPN Connect
                                 Connection Name: Local Area Connection
                                 Status:          Media disconnected
                           [04]: Realtek USB GbE Family Controller
                                 Connection Name: Ethernet 3
                                 DHCP Enabled:    Yes
                                 DHCP Server:     130.37.74.1
                                 IP address(es)
                                 [01]: 130.37.74.47
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

**Comment by olivierfriard** [comment]
Hi,
can you reproduce this issue with the current version (8.25.4)?
