### ISSUE TITLE
Issue with "limit to an observation interval"

### ISSUE THREAD

**Issue by bordesse** [olivierfriard/BORIS#745]
BORIS version: 8.22.6
OS: Windows 10 10.0.19045
CPU: AMD64 Intel64 Family 6 Model 186 Stepping 3, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.10
2024-05-06 10:17

Traceback (most recent call last):
  File "C:\Program Files (x86)\BORIS\Lib\site-packages\boris\observation.py", line 358, in limit_time_interval
    time_interval_dialog.time_widget.set_time(0)
  File "C:\Program Files (x86)\BORIS\Lib\site-packages\boris\duration_widget.py", line 188, in set_time
    if new_time.is_nan():
       ^^^^^^^^^^^^^^^
AttributeError: 'int' object has no attribute 'is_nan'

System info

Host Name:                 I106LAP95
OS Name:                   Microsoft Windows 10 Education
OS Version:                10.0.19045 N/A Build 19045
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          IT-Services
Registered Organization:   Vetmeduni Vienna
Product ID:                00328-10000-00001-AA620
Original Install Date:     21.12.2023, 10:45:35
System Boot Time:          05.05.2024, 21:56:07
System Manufacturer:       LENOVO
System Model:              21HES0RX00
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 186 Stepping 3 GenuineIntel ~893 Mhz
BIOS Version:              LENOVO N3QET39W (1.39 ), 23.10.2023
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-gb;English (United Kingdom)
Input Locale:              de;German (Germany)
Time Zone:                 (UTC+01:00) Amsterdam, Berlin, Bern, Rome, Stockholm, Vienna
Total Physical Memory:     16.065 MB
Available Physical Memory: 11.275 MB
Virtual Memory: Max Size:  18.497 MB
Virtual Memory: Available: 12.596 MB
Virtual Memory: In Use:    5.901 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    vmudomain.vu-wien.ac.at
Logon Server:              \\ADDC3
Hotfix(s):                 12 Hotfix(s) Installed.
                           [01]: KB5034468
                           [02]: KB5036608
                           [03]: KB5012170
                           [04]: KB5015684
                           [05]: KB5036892
                           [06]: KB5014032
                           [07]: KB5020372
                           [08]: KB5031539
                           [09]: KB5032907
                           [10]: KB5034224
                           [11]: KB5036447
                           [12]: KB5037018
Network Card(s):           4 NIC(s) Installed.
                           [01]: Intel(R) Wi-Fi 6E AX211 160MHz
                                 Connection Name: WiFi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     193.171.98.132
                                 IP address(es)
                                 [01]: 10.157.3.235
                                 [02]: fe80::ec5:82c0:e693:18c9
                                 [03]: 2001:628:2080:157:d50f:d998:27d7:7306
                                 [04]: 2001:628:2080:157:1240:fa01:49de:ba98
                           [02]: Intel(R) Ethernet Connection (23) I219-V
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [03]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
                           [04]: Cisco AnyConnect Secure Mobility Client Virtual Miniport Adapter for Windows x64
                                 Connection Name: Ethernet 2
                                 Status:          Hardware not present
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: No
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

**Comment by olivierfriard** [comment]
Hi,
can you reproduce this issue with the last version of BORIS?
See https://www.boris.unito.it/download
