### ISSUE TITLE
Error when I tried to create a new observation

### ISSUE THREAD

**Issue by laura9130** [olivierfriard/BORIS#746]
**Indicate the version of BORIS**
 Verify you are using the last version (http://www.boris.unito.it/pages/download.html)

**Describe the bug**
Issue appeared when trying to create new observation.

**To Reproduce**

**Expected behavior**
Observation to be created.

**Screenshots**
BORIS version: 8.20.3
OS: Windows 10 10.0.19045
CPU: AMD64 Intel64 Family 6 Model 186 Stepping 3, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.9
2024-05-10 09:28

Traceback (most recent call last):
  File "C:\Users\c3287023\BORIS\Lib\site-packages\boris\observation.py", line 140, in 
    menu.triggered.connect(lambda x: self.add_media(mode=x.statusTip()))
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\c3287023\BORIS\Lib\site-packages\boris\observation.py", line 1138, in add_media
    (error, msg) = self.check_media(file_path, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\c3287023\BORIS\Lib\site-packages\boris\observation.py", line 1040, in check_media
    media_info = util.accurate_media_analysis(self.ffmpeg_bin, file_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\c3287023\BORIS\Lib\site-packages\boris\utilities.py", line 1278, in accurate_media_analysis
    ffprobe_results = ffprobe_media_analysis(ffmpeg_bin, file_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\c3287023\BORIS\Lib\site-packages\boris\utilities.py", line 1173, in ffprobe_media_analysis
    video_param = json.loads(out.decode("utf-8"))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\c3287023\BORIS\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\c3287023\BORIS\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\c3287023\BORIS\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

System info

Host Name:                 HDR-C158RV3
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19045 N/A Build 19045
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          UON
Registered Organization:   University of Newcastle
Product ID:                00330-80000-00000-AA776
Original Install Date:     29/05/2023, 10:41:38 AM
System Boot Time:          10/05/2024, 9:00:23 AM
System Manufacturer:       Dell Inc.
System Model:              Latitude 5440
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 186 Stepping 3 GenuineIntel ~1800 Mhz
BIOS Version:              Dell Inc. 1.2.0, 14/03/2023
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC+10:00) Canberra, Melbourne, Sydney
Total Physical Memory:     32,421 MB
Available Physical Memory: 19,975 MB
Virtual Memory: Max Size:  37,285 MB
Virtual Memory: Available: 24,179 MB
Virtual Memory: In Use:    13,106 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    uncle.newcastle.edu.au
Logon Server:              \\CALLA-DC01
Hotfix(s):                 16 Hotfix(s) Installed.
                           [01]: KB5036608
                           [02]: KB5003791
                           [03]: KB5012170
                           [04]: KB5015684
                           [05]: KB5020683
                           [06]: KB5036892
                           [07]: KB5014032
                           [08]: KB5023794
                           [09]: KB5026879
                           [10]: KB5028318
                           [11]: KB5031539
                           [12]: KB5032907
                           [13]: KB5034224
                           [14]: KB5036447
                           [15]: KB5037018
                           [16]: KB5005699
Network Card(s):           2 NIC(s) Installed.
                           [01]: Intel(R) Wi-Fi 6E AX211 160MHz
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.0.2.1
                                 IP address(es)
                                 [01]: 10.222.14.88
                                 [02]: fe80::113f:5dc:3af:41ab
                           [02]: Intel(R) Ethernet Connection (23) I219-LM
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

**Desktop (please complete the following information):**
 - OS: [windows 10, Ubuntu 22.04 ... ]
 - Type of BORIS instalaltion (setup or portable ...)

**In case of crash** attach or copy the content of the boris.log file (before relaunching BORIS).
(see http://www.boris.unito.it/pages/report_a_bug.html for its location)

**Comment by olivierfriard** [comment]
Hi,
Can you reproduce this issue with the laost version?
Best regards



-- 
Research technician
Dept of Life Sciences and Systems Biology
University of Torino
tel: +39 011 6704542
http://penelope.unito.it/friard/
GitHub: olivierfriard <https://github.com/olivierfriard>
ORCID: 0000-0002-0374-9872 <http://orcid.org/0000-0002-0374-9872>
Web of Science ResearcherID: ABG-2435-2021
<https://publons.com/researcher/4857666/olivier-friard/>
Scopus Author ID: 10639803800
<https://www.scopus.com/authid/detail.uri?authorId=10639803800>
