### ISSUE TITLE
Error when trying to export aggregated events

### ISSUE THREAD

**Issue by samhc7** [olivierfriard/BORIS#747]
**Indicate the version of BORIS**
 Verify you are using the last version (http://www.boris.unito.it/pages/download.html)
8.25.4

**Describe the bug**
Trying to export aggregated events of a subset of behaviours and subjects and it fails.

**To Reproduce**
1. Go to 'Observations'
2. Click on 'Export events>Aggregated events'
3. Select all
4. Pick subjects and behaviours
5. Select yes to save all in same file 
6. Choose where to save file
7. See error

**Expected behavior**
To export events as a csv or tsv file

**Screenshots**
BORIS version: 8.25.4
OS: Windows 10 10.0.19045
CPU: AMD64 Intel64 Family 6 Model 186 Stepping 2, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.10
MPV library version: 2.1
MPV library file path: C:\Users\er20608\BORIS\Lib\site-packages\boris\misc\mpv-2.dll

Error succeded at 2024-05-16 10:20

Traceback (most recent call last):
  File "C:\Users\er20608\BORIS\Lib\site-packages\boris\connections.py", line 149, in <lambda>
    self.actionExport_aggregated_events.triggered.connect(lambda: export_events.export_aggregated_events(self))
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\er20608\BORIS\Lib\site-packages\boris\export_events.py", line 530, in export_aggregated_events
    data_grouped_obs_all.extend(data_grouped_obs)
  File "C:\Users\er20608\BORIS\Lib\site-packages\tablib\core.py", line 487, in extend
    self.append(row, tags)
  File "C:\Users\er20608\BORIS\Lib\site-packages\tablib\core.py", line 479, in append
    self.rpush(row, tags)
  File "C:\Users\er20608\BORIS\Lib\site-packages\tablib\core.py", line 465, in rpush
    self.insert(self.height, row=row, tags=tags)
  File "C:\Users\er20608\BORIS\Lib\site-packages\tablib\core.py", line 453, in insert
    self._validate(row)
  File "C:\Users\er20608\BORIS\Lib\site-packages\tablib\core.py", line 267, in _validate
    raise InvalidDimensions
tablib.exceptions.InvalidDimensions

System info
===========

Host Name:                 IT102441
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19045 N/A Build 19045
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          N/A
Registered Organization:   N/A
Product ID:                00329-10380-21520-AA813
Original Install Date:     18/04/2024, 06:17:06
System Boot Time:          13/05/2024, 12:27:33
System Manufacturer:       Dell Inc.
System Model:              Latitude 5440
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 186 Stepping 2 GenuineIntel ~1900 Mhz
BIOS Version:              Dell Inc. 1.12.0, 05/02/2024
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-gb;English (United Kingdom)
Input Locale:              en-gb;English (United Kingdom)
Time Zone:                 (UTC+00:00) Dublin, Edinburgh, Lisbon, London
Total Physical Memory:     32,453 MB
Available Physical Memory: 25,238 MB
Virtual Memory: Max Size:  37,317 MB
Virtual Memory: Available: 28,967 MB
Virtual Memory: In Use:    8,350 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\IT102441
Hotfix(s):                 9 Hotfix(s) Installed.
                           [01]: KB5036608
                           [02]: KB5015684
                           [03]: KB5020683
                           [04]: KB5036892
                           [05]: KB5014032
                           [06]: KB5016705
                           [07]: KB5032907
                           [08]: KB5037018
                           [09]: KB5034441
Network Card(s):           3 NIC(s) Installed.
                           [01]: Intel(R) Wi-Fi 6E AX211 160MHz
                                 Connection Name: WiFi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     137.222.7.170
                                 IP address(es)
                                 [01]: 172.23.60.95
                                 [02]: fe80::652a:a879:f939:be51
                                 [03]: 2001:630:e4:4220:a9aa:ca19:49e8:6c12
                                 [04]: 2001:630:e4:4220:253a:231a:9c12:9241
                           [02]: Intel(R) Ethernet Connection (23) I219-LM
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [03]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

**In case of crash** attach or copy the content of the boris.log file (before relaunching BORIS).
(see http://www.boris.unito.it/pages/report_a_bug.html for its location)

**Comment by samhc7** [comment]
Hi,

Thank you for getting back to me so quickly. I have since found that this error is not replicated if I export the aggregated events on a Mac, using the older version of BORIS. When you say you need a project file, do you also require observations within this?

Thanks,
Sam

On 16 May 2024, at 10:35, Olivier Friard ***@***.***> wrote:



Hi,
thank you for reporting this issue.
I need a minimal BORIS project file to reproduce the issue, is it possible ?

**Comment by olivierfriard** [comment]
I need a BORIS project file and a detailed procedure that allow me to reproduce this issue.
You can send me your project file by email (www.boris.unito.it > About).

**Comment by olivierfriard** [comment]
Did you find a solution?
Otherwise I need your project file to reproduce the issue and fix it.
You can send it by email (see the About page of www.boris.unito.it)

Thank you for your collaboration

**Comment by samhc7** [comment]
Hi,

Sorry for my delay in reply I missed your previous email. I am still having the issue on the latest version of BORIS for Windows (But not on an old one for MacOS). I have attached a project file. The issue is when I try to export aggregated events.

Thanks,
Sam

On 7 Jun 2024, at 13:59, Olivier Friard ***@***.***> wrote:



Did you find a solution?
Otherwise I need your project file to reproduce the issue and fix it.
You can send it by email (see the About page of www.boris.unito.it<http://www.boris.unito.it/>)

Thank you for your collaboration

**Comment by olivierfriard** [comment]
Hi,

I cannot find your attached project file on GitHub, please send it by email (see https://www.boris.unito.it/about )

**Comment by olivierfriard** [comment]
This issue should be fixed in the last release.
Can you confirm this?
