### ISSUE TITLE
Error when logging the start of a state event

### ISSUE THREAD

**Issue by MB250900** [olivierfriard/BORIS#754]
**Indicate the version of BORIS**
 Verify you are using the last version (http://www.boris.unito.it/pages/download.html)

**Describe the bug**
BORIS version: 8.27
OS: Windows 10 10.0.22631
CPU: AMD64 AMD64 Family 25 Model 68 Stepping 1, AuthenticAMD
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.10
MPV library version: 2.1
MPV library file path: C:\Users\megan\BORIS\Lib\site-packages\boris\misc\mpv-2.dll

Error succeded at 2024-06-10 22:52

Traceback (most recent call last):
  File "C:\Users\megan\BORIS\Lib\site-packages\boris\core.py", line 3952, in twEthogram_doubleClicked
    write_event.write_event(self, event, self.getLaps())
  File "C:\Users\megan\BORIS\Lib\site-packages\boris\write_event.py", line 269, in write_event
    modifiers_selector = select_modifiers.ModifiersList(
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\megan\BORIS\Lib\site-packages\boris\select_modifiers.py", line 82, in __init__
    lb = QLabel(f"<small>{self.modifiers_dict[idx]['description']}</small>")
                          ~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'description'


System info
===========

OS Name:                   Microsoft Windows 11 Home
OS Version:                10.0.22631 N/A Build 22631
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Organization:   N/A
Original Install Date:     05/06/2023, 02:55:11
System Boot Time:          10/06/2024, 18:12:56
System Manufacturer:       Acer
System Model:              Swift SFA16-41
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: AMD64 Family 25 Model 68 Stepping 1 AuthenticAMD ~2701 Mhz
BIOS Version:              Insyde Corp. V1.09, 04/10/2023
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-gb;English (United Kingdom)
Input Locale:              en-gb;English (United Kingdom)
Total Physical Memory:     15,556 MB
Available Physical Memory: 7,887 MB
Virtual Memory: Max Size:  21,444 MB
Virtual Memory: Available: 11,517 MB
Virtual Memory: In Use:    9,927 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Hotfix(s):                 6 Hotfix(s) Installed.
                           [01]: KB5037591
                           [02]: KB5012170
                           [03]: KB5026039
                           [04]: KB5027397
                           [05]: KB5037771
                           [06]: KB5037663
Network Card(s):           5 NIC(s) Installed.
                           [01]: TAP-NordVPN Windows Adapter V9
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [02]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
                           [03]: RZ616 Wi-Fi 6E 160MHz
                                 Connection Name: WiFi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.1.254
                                 IP address(es)
                                 [01]: 192.168.1.188
                           [04]: WireGuard Tunnel
                                 Connection Name: NordLynx
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 10.5.0.2
                                 [02]: fe80::723e:7ca:789d:a5aa
                           [05]: WireGuard Tunnel
                                 Connection Name: Local Area Connection
                                 Status:          Media disconnected
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.


**To Reproduce**
Steps to reproduce the behavior:
1. Go to '...'
2. Click on '....'
3. Scroll down to '....'
4. See error

**Expected behavior**
A clear and concise description of what you expected to happen.

**Screenshots**
If applicable, add screenshots to help explain your problem.

**Desktop (please complete the following information):**
 - OS: [windows 10, Ubuntu 22.04 ... ]
 - Type of BORIS instalaltion (setup or portable ...)

**In case of crash** attach or copy the content of the boris.log file (before relaunching BORIS).
(see http://www.boris.unito.it/pages/report_a_bug.html for its location)

**Comment by olivierfriard** [comment]
closed by mistake...

**Comment by olivierfriard** [comment]
Hi,
the issue should be fixed in v. 8.27.1
Please try and let me know:
https://www.boris.unito.it/download/

**Comment by MB250900** [comment]
The issue is fixed but the widget for my behaviours has disappeared and I am not able to see/open a coding pad, it says one is open but it does not show up

**Comment by olivierfriard** [comment]
Hi,
thank you for testing.
For the invisible widget please check https://www.boris.unito.it/faq

For the coding pad issue can you send me a screenshot with the error message?

Thank you for your collaboration

**Comment by MB250900** [comment]
There is no error message for the coding pad, it just doesn't appear, when hovering over the boric icon at the bottom of the screen a second blank page is there where the coding pad should be and when clicked on nothing shows up
