### ISSUE TITLE
Can't go back and carry on from where I last left off - this error pops up each time

### ISSUE THREAD

**Issue by cehbodie** [olivierfriard/BORIS#756]
An error has occured!

to improve the software please report this problem at:
https://github.com/olivierfriard/BORIS/issues

Please no screenshot, the error message was copied to the clipboard.

Thank you for your collaboration!

BORIS version: 8.25.4
OS: Windows 10 10.0.19045
CPU: AMD64 Intel64 Family 6 Model 154 Stepping 4, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.10
MPV library version: 2.1
MPV library file path: C:\Users\bodieceh\OneDrive - NIWA\Documents\boris-8.25.4-win64\Lib\site-packages\boris\misc\mpv-2.dll

Error succeded at 2024-06-16 14:16

Traceback (most recent call last):
  File "C:\Users\bodieceh\OneDrive - NIWA\Documents\boris-8.25.4-win64\Lib\site-packages\boris\core.py", line 5081, in tv_events_doubleClicked
    self.seek_mediaplayer(new_time)
  File "C:\Users\bodieceh\OneDrive - NIWA\Documents\boris-8.25.4-win64\Lib\site-packages\boris\core.py", line 1427, in seek_mediaplayer
    self.dw_player[player].player.seek(
  File "C:\Users\bodieceh\OneDrive - NIWA\Documents\boris-8.25.4-win64\Lib\site-packages\boris\mpv2.py", line 1235, in seek
    self.command('seek', amount, reference, precision)
  File "C:\Users\bodieceh\OneDrive - NIWA\Documents\boris-8.25.4-win64\Lib\site-packages\boris\mpv2.py", line 1228, in command
    _mpv_command_node(self.handle, ppointer, out)
  File "C:\Users\bodieceh\OneDrive - NIWA\Documents\boris-8.25.4-win64\Lib\site-packages\boris\mpv2.py", line 148, in raise_for_ec
    raise ex
SystemError: ('Error running mpv command', -12, (<MpvHandle object at 0x0000013F785B2AD0>, <boris.mpv2.LP_MpvNode object at 0x0000013F015FBCD0>, <boris.mpv2.LP_MpvNode object at 0x0000013F015FB9D0>))

System info
===========

Host Name:                 NIWA-1022593
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19045 N/A Build 19045
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          NIWA IT
Registered Organization:   NIWA
Product ID:                00330-80000-00000-AA069
Original Install Date:     21/03/2023, 7:08:36 am
System Boot Time:          16/06/2024, 1:59:15 pm
System Manufacturer:       HP
System Model:              HP EliteBook 840 14 inch G9 Notebook PC
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 154 Stepping 4 GenuineIntel ~1300 Mhz
BIOS Version:              HP U70 Ver. 01.10.00, 18/01/2024
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC+12:00) Auckland, Wellington
Total Physical Memory:     16,016 MB
Available Physical Memory: 5,679 MB
Virtual Memory: Max Size:  19,216 MB
Virtual Memory: Available: 7,775 MB
Virtual Memory: In Use:    11,441 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    niwa.local
Logon Server:              \\HAMWDC02
Hotfix(s):                 22 Hotfix(s) Installed.
                           [01]: KB5037592
                           [02]: KB5003791
                           [03]: KB5012170
                           [04]: KB5015684
                           [05]: KB5037768
                           [06]: KB5014032
                           [07]: KB5022924
                           [08]: KB5023794
                           [09]: KB5025315
                           [10]: KB5026879
                           [11]: KB5028318
                           [12]: KB5028380
                           [13]: KB5029709
                           [14]: KB5031539
                           [15]: KB5032392
                           [16]: KB5032907
                           [17]: KB5034224
                           [18]: KB5036447
                           [19]: KB5037018
                           [20]: KB5037240
                           [21]: KB5037995
                           [22]: KB5005699
Network Card(s):           3 NIC(s) Installed.
                           [01]: Intel(R) Wi-Fi 6E AX211 160MHz
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.178.1
                                 IP address(es)
                                 [01]: 192.168.178.52
                                 [02]: fe80::af91:baf8:9521:ee47
                           [02]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
                           [03]: Juniper Networks Virtual Adapter
                                 Connection Name: Ethernet 4
                                 DHCP Enabled:    No
                                 IP address(es)
                                 [01]: 192.168.86.61
                                 [02]: fe80::bee8:5fb3:65ca:9128
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by cehbodie** [comment]
Seems to work fine on the day it is being used but then each time I have re-opened the project the following day, start observation, scroll down to last recorded event and click start this error message pops up. I am unable to continue recording observations even after clicking ignore and continue. Is there anything else I could try to fix this issue?

Cheers,
Charlotte
