### ISSUE TITLE
Issue With boris.config attribute

### ISSUE THREAD

**Issue by sketch123456** [olivierfriard/BORIS#762]
When launching BORIS, the command prompt window shows up and the attribute error module 'boris.config' has no attribute 'FRAME_DEFAULT_BITMAP_FORMAT' shows up. Then, another exception occurs 

Traceback (most recent call last): 
File "", line 198, in _run_module_as_main
File "", line 88 in_run_code
File "C:\Boris\BORIS\Lib\site-packages\boris\_main_.py", line 25, in 
main()
File "C:\Boris\BORIS\Lib\site-packages\boris\core.py" , line 5217, in main
window=MainWindow(ffmpeg_bin)
^^^^^^^^^^^^^^^^^^^^^
File "C:\Boris\BORIS\Lib\site-packages\boris]core.py", line366, in _init_
config_file.read(self)
File "CL\Boris\BORIS\Lib\site-packages\boris\config_file.py", line 226, in read
self.frame_bitmap_format = cfg.FRAME_DEFAULT_BITMAP_FORMAT

**Comment by sketch123456** [comment]
I used pip uninstall boris-behav-obs and pip install boris-behav-obs to see if it would help, but now, if I open BORIS the command window opens and just closes almost immedaitely.

**Comment by olivierfriard** [comment]
Hi,
can you send me the boris.log file ?
See https://www.boris.unito.it/report_a_bug/

**Comment by olivierfriard** [comment]
Please completely delete the entire directory where BORIS was installed and install it again
