### ISSUE TITLE
When exporting aggregated events in CSV format for all individuals and behaviours

### ISSUE THREAD

**Issue by elisaffueyo** [olivierfriard/BORIS#767]
Error message pasted...

An error has occured!

to improve the software please report this problem at:
https://github.com/olivierfriard/BORIS/issues

Please no screenshot, the error message was copied to the clipboard.

Thank you for your collaboration!

BORIS version: 8.27
OS: Windows 10 10.0.22631
CPU: AMD64 AMD64 Family 23 Model 160 Stepping 0, AuthenticAMD
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.10
MPV library version: 2.1
MPV library file path: C:\Users\Elisa\BORIS\Lib\site-packages\boris\misc\mpv-2.dll

Error succeded at 2024-07-18 14:15

Traceback (most recent call last):
  File "C:\Users\Elisa\BORIS\Lib\site-packages\boris\connections.py", line 149, in <lambda>
    self.actionExport_aggregated_events.triggered.connect(lambda: export_events.export_aggregated_events(self))
                                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Elisa\BORIS\Lib\site-packages\boris\export_events.py", line 530, in export_aggregated_events
    data_grouped_obs_all.extend(data_grouped_obs)
  File "C:\Users\Elisa\BORIS\Lib\site-packages\tablib\core.py", line 487, in extend
    self.append(row, tags)
  File "C:\Users\Elisa\BORIS\Lib\site-packages\tablib\core.py", line 479, in append
    self.rpush(row, tags)
  File "C:\Users\Elisa\BORIS\Lib\site-packages\tablib\core.py", line 465, in rpush
    self.insert(self.height, row=row, tags=tags)
  File "C:\Users\Elisa\BORIS\Lib\site-packages\tablib\core.py", line 453, in insert
    self._validate(row)
  File "C:\Users\Elisa\BORIS\Lib\site-packages\tablib\core.py", line 267, in _validate
    raise InvalidDimensions
tablib.exceptions.InvalidDimensions

System info
===========

Host Name:                 LAPTOP-KPDOB7BK
OS Name:                   Microsoft Windows 11 Home
OS Version:                10.0.22631 N/A Build 22631
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Elisa
Registered Organization:   N/A
Product ID:                00342-21154-44942-AAOEM
Original Install Date:     11/04/2024, 12:33:15 AM
System Boot Time:          14/07/2024, 11:06:28 PM
System Manufacturer:       LENOVO
System Model:              82YU
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: AMD64 Family 23 Model 160 Stepping 0 AuthenticAMD ~2801 Mhz
BIOS Version:              LENOVO L1CN36WW, 01/12/2023
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-gb;English (United Kingdom)
Time Zone:                 (UTC+00:00) Dublin, Edinburgh, Lisbon, London
Total Physical Memory:     5,965 MB
Available Physical Memory: 400 MB
Virtual Memory: Max Size:  22,668 MB
Virtual Memory: Available: 4,483 MB
Virtual Memory: In Use:    18,185 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\LAPTOP-KPDOB7BK
Hotfix(s):                 6 Hotfix(s) Installed.
                           [01]: KB5039895
                           [02]: KB5027397
                           [03]: KB5031274
                           [04]: KB5036212
                           [05]: KB5040442
                           [06]: KB5039338
Network Card(s):           3 NIC(s) Installed.
                           [01]: Realtek 8822CE Wireless LAN 802.11ac PCI-E NIC
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     134.219.164.3
                                 IP address(es)
                                 [01]: 10.2.156.69
                                 [02]: fe80::250d:8a5b:c3fb:b567
                           [02]: Realtek PCIe GbE Family Controller
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [03]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by olivierfriard** [comment]
Hi,
this issue should be fixed in v. 8.27.4 just released.
Please check and let me know.

Thank you for your collaboration.
