### ISSUE TITLE
cannot save ethogram

### ISSUE THREAD

**Issue by areinhar01** [olivierfriard/BORIS#769]
So I have started a new project and I keep trying to save my ethogram but I keep getting the following error. 

BORIS version: 8.27
OS: Windows 10 10.0.19045
CPU: AMD64 Intel64 Family 6 Model 158 Stepping 13, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.10
MPV library version: 2.1
MPV library file path: C:\Users\areinhar\Downloads\borislater\Lib\site-packages\boris\misc\mpv-2.dll

Error succeded at 2024-07-23 10:57

Traceback (most recent call last):
  File "C:\Users\areinhar\Downloads\borislater\Lib\site-packages\boris\project.py", line 316, in <lambda>
    self.pbExportEthogram.clicked.connect(lambda: project_import_export.export_ethogram(self))
                                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\areinhar\Downloads\borislater\Lib\site-packages\boris\project_import_export.py", line 87, in export_ethogram
    r = self.check_ethogram()
        ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\areinhar\Downloads\borislater\Lib\site-packages\boris\project.py", line 1706, in check_ethogram
    row["modifiers"] = json.loads(row["modifiers"]) if row["modifiers"] else {}
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\areinhar\Downloads\borislater\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\areinhar\Downloads\borislater\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\areinhar\Downloads\borislater\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

System info
===========

Host Name:                 STFX2768
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19045 N/A Build 19045
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          STFX
Registered Organization:   STFX
Product ID:                00329-00000-00003-AA338
Original Install Date:     2/21/2022, 12:26:57 PM
System Boot Time:          7/14/2024, 11:13:52 AM
System Manufacturer:       Dell Inc.
System Model:              Precision 3541
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 158 Stepping 13 GenuineIntel ~2304 Mhz
BIOS Version:              Dell Inc. 1.31.0, 4/2/2024
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume3
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-08:00) Pacific Time (US & Canada)
Total Physical Memory:     32,538 MB
Available Physical Memory: 25,522 MB
Virtual Memory: Max Size:  37,402 MB
Virtual Memory: Available: 29,211 MB
Virtual Memory: In Use:    8,191 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    ad.stfx.ca
Logon Server:              \\ANTONIO
Hotfix(s):                 34 Hotfix(s) Installed.
                           [01]: KB5039893
                           [02]: KB5028951
                           [03]: KB4562830
                           [04]: KB5000736
                           [05]: KB5003791
                           [06]: KB5007401
                           [07]: KB5011048
                           [08]: KB5012170
                           [09]: KB5015684
                           [10]: KB5040427
                           [11]: KB5011352
                           [12]: KB5014032
                           [13]: KB5014035
                           [14]: KB5014671
                           [15]: KB5015895
                           [16]: KB5016705
                           [17]: KB5018506
                           [18]: KB5020372
                           [19]: KB5022924
                           [20]: KB5023794
                           [21]: KB5025315
                           [22]: KB5026879
                           [23]: KB5028318
                           [24]: KB5028380
                           [25]: KB5029709
                           [26]: KB5031539
                           [27]: KB5032392
                           [28]: KB5032907
                           [29]: KB5037018
                           [30]: KB5037240
                           [31]: KB5037995
                           [32]: KB5039336
                           [33]: KB5005260
                           [34]: KB5034441
Network Card(s):           5 NIC(s) Installed.
                           [01]: Intel(R) Ethernet Connection (7) I219-LM
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [02]: Qualcomm QCA61x4A 802.11ac Wireless Adapter
                                 Connection Name: Wi-Fi
                                 Status:          Media disconnected
                           [03]: Fortinet Virtual Ethernet Adapter (NDIS 6.30)
                                 Connection Name: Ethernet 2
                                 Status:          Media disconnected
                           [04]: Fortinet SSL VPN Virtual Ethernet Adapter
                                 Connection Name: Ethernet 3
                                 Status:          Media disconnected
                           [05]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection 2
                                 Status:          Media disconnected
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

**Comment by olivierfriard** [comment]
Hi,
this issue should be fixed in v. 8.27.3
Please test and let me know.
See https://github.com/olivierfriard/BORIS/releases/tag/v8.27.3
