### ISSUE TITLE
cannot save ethogram or project

### ISSUE THREAD

**Issue by areinhar01** [olivierfriard/BORIS#770]
Hi! I cannot save my project or ethogram. I get this error code every time I try to save either. Any help would be greatly appreciated!

BORIS version: 8.27
OS: Windows 10 10.0.19045
CPU: AMD64 Intel64 Family 6 Model 158 Stepping 13, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.10
MPV library version: 2.1
MPV library file path: C:\Users\areinhar\Downloads\borislater\Lib\site-packages\boris\misc\mpv-2.dll

Error succeded at 2024-07-23 11:19

Traceback (most recent call last):
  File "C:\Users\areinhar\Downloads\borislater\Lib\site-packages\boris\project.py", line 1848, in pbOK_clicked
    r = dict(self.check_ethogram())
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\areinhar\Downloads\borislater\Lib\site-packages\boris\project.py", line 1706, in check_ethogram
    row["modifiers"] = json.loads(row["modifiers"]) if row["modifiers"] else {}
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\areinhar\Downloads\borislater\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\areinhar\Downloads\borislater\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\areinhar\Downloads\borislater\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

System info
===========

Host Name:                 STFX2768
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19045 N/A Build 19045
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          STFX
Registered Organization:   STFX
Product ID:                00329-00000-00003-AA338
Original Install Date:     2/21/2022, 12:26:57 PM
System Boot Time:          7/14/2024, 11:13:52 AM
System Manufacturer:       Dell Inc.
System Model:              Precision 3541
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 158 Stepping 13 GenuineIntel ~2304 Mhz
BIOS Version:              Dell Inc. 1.31.0, 4/2/2024
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume3
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-08:00) Pacific Time (US & Canada)
Total Physical Memory:     32,538 MB
Available Physical Memory: 24,356 MB
Virtual Memory: Max Size:  37,402 MB
Virtual Memory: Available: 28,385 MB
Virtual Memory: In Use:    9,017 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    ad.stfx.ca
Logon Server:              \\ANTONIO
Hotfix(s):                 34 Hotfix(s) Installed.
                           [01]: KB5039893
                           [02]: KB5028951
                           [03]: KB4562830
                           [04]: KB5000736
                           [05]: KB5003791
                           [06]: KB5007401
                           [07]: KB5011048
                           [08]: KB5012170
                           [09]: KB5015684
                           [10]: KB5040427
                           [11]: KB5011352
                           [12]: KB5014032
                           [13]: KB5014035
                           [14]: KB5014671
                           [15]: KB5015895
                           [16]: KB5016705
                           [17]: KB5018506
                           [18]: KB5020372
                           [19]: KB5022924
                           [20]: KB5023794
                           [21]: KB5025315
                           [22]: KB5026879
                           [23]: KB5028318
                           [24]: KB5028380
                           [25]: KB5029709
                           [26]: KB5031539
                           [27]: KB5032392
                           [28]: KB5032907
                           [29]: KB5037018
                           [30]: KB5037240
                           [31]: KB5037995
                           [32]: KB5039336
                           [33]: KB5005260
                           [34]: KB5034441
Network Card(s):           5 NIC(s) Installed.
                           [01]: Intel(R) Ethernet Connection (7) I219-LM
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [02]: Qualcomm QCA61x4A 802.11ac Wireless Adapter
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.1.254
                                 IP address(es)
                                 [01]: 192.168.1.182
                                 [02]: fe80::5829:d:4cb:161c
                                 [03]: 2001:569:bdf4:f200:1534:7045:6c1b:1aac
                                 [04]: 2001:569:bdf4:f200:c3aa:b841:9581:17bc
                           [03]: Fortinet Virtual Ethernet Adapter (NDIS 6.30)
                                 Connection Name: Ethernet 2
                                 Status:          Media disconnected
                           [04]: Fortinet SSL VPN Virtual Ethernet Adapter
                                 Connection Name: Ethernet 3
                                 Status:          Media disconnected
                           [05]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection 2
                                 Status:          Media disconnected
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

**Comment by olivierfriard** [comment]
Hi,
this issue should be fixed in v. 8.27.3
Please test and let me know.
See https://github.com/olivierfriard/BORIS/releases/tag/v8.27.3

**Comment by swinquist** [comment]
I am trying to save my ethogram using v. 8.27.3 and also getting an error :( 
Any further tips appreciated. Thank you!

An error has occured!

to improve the software please report this problem at:
https://github.com/olivierfriard/BORIS/issues

Please no screenshot, the error message was copied to the clipboard.

Thank you for your collaboration!

BORIS version: 8.27.3
OS: Windows 10 10.0.19045
CPU: AMD64 Intel64 Family 6 Model 142 Stepping 12, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.11
MPV library version: 2.1
MPV library file path: C:\Users\localadmin\BORIS\Lib\site-packages\boris\misc\mpv-2.dll

Error succeded at 2024-09-05 19:49

Traceback (most recent call last):
  File "C:\Users\localadmin\BORIS\Lib\site-packages\boris\project.py", line 1881, in pbOK_clicked
    r = dict(self.check_ethogram())
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\localadmin\BORIS\Lib\site-packages\boris\project.py", line 1647, in check_ethogram
    if self.twBehaviors.item(r, cfg.behavioursFields["modifiers"]).text():
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'text'


System info
===========


Host Name:                 NASH128-LAP3
OS Name:                   Microsoft Windows 10 Enterprise
OS Version:                10.0.19045 N/A Build 19045
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Roots IT
Registered Organization:   Oregon State University
Product ID:                00329-00000-00003-AA507
Original Install Date:     8/27/2020, 1:04:40 PM
System Boot Time:          8/19/2024, 2:38:59 PM
System Manufacturer:       Dell Inc.
System Model:              Latitude 5510
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 142 Stepping 12 GenuineIntel ~1803 Mhz
BIOS Version:              Dell Inc. 1.28.0, 4/8/2024
Windows Directory:         C:\windows
System Directory:          C:\windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-08:00) Pacific Time (US & Canada)
Total Physical Memory:     15,984 MB
Available Physical Memory: 3,649 MB
Virtual Memory: Max Size:  39,536 MB
Virtual Memory: Available: 22,685 MB
Virtual Memory: In Use:    16,851 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    biossys.oregonstate.edu
Logon Server:              \\ONID-M-DC03
Hotfix(s):                 51 Hotfix(s) Installed.
                           [01]: KB5039893
                           [02]: KB5030841
                           [03]: KB4537759
                           [04]: KB4557968
                           [05]: KB4561600
                           [06]: KB4566785
                           [07]: KB4570334
                           [08]: KB4577266
                           [09]: KB4577586
                           [10]: KB4580325
                           [11]: KB4584642
                           [12]: KB4586864
                           [13]: KB4589212
                           [14]: KB4593175
                           [15]: KB4598481
                           [16]: KB5000736
                           [17]: KB5003791
                           [18]: KB5011048
                           [19]: KB5012170
                           [20]: KB5015684
                           [21]: KB5041580
                           [22]: KB5006753
                           [23]: KB5007273
                           [24]: KB5011352
                           [25]: KB5011651
                           [26]: KB5012677
                           [27]: KB5014032
                           [28]: KB5014035
                           [29]: KB5014671
                           [30]: KB5015895
                           [31]: KB5016705
                           [32]: KB5018506
                           [33]: KB5020372
                           [34]: KB5022924
                           [35]: KB5023794
                           [36]: KB5025315
                           [37]: KB5026879
                           [38]: KB5028318
                           [39]: KB5028380
                           [40]: KB5029709
                           [41]: KB5031539
                           [42]: KB5032392
                           [43]: KB5032907
                           [44]: KB5034224
                           [45]: KB5036447
                           [46]: KB5037018
                           [47]: KB5037240
                           [48]: KB5037995
                           [49]: KB5039336
                           [50]: KB5041579
                           [51]: KB5005699
Network Card(s):           5 NIC(s) Installed.
                           [01]: Qualcomm QCA61x4A 802.11ac Wireless Adapter
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     10.0.0.1
                                 IP address(es)
                                 [01]: 10.0.0.181
                           [02]: Cisco AnyConnect Secure Mobility Client Virtual Miniport Adapter for Windows x64
                                 Connection Name: Ethernet 2
                                 Status:          Hardware not present
                           [03]: Realtek USB GbE Family Controller
                                 Connection Name: Ethernet 3
                                 Status:          Media disconnected
                           [04]: Intel(R) Ethernet Connection (10) I219-LM
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [05]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection 3
                                 Status:          Media disconnected
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

**Comment by olivierfriard** [comment]
Is it possible to access to your BORIS project file and to a detailed procedure to repeat the issue?
You can send your project file by email (see the about page of the web site)
