### ISSUE TITLE
Trouble saving imported ethogram

### ISSUE THREAD

**Issue by Gjenni** [olivierfriard/BORIS#773]
**Indicate the version of BORIS**
BORIS Version 8.27.1

**Describe the bug**
I created a new BORIS project and imported the ethogram from another BORIS file (which I created about a month ago). When I wanted to save the project, the error message below appeared.
It took my quite a long time to create the ethogram last time, so being able to import would really make my life a lot easier.
Thanks!!

An error has occured!

to improve the software please report this problem at:
https://github.com/olivierfriard/BORIS/issues

Please no screenshot, the error message was copied to the clipboard.

Thank you for your collaboration!

BORIS version: 8.27.1
OS: Windows 10 10.0.19045
CPU: AMD64 AMD64 Family 25 Model 80 Stepping 0, AuthenticAMD
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.10
MPV library version: 2.1
MPV library file path: D:\boris-8.27.1-win64\Lib\site-packages\boris\misc\mpv-2.dll

Error succeded at 2024-07-24 20:10

Traceback (most recent call last):
  File "D:\boris-8.27.1-win64\Lib\site-packages\boris\project.py", line 1848, in pbOK_clicked
    r = dict(self.check_ethogram())
             ^^^^^^^^^^^^^^^^^^^^^
  File "D:\boris-8.27.1-win64\Lib\site-packages\boris\project.py", line 1706, in check_ethogram
    row["modifiers"] = json.loads(row["modifiers"]) if row["modifiers"] else {}
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\boris-8.27.1-win64\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\boris-8.27.1-win64\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\boris-8.27.1-win64\Lib\json\decoder.py", line 353, in raw_decode
    obj, end = self.scan_once(s, idx)
               ^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)

System info
===========

Host Name:                 LAPTOP-UA3J9RQF
OS Name:                   Microsoft Windows 10 Home
OS Version:                10.0.19045 N/A Build 19045
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Gjenni
Registered Organization:   N/A
Product ID:                00325-97238-90186-AAOEM
Original Install Date:     2021-11-23, 00:31:38
System Boot Time:          2024-07-12, 12:17:56
System Manufacturer:       LENOVO
System Model:              82MS
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: AMD64 Family 25 Model 80 Stepping 0 AuthenticAMD ~3301 Mhz
BIOS Version:              LENOVO GZCN27WW, 2022-05-01
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              sv;Swedish
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     14ÿ199 MB
Available Physical Memory: 4ÿ884 MB
Virtual Memory: Max Size:  21ÿ111 MB
Virtual Memory: Available: 7ÿ596 MB
Virtual Memory: In Use:    13ÿ515 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\LAPTOP-UA3J9RQF
Hotfix(s):                 40 Hotfix(s) Installed.
                           [01]: KB5039893
                           [02]: KB5028853
                           [03]: KB4562830
                           [04]: KB4570334
                           [05]: KB4580325
                           [06]: KB4586864
                           [07]: KB4593175
                           [08]: KB5003791
                           [09]: KB5005716
                           [10]: KB5011048
                           [11]: KB5012170
                           [12]: KB5015684
                           [13]: KB5033052
                           [14]: KB5040427
                           [15]: KB5006753
                           [16]: KB5007273
                           [17]: KB5011352
                           [18]: KB5011651
                           [19]: KB5014032
                           [20]: KB5014035
                           [21]: KB5014671
                           [22]: KB5015895
                           [23]: KB5016705
                           [24]: KB5018506
                           [25]: KB5020372
                           [26]: KB5022924
                           [27]: KB5025315
                           [28]: KB5026879
                           [29]: KB5028318
                           [30]: KB5028380
                           [31]: KB5029709
                           [32]: KB5031539
                           [33]: KB5032907
                           [34]: KB5034224
                           [35]: KB5036447
                           [36]: KB5037018
                           [37]: KB5037240
                           [38]: KB5037995
                           [39]: KB5039336
                           [40]: KB5034441
Network Card(s):           2 NIC(s) Installed.
                           [01]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
                           [02]: Realtek RTL8852AE WiFi 6 802.11ax PCIe Adapter
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     10.0.0.1
                                 IP address(es)
                                 [01]: 10.0.0.159
                                 [02]: fe80::78ee:fe40:c7c2:dfe8
                                 [03]: 2601:18e:c781:d840:bc13:bc7a:a897:7323
                                 [04]: 2601:18e:c781:d840:e74:eb2f:d412:253c
                                 [05]: 2601:18e:c781:d840::c68b
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

**Comment by olivierfriard** [comment]
Hi,
this issue should be fixed in v. 8.27.3
Please test and let me know.
See https://github.com/olivierfriard/BORIS/releases/tag/v8.27.3

**Comment by Gjenni** [comment]
Thank you so much!!
I skipped v. 8.27.3 since I saw you released another shortly after, and can confirm it's working perfectly now in v. 8.27.4
