### ISSUE TITLE
BORIS crashes when I load a video and does not generate any error message

### ISSUE THREAD

**Issue by marie1203** [olivierfriard/BORIS#774]
**Indicate the version of BORIS**
BORIS v. 8.27.1 - 2024-06-11

**Describe the bug**
When I try to load a video for a new observation, BORIS crashes without any error message even if I set the MPV player hardware video decoding option to No. I tried to play the video with mpv and it works normally. I've also re-encoded the video (originally as mp4) but the same error occurs. I'm a beginner on Linux so I don't really know what's wrong and how to solve it. 

**In case of crash** attach or copy the content of the boris.log file (before relaunching BORIS).

BORIS version: 8.27.1
OS: Linux 6.1.0-23-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.99-1 (2024-07-15)
CPU: x86_64 
Python 3.11.2 (64-bit)
Qt 5.15.8 - PyQt 5.15.9
MPV library version: 2.0
MPV library file path: libmpv.so.2

Error succeded at 2024-07-25 09:11

Traceback (most recent call last):
  File "/opt/boris/boris/core.py", line 5417, in closeEvent
    observation_operations.close_observation(self)
  File "/opt/boris/boris/observation_operations.py", line 1135, in close_observation
    dw.player.log_handler = None
    ^^^^^^^^^^^^^^^^^^^^^
  File "/opt/boris/boris/mpv2.py", line 2017, in __setattr__
    self._set_property(_py_to_mpv(name), value)
  File "/opt/boris/boris/mpv2.py", line 2003, in _set_property
    self.check_core_alive()
  File "/opt/boris/boris/mpv2.py", line 978, in check_core_alive
    raise ShutdownError('libmpv core has been shutdown')
boris.mpv2.ShutdownError: libmpv core has been shutdown

System info
===========

PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
Linux marvin-candy 6.1.0-23-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.99-1 (2024-07-15) x86_64 GNU/Linux
System info:
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
Linux marvin-candy 6.1.0-23-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.99-1 (2024-07-15) x86_64 GNU/Linux

**Comment by igutermes** [comment]
Same happening in Fedora 40 - Gnome
Happens both in Wayland and Xorg sessions
