### ISSUE TITLE
Boris Error when attempting to start a new observation

### ISSUE THREAD

**Issue by e-blop** [olivierfriard/BORIS#777]
When attempting to start a new observation in BORIS, I can get all the way down until hitting start: then, an error message pops up: 

An error has occured!

to improve the software please report this problem at:
https://github.com/olivierfriard/BORIS/issues

Please no screenshot, the error message was copied to the clipboard.

Thank you for your collaboration!

BORIS version: 8.25.4
OS: Windows 10 10.0.22631
CPU: AMD64 Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.10
MPV library version: 2.1
MPV library file path: C:\Users\erika\OneDrive\Documents\BORIS\Lib\site-packages\boris\misc\mpv-2.dll

Error succeded at 2024-07-30 09:54

Traceback (most recent call last):
  File "C:\Users\MYNAME\OneDrive\Documents\BORIS\Lib\site-packages\boris\observation.py", line 148, in <lambda>
    menu.triggered.connect(lambda x: self.add_media(mode=x.statusTip()))
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MYNAME\OneDrive\Documents\BORIS\Lib\site-packages\boris\observation.py", line 1251, in add_media
    (error, msg) = self.check_media(file_path, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\erika\OneDrive\Documents\BORIS\Lib\site-packages\boris\observation.py", line 1152, in check_media
    media_info = util.accurate_media_analysis(self.ffmpeg_bin, file_path)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MYNAME\OneDrive\Documents\BORIS\Lib\site-packages\boris\utilities.py", line 1343, in accurate_media_analysis
    ffprobe_results = ffprobe_media_analysis(ffmpeg_bin, file_name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MYNAME\OneDrive\Documents\BORIS\Lib\site-packages\boris\utilities.py", line 1231, in ffprobe_media_analysis
    video_param = json.loads(out.decode("utf-8"))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MY NAME\OneDrive\Documents\BORIS\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MY NAME\OneDrive\Documents\BORIS\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\MY NAME\OneDrive\Documents\BORIS\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

System info
===========

NO IDEA WHAT TO DO! Would appreciate help.

**Comment by olivierfriard** [comment]
Hi,
can you repeat this issue with the last version of BORIS?
