### ISSUE TITLE
BORIS no longer allows editing of observation

### ISSUE THREAD

**Issue by lysandrafp** [olivierfriard/BORIS#779]
BORIS version: 8.27.1
OS: Windows 11 10.0.22631
CPU: AMD64 Intel64 Family 6 Model 126 Stepping 5, GenuineIntel
Python 3.12.4 (64-bit)
Qt 5.15.2 - PyQt 5.15.10
MPV library version: 2.1
MPV library file path: C:\Users\Lysandra\BORIS\Lib\site-packages\boris\misc\mpv-2.dll

Error succeded at 2024-08-06 18:41

Traceback (most recent call last):
  File "C:\Users\Lysandra\BORIS\Lib\site-packages\boris\connections.py", line 90, in <lambda>
    self.actionEdit_observation_2.triggered.connect(lambda: observation_operations.edit_observation(self))
                                                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Lysandra\BORIS\Lib\site-packages\boris\observation_operations.py", line 265, in edit_observation
    new_observation(self, mode=cfg.EDIT, obsId=selected_observations[0])
  File "C:\Users\Lysandra\BORIS\Lib\site-packages\boris\observation_operations.py", line 753, in new_observation
    observationWindow.sb_media_scan_sampling.setValue(self.pj[cfg.OBSERVATIONS][obsId].get(cfg.MEDIA_SCAN_SAMPLING_DURATION, 0))
TypeError: setValue(self, val: int): argument 1 has unexpected type 'float'

System info
===========

Host Name:                 DESKTOP-FGCDRGB
OS Name:                   Microsoft Windows 11 Home
OS Version:                10.0.22631 N/A Build 22631
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Lysandra
Registered Organization:   
Product ID:                00325-82077-54234-AAOEM
Original Install Date:     14/02/2023, 14:59:19
System Boot Time:          06/08/2024, 18:02:47
System Manufacturer:       ASUSTeK COMPUTER INC.
System Model:              VivoBook_ASUSLaptop X421JAY_X413JA
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 126 Stepping 5 GenuineIntel ~991 Mhz
BIOS Version:              American Megatrends Inc. X421JAY.304, 04/06/2021
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-gb;English (United Kingdom)
Input Locale:              en-gb;English (United Kingdom)
Time Zone:                 (UTC+00:00) Dublin, Edinburgh, Lisbon, London
Total Physical Memory:     7,884 MB
Available Physical Memory: 1,434 MB
Virtual Memory: Max Size:  14,284 MB
Virtual Memory: Available: 5,541 MB
Virtual Memory: In Use:    8,743 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\DESKTOP-FGCDRGB
Hotfix(s):                 6 Hotfix(s) Installed.
                           [01]: KB5039895
                           [02]: KB5012170
                           [03]: KB5027397
                           [04]: KB5040442
                           [05]: KB5037959
                           [06]: KB5039338
Network Card(s):           4 NIC(s) Installed.
                           [01]: Fortinet Virtual Ethernet Adapter (NDIS 6.30)
                                 Connection Name: Ethernet 2
                                 Status:          Media disconnected
                           [02]: Intel(R) Wi-Fi 6 AX201 160MHz
                                 Connection Name: WiFi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     10.64.7.252
                                 IP address(es)
                                 [01]: 10.126.56.208
                                 [02]: fe80::2de9:eab6:a0c7:b869
                           [03]: Fortinet SSL VPN Virtual Ethernet Adapter
                                 Connection Name: Ethernet 3
                                 Status:          Hardware not present
                           [04]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

**Comment by olivierfriard** [comment]
Hi,
did you edit the BORIS project file with an external program?

Is it possible to access the project file that give this issue?
