### ISSUE TITLE
Error adding new behavior

### ISSUE THREAD

**Issue by automatize1** [olivierfriard/BORIS#784]
**Indicate the version of BORIS**
BORIS version: 8.27.4

**Describe the bug**
I get error popups on basically any action, namely when I first try to add a new behavior or when I click 'ok' on the 'new project' window. Note that this is a fresh instance of Boris.

**To Reproduce**
1. Create new project
2. Go to 'Ethogram'
3. Click on 'Behavior' -> 'Add new Behavior'

**Expected behavior**
Behavior should be added without errors

**Desktop (please complete the following information):**
 - OS: Windows 11
 - BORIS portable installation
 - Language: PT/BR

**In case of crash** attach or copy the content of the boris.log file (before relaunching BORIS).
(see http://www.boris.unito.it/pages/report_a_bug.html for its location)
An error has occured!

to improve the software please report this problem at:
https://github.com/olivierfriard/BORIS/issues

Please no screenshot, the error message was copied to the clipboard.

Thank you for your collaboration!

BORIS version: 8.27.4
OS: Windows 10 10.0.22631
CPU: AMD64 Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.11
MPV library version: 2.1
MPV library file path: C:\Users\gabriel.monteiro\OneDrive - Watanabe Tecnologia Aplicada\boris\boris-8.27.4-win64\Lib\site-packages\boris\misc\mpv-2.dll

Error succeded at 2024-08-23 09:33

Traceback (most recent call last):
  File "C:\Users\gabriel.monteiro\OneDrive - Watanabe Tecnologia Aplicada\boris\boris-8.27.4-win64\Lib\site-packages\boris\project.py", line 306, in <lambda>
    menu.triggered.connect(lambda x: self.behavior(action=x.statusTip()))
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gabriel.monteiro\OneDrive - Watanabe Tecnologia Aplicada\boris\boris-8.27.4-win64\Lib\site-packages\boris\project.py", line 461, in behavior
    self.add_behavior()
  File "C:\Users\gabriel.monteiro\OneDrive - Watanabe Tecnologia Aplicada\boris\boris-8.27.4-win64\Lib\site-packages\boris\project.py", line 1368, in add_behavior
    item.setBackground(self.not_editable_column_color())
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\gabriel.monteiro\OneDrive - Watanabe Tecnologia Aplicada\boris\boris-8.27.4-win64\Lib\site-packages\boris\project.py", line 433, in not_editable_column_color
    if self.config_param[cfg.DARK_MODE]:
       ~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^
KeyError: 'dark_mode'


System info
===========


Nome do host:                              WTA-3960
Nome do sistema operacional:               Microsoft Windows 11 Pro
VersÆo do sistema operacional:             10.0.22631 N/A compila‡Æo 22631
Fabricante do sistema operacional:         Microsoft Corporation
Configura‡Æo do SO:                        Esta‡Æo de trabalho membro
Tipo de compila‡Æo do sistema operacional: Multiprocessor Free
Propriet rio registrado:                   Adm
Organiza‡Æo registrada:                    N/A
Identifica‡Æo do produto:                  00355-60807-07672-AAOEM
Data da instala‡Æo original:               17/11/2022, 15:43:53
Tempo de Inicializa‡Æo do Sistema:         21/08/2024, 17:49:02
Fabricante do sistema:                     Dell Inc.
Modelo do sistema:                         Vostro 15 3510
Tipo de sistema:                           x64-based PC
Processador(es):                           1 processador(es) instalado(s).
                                           [01]: Intel64 Family 6 Model 140 Stepping 1 GenuineIntel ~2419 Mhz
VersÆo do BIOS:                            Dell Inc. 1.29.0, 25/04/2024
Pasta do Windows:                          C:\Windows
Pasta do sistema:                          C:\Windows\system32
Inicializar dispositivo:                   \Device\HarddiskVolume1
Localidade do sistema:                     pt-br;Portuguˆs (Brasil)
Localidade de entrada:                     pt-br;Portuguˆs (Brasil)
Fuso hor rio:                              (UTC-03:00) Bras¡lia
Mem¢ria f¡sica total:                      32.503 MB
Mem¢ria f¡sica dispon¡vel:                 12.742 MB
Mem¢ria Virtual: Tamanho M ximo:           45.303 MB
Mem¢ria Virtual: Dispon¡vel:               18.820 MB
Mem¢ria Virtual: Em Uso:                   26.483 MB
Local(is) de arquivo de pagina‡Æo:         C:\pagefile.sys
Dom¡nio:                                   wta.local
Servidor de Logon:                         \\DC1
Hotfix(es):                                5 hotfix(es) instalado(s).
                                           [01]: KB5042099
                                           [02]: KB5012170
                                           [03]: KB5027397
                                           [04]: KB5041585
                                           [05]: KB5041584
Placa(s) de Rede:                          5 NIC(s) instalado(s).
                                           [01]: Intel(R) Wireless-AC 9462
                                                 Nome da conexÆo: Wi-Fi
                                                 DHCP ativado:    Sim
                                                 Servidor DHCP:   192.168.0.1
                                                 Endere‡o(es) IP
                                                 [01]: 192.168.0.107
                                           [02]: Realtek PCIe GbE Family Controller
                                                 Nome da conexÆo: Ethernet
                                                 DHCP ativado:    Sim
                                                 Servidor DHCP:   192.168.2.1
                                                 Endere‡o(es) IP
                                                 [01]: 192.168.2.114
                                           [03]: Bluetooth Device (Personal Area Network)
                                                 Nome da conexÆo: ConexÆo de Rede Bluetooth
                                                 Status:          M¡dia desconectada
                                           [04]: Wintun Userspace Tunnel
                                                 Nome da conexÆo: OpenVPN Wintun
                                                 Status:          M¡dia desconectada
                                           [05]: TAP-Windows Adapter V9
                                                 Nome da conexÆo: OpenVPN TAP-Windows6
                                                 Status:          M¡dia desconectada
Requisitos do Hyper-V:                     Hipervisor detectado. Recursos necess rios para o Hyper-V nÆo serÆo exibidos.

**Comment by olivierfriard** [comment]
hi,
this issue should be fixed in v. 8.27.7.
Please try and and me know.
Thank you for your collaboration

**Comment by automatize1** [comment]
It is working as expected now! Thank you for the quick fix.

I'll mark this issue as 'Closed'
