### ISSUE TITLE
Can not download tabular data

### ISSUE THREAD

**Issue by carsondaniel** [olivierfriard/BORIS#799]
**ERROR MESSAGE**
An error has occured!

to improve the software please report this problem at:
https://github.com/olivierfriard/BORIS/issues

Please no screenshot, the error message was copied to the clipboard.

Thank you for your collaboration!

BORIS version: 8.24.1
OS: Windows 10 10.0.22631
CPU: AMD64 Intel64 Family 6 Model 85 Stepping 7, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.10
MPV library version: 2.1
MPV library file path: C:\Users\acd27038\BORIS\Lib\site-packages\boris\misc\mpv-2.dll

Error succeded at 2024-10-10 13:28

Traceback (most recent call last):
  File "C:\Users\acd27038\BORIS\Lib\site-packages\boris\connections.py", line 138, in <lambda>
    self.actionExportEvents_2.triggered.connect(lambda: export_events.export_tabular_events(self, mode="tabular"))
                                                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\acd27038\BORIS\Lib\site-packages\boris\export_events.py", line 261, in export_tabular_events
    r, msg = export_observation.export_tabular_events(
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\acd27038\BORIS\Lib\site-packages\boris\export_observation.py", line 429, in export_tabular_events
    fps_lst.append(f"{observation[cfg.MEDIA_INFO][cfg.FPS].get(media_file, cfg.NA):.3f}")
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: Unknown format code 'f' for object of type 'str'

System info
===========

Host Name:                 FOR-G0HQNZ3-D
OS Name:                   Microsoft Windows 11 Enterprise
OS Version:                10.0.22631 N/A Build 22631
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          N/A
Registered Organization:   N/A
Product ID:                00329-00000-00003-AA871
Original Install Date:     11/7/2023, 1:12:07 PM
System Boot Time:          10/7/2024, 1:20:32 PM
System Manufacturer:       Dell Inc.
System Model:              Precision 7820 Tower
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 85 Stepping 7 GenuineIntel ~3592 Mhz
BIOS Version:              Dell Inc. 2.34.0, 5/29/2023
Windows Directory:         C:\Windows
System Directory:          C:\Windows\system32
Boot Device:               \Device\HarddiskVolume5
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     195,205 MB
Available Physical Memory: 172,991 MB
Virtual Memory: Max Size:  207,493 MB
Virtual Memory: Available: 183,903 MB
Virtual Memory: In Use:    23,590 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\FOR-G0HQNZ3-D
Hotfix(s):                 7 Hotfix(s) Installed.
                           [01]: KB5042099
                           [02]: KB5044033
                           [03]: KB5027397
                           [04]: KB5031274
                           [05]: KB5032381
                           [06]: KB5043076
                           [07]: KB5043937
Network Card(s):           2 NIC(s) Installed.
                           [01]: Intel(R) Ethernet Connection (3) I219-LM
                                 Connection Name: Ethernet
                                 DHCP Enabled:    Yes
                                 DHCP Server:     128.192.247.229
                                 IP address(es)
                                 [01]: 172.22.18.191
                                 [02]: fe80::faea:76ef:9de3:ccf2
                           [02]: Cisco AnyConnect Secure Mobility Client Virtual Miniport Adapter for Windows x64
                                 Connection Name: Ethernet 3
                                 Status:          Hardware not present
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Expected behavior**

I EXPECTED THE TABULAR DATA TO BE DONWLOADED IN DESIRED FOLDER. 

**Desktop (please complete the following information):**
 - OS: Windows 10 10.0.22631

**Comment by olivierfriard** [comment]
Hi,
thank you for reporting this.
Are you able to reproduce this issue using the last version (8.27.7)?
