### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by kalves4** [olivierfriard/BORIS#804]
Important points to add in your bug report
===========================================

1) Indicate the version of BORIS (Verify you are using the last version http://www.boris.unito.it/download)
8.27.10
2) Verify the integrity of your BORIS project using: Project > Check project integrity

3) Describe the bug

SystemError: ('Error running mpv command', -12, (<MpvHandle object at 0x0000022F1478EDD0>, <boris.mpv2.LP_MpvNode object at 0x0000022F19D397D0>, <boris.mpv2.LP_MpvNode object at 0x0000022F19D39550>))

Steps to reproduce the issue:

**Expected behavior**

Screenshots:  If applicable, add screenshots to help explain your problem.

Information about your system: 
 - OS: [windows 10, Ubuntu 22.04 ... ]
 - Type of BORIS installation (setup or portable ...)

In case of crash attach or copy the content of the boris.log file (before relaunching BORIS).
(see http://www.boris.unito.it/report_a_bug for its location)

An error has occured!

to improve the software please report this problem at:
https://github.com/olivierfriard/BORIS/issues

Please no screenshot, the error message was copied to the clipboard.

Thank you for your collaboration!

BORIS version: 8.27.10
OS: Windows 11 10.0.22631
CPU: AMD64 Intel64 Family 6 Model 165 Stepping 3, GenuineIntel
Python 3.12.4 (64-bit)
Qt 5.15.2 - PyQt 5.15.11
MPV library version: 2.1
MPV API version: (2, 1)
MPV library file path: C:\Users\kalves\BORIS\Lib\site-packages\boris\misc\mpv-2.dll

Error succeded at 2024-11-06 11:02

Traceback (most recent call last):
  File "C:\Users\kalves\BORIS\Lib\site-packages\boris\connections.py", line 88, in <lambda>
    self.actionOpen_observation.triggered.connect(lambda: observation_operations.open_observation(self, mode=cfg.OBS_START))
                                                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kalves\BORIS\Lib\site-packages\boris\observation_operations.py", line 175, in open_observation
    return load_observation(self, selected_observations[0], mode)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kalves\BORIS\Lib\site-packages\boris\observation_operations.py", line 222, in load_observation
    if not initialize_new_media_observation(self):
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\kalves\BORIS\Lib\site-packages\boris\observation_operations.py", line 1853, in initialize_new_media_observation
    self.seek_mediaplayer(int(self.pj[cfg.OBSERVATIONS][self.observationId][cfg.OBSERVATION_TIME_INTERVAL][0]), player=i)
  File "C:\Users\kalves\BORIS\Lib\site-packages\boris\core.py", line 1482, in seek_mediaplayer
    self.dw_player[player].player.seek(
  File "C:\Users\kalves\BORIS\Lib\site-packages\boris\mpv2.py", line 1266, in seek
    self.command('seek', amount, reference, precision)
  File "C:\Users\kalves\BORIS\Lib\site-packages\boris\mpv2.py", line 1259, in command
    _mpv_command_node(self.handle, ppointer, out)
  File "C:\Users\kalves\BORIS\Lib\site-packages\boris\mpv2.py", line 162, in raise_for_ec
    raise ex
SystemError: ('Error running mpv command', -12, (<MpvHandle object at 0x0000022F1478EDD0>, <boris.mpv2.LP_MpvNode object at 0x0000022F19D397D0>, <boris.mpv2.LP_MpvNode object at 0x0000022F19D39550>))

System info
===========

Host Name:                 DESKTOP-LP9O7AC
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22631 N/A Build 22631
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          Admin
Registered Organization:   N/A
Product ID:                00330-53869-62165-AAOEM
Original Install Date:     1/12/2023, 8:48:24 AM
System Boot Time:          10/15/2024, 2:31:31 AM
System Manufacturer:       LENOVO
System Model:              30DHS00N00
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 165 Stepping 3 GenuineIntel ~2904 Mhz
BIOS Version:              LENOVO S08KT58A, 12/25/2023
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume2
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     7,900 MB
Available Physical Memory: 1,045 MB
Virtual Memory: Max Size:  11,909 MB
Virtual Memory: Available: 1,297 MB
Virtual Memory: In Use:    10,612 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    cf.local
Logon Server:              N/A
Hotfix(s):                 5 Hotfix(s) Installed.
                           [01]: KB5042099
                           [02]: KB5012170
                           [03]: KB5027397
                           [04]: KB5043076
                           [05]: KB5043937
Network Card(s):           3 NIC(s) Installed.
                           [01]: Intel(R) Wi-Fi 6 AX201 160MHz
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.110.5
                                 IP address(es)
                                 [01]: 192.168.110.176
                                 [02]: fe80::5af4:ac45:3ca1:9ee
                           [02]: Intel(R) Ethernet Connection (11) I219-LM
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [03]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

**Comment by Sofiagigliotti** [comment]
Hello, 
Could you solve your problem? I'm having the same issue when I try to open observations

**Comment by olivierfriard** [comment]
Hi,

is it possible to access the BORIS project file?

See https://www.boris.unito.it/about for my direct email

Please indicate the GitHub issue id

Thank you for your collaboration

**Comment by olivierfriard** [comment]
Please verify the integrity of your BORIS project using: Project > Check project integrity
