### ISSUE TITLE
Cannot Edit Point Event Code for Observation from Pictures

### ISSUE THREAD

**Issue by jujumartini** [olivierfriard/BORIS#809]
1) BORIS version: 8.27.10

2) The current project has no issues

3) When attempting to edit a point event in a Observation from Pictures, BORIS crashes

Steps to reproduce the issue:

1. 'Observations' -> 'New Observation'
2. Click on 'Observation from Pictures'. No other options matter
3. Start Observation
4. Apply a Point Event code
5. Right click the applied code in the Events Table -> 'Edit Selected Event(s)'
6. Change the code to another Point Event Code. Changing other options such as 'Image Index' does not matter
7. Click 'OK'
8. Crash occurs

**Expected behavior**

The Point Event code to be changed to the new Point Event code.
As of now, requires 1) double-clicking event in Events Table 2) deleting the event in the Events Table, 3) Apply correct Point Event code

An error has occured!

to improve the software please report this problem at:
https://github.com/olivierfriard/BORIS/issues

Please no screenshot, the error message was copied to the clipboard.

Thank you for your collaboration!

BORIS version: 8.27.10
OS: Windows 10 10.0.19045
CPU: AMD64 Intel64 Family 6 Model 158 Stepping 9, GenuineIntel
Python 3.12.4 (64-bit)
Qt 5.15.2 - PyQt 5.15.11
MPV library version: 2.3
MPV API version: (2, 3)
MPV library file path: S:\_V_PAHRL\FLAC\BORIS\Lib\site-packages\boris\misc\libmpv-2.dll

Error succeded at 2024-12-05 09:24

Traceback (most recent call last):
  File "S:\_V_PAHRL\FLAC\BORIS\Lib\site-packages\boris\connections.py", line 122, in <lambda>
    self.actionEdit_selected_events.triggered.connect(lambda: event_operations.edit_selected_events(self))
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "S:\_V_PAHRL\FLAC\BORIS\Lib\site-packages\boris\event_operations.py", line 461, in edit_selected_events
    edit_event(self)
  File "S:\_V_PAHRL\FLAC\BORIS\Lib\site-packages\boris\event_operations.py", line 788, in edit_event
    r = write_event.write_event(self, event, event[cfg.TIME].quantize(dec("0.001"), rounding=ROUND_DOWN))
                                             ^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'quantize'

System info
===========

Host Name:                 CHS-END416-X6
OS Name:                   Microsoft Windows 10 Education
OS Version:                10.0.19045 N/A Build 19045
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Member Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          UWM Computer User
Registered Organization:   University of Wisconsin - Milwaukee
Product ID:                00328-10000-00001-AA159
Original Install Date:     4/21/2022, 12:22:11 AM
System Boot Time:          11/20/2024, 11:32:58 PM
System Manufacturer:       Dell Inc.
System Model:              OptiPlex 7450 AIO
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 158 Stepping 9 GenuineIntel ~3408 Mhz
BIOS Version:              Dell Inc. 1.9.1, 3/13/2018
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume2
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-06:00) Central Time (US & Canada)
Total Physical Memory:     8,044 MB
Available Physical Memory: 1,506 MB
Virtual Memory: Max Size:  17,285 MB
Virtual Memory: Available: 3,060 MB
Virtual Memory: In Use:    14,225 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    ad.uwm.edu
Logon Server:              \\UWM-DC-P5
Hotfix(s):                 36 Hotfix(s) Installed.
                           [01]: KB5045936
                           [02]: KB4562830
                           [03]: KB5003791
                           [04]: KB5007401
                           [05]: KB5012170
                           [06]: KB5015684
                           [07]: KB5046613
                           [08]: KB5011651
                           [09]: KB5014032
                           [10]: KB5014035
                           [11]: KB5014671
                           [12]: KB5015895
                           [13]: KB5016705
                           [14]: KB5018506
                           [15]: KB5020372
                           [16]: KB5022924
                           [17]: KB5023794
                           [18]: KB5025315
                           [19]: KB5026879
                           [20]: KB5028318
                           [21]: KB5028380
                           [22]: KB5029709
                           [23]: KB5031539
                           [24]: KB5032392
                           [25]: KB5032907
                           [26]: KB5034224
                           [27]: KB5036447
                           [28]: KB5037018
                           [29]: KB5037240
                           [30]: KB5037995
                           [31]: KB5039336
                           [32]: KB5041579
                           [33]: KB5043935
                           [34]: KB5043130
                           [35]: KB5046823
                           [36]: KB5005699
Network Card(s):           1 NIC(s) Installed.
                           [01]: Intel(R) Ethernet Connection (5) I219-LM
                                 Connection Name: Ethernet
                                 DHCP Enabled:    Yes
                                 DHCP Server:     129.89.10.202
                                 IP address(es)
                                 [01]: 10.60.8.202
                                 [02]: fe80::716e:5a77:27e9:a7d7
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

**Comment by olivierfriard** [comment]
Hi,
thank you for reporting this issue.
It should be fixed in the pre-release of v. 9.1.1 see https://github.com/olivierfriard/BORIS/releases/tag/v9.1.1

Please test it and let me known
