### ISSUE TITLE
Cannot edit project ethogram information

### ISSUE THREAD

**Issue by AlbertFok** [olivierfriard/BORIS#810]
BORIS version: 8.25.4
OS: Windows 10 10.0.22631
CPU: AMD64 Intel64 Family 6 Model 167 Stepping 1, GenuineIntel
Python 3.11.2 (64-bit)
Qt 5.15.2 - PyQt 5.15.10
MPV library version: 2.1
MPV library file path: C:\Users\ahkfo\BORIS\Lib\site-packages\boris\misc\mpv-2.dll

Error succeded at 2024-12-05 10:57

Traceback (most recent call last):
  File "C:\Users\ahkfo\BORIS\Lib\site-packages\boris\project.py", line 1833, in pbOK_clicked
    r = dict(self.check_ethogram())
             ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\ahkfo\BORIS\Lib\site-packages\boris\project.py", line 1691, in check_ethogram
    row["modifiers"] = eval(row["modifiers"])
                       ^^^^^^^^^^^^^^^^^^^^^^
  File "<string>", line 1, in <module>
NameError: name 'false' is not defined

System info
===========

Host Name:                 DESKTOP-1VGSC39
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22631 N/A Build 22631
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          sabrinachierzi@gmail.com
Registered Organization:   N/A
Product ID:                00330-54381-21775-AAOEM
Original Install Date:     2024-01-24, 12:14:42 AM
System Boot Time:          2024-11-18, 2:35:56 PM
System Manufacturer:       LENOVO
System Model:              30EQ01VXUS
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 167 Stepping 1 GenuineIntel ~2496 Mhz
BIOS Version:              LENOVO M3KKT2DA, 2021-11-01
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     32,464 MB
Available Physical Memory: 19,306 MB
Virtual Memory: Max Size:  34,512 MB
Virtual Memory: Available: 18,332 MB
Virtual Memory: In Use:    16,180 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\DESKTOP-1VGSC39
Hotfix(s):                 4 Hotfix(s) Installed.
                           [01]: KB5045935
                           [02]: KB5027397
                           [03]: KB5046633
                           [04]: KB5044620
Network Card(s):           3 NIC(s) Installed.
                           [01]: Intel(R) Wi-Fi 6 AX201 160MHz
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.0.1
                                 IP address(es)
                                 [01]: 192.168.0.111
                                 [02]: fe80::e22f:10b7:2fcd:c6ad
                           [02]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
                           [03]: Realtek PCIe GbE Family Controller
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

**Comment by olivierfriard** [comment]
Hi,
can you repeat this issue with the last version (8.27.10)?
See https://www.boris.unito.it/download/
