### ISSUE TITLE
Annotation Sync Error

### ISSUE THREAD

**Issue by ameliamacap** [olivierfriard/BORIS#811]
When attempting to change the video path for this observation, all annotation times have disappeared, resulting in a loss of synchronization with the video.

BORIS version: 8.27.1
OS: Windows 11 10.0.22631
CPU: AMD64 Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
Python 3.12.4 (64-bit)
Qt 5.15.2 - PyQt 5.15.10
MPV library version: 2.1
MPV library file path: C:\Users\amelia.macapia\BORIS\Lib\site-packages\boris\misc\mpv-2.dll

Error succeded at 2024-12-09 10:50

Traceback (most recent call last):
  File "C:\Users\amelia.macapia\BORIS\Lib\site-packages\boris\core.py", line 5111, in tv_events_doubleClicked
    time_ = util.time2seconds(time_str) if ":" in time_str else dec(time_str)
                                           ^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable

System info
===========

Host Name:                 DESKTOP-AIT04EO
OS Name:                   Microsoft Windows 11 Enterprise
OS Version:                10.0.22631 N/A Build 22631
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          N/A
Registered Organization:   N/A
Product ID:                00330-80000-00000-AA021
Original Install Date:     10/9/2022, 3:14:03 PM
System Boot Time:          11/25/2024, 7:09:04 PM
System Manufacturer:       Dell Inc.
System Model:              Latitude 5430 Rugged
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 140 Stepping 1 GenuineIntel ~2995 Mhz
BIOS Version:              Dell Inc. 1.30.0, 8/16/2024
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     32,497 MB
Available Physical Memory: 14,994 MB
Virtual Memory: Max Size:  40,536 MB
Virtual Memory: Available: 4,210 MB
Virtual Memory: In Use:    36,326 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\DESKTOP-AIT04EO
Hotfix(s):                 5 Hotfix(s) Installed.
                           [01]: KB5045935
                           [02]: KB5012170
                           [03]: KB5027397
                           [04]: KB5046633
                           [05]: KB5044620
Network Card(s):           3 NIC(s) Installed.
                           [01]: Intel(R) Wi-Fi 6E AX210 160MHz
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     128.128.243.43
                                 IP address(es)
                                 [01]: 128.128.225.176
                                 [02]: fe80::6ae7:8490:c59e:9cb8
                           [02]: Intel(R) Ethernet Connection (13) I219-LM
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [03]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.

**Comment by olivierfriard** [comment]
Hi,

please give me the context and more details in order to repeat the issue.

**Comment by olivierfriard** [comment]
Hi Amelia,

can you repeat the issue with the last version of BORIS?
Best regards

**Comment by ameliamacap** [comment]
Hello, yes even with the updated version, for both this project and another I have the same issue where timestamps disappear and no media position is appearing. 

![Screenshot 2024-12-11 133530](https://github.com/user-attachments/assets/21475052-7955-4af1-b848-859ce2a123a1)


BORIS version: 8.27.10
OS: Windows 11 10.0.22631
CPU: AMD64 Intel64 Family 6 Model 140 Stepping 1, GenuineIntel
Python 3.12.4 (64-bit)
Qt 5.15.2 - PyQt 5.15.11
MPV library version: 2.1
MPV API version: (2, 1)
MPV library file path: C:\Users\amelia.macapia\BORIS\Lib\site-packages\boris\misc\mpv-2.dll

Error succeded at 2024-12-11 13:18

Traceback (most recent call last):
  File "C:\Users\amelia.macapia\BORIS\Lib\site-packages\boris\core.py", line 5111, in tv_events_doubleClicked
    time_ = util.time2seconds(time_str) if ":" in time_str else dec(time_str)
                                           ^^^^^^^^^^^^^^^
TypeError: argument of type 'NoneType' is not iterable


System info
===========


Host Name:                 DESKTOP-AIT04EO
OS Name:                   Microsoft Windows 11 Enterprise
OS Version:                10.0.22631 N/A Build 22631
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          N/A
Registered Organization:   N/A
Product ID:                00330-80000-00000-AA021
Original Install Date:     10/9/2022, 3:14:03 PM
System Boot Time:          11/25/2024, 7:09:00 PM
System Manufacturer:       Dell Inc.
System Model:              Latitude 5430 Rugged
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 140 Stepping 1 GenuineIntel ~2995 Mhz
BIOS Version:              Dell Inc. 1.30.0, 8/16/2024
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     32,497 MB
Available Physical Memory: 10,689 MB
Virtual Memory: Max Size:  53,126 MB
Virtual Memory: Available: 7,686 MB
Virtual Memory: In Use:    45,440 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\DESKTOP-AIT04EO
Hotfix(s):                 6 Hotfix(s) Installed.
                           [01]: KB5045935
                           [02]: KB5012170
                           [03]: KB5027397
                           [04]: KB5048685
                           [05]: KB5044620
                           [06]: KB5046729
Network Card(s):           3 NIC(s) Installed.
                           [01]: Intel(R) Wi-Fi 6E AX210 160MHz
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     128.128.243.43
                                 IP address(es)
                                 [01]: 128.128.225.176
                                 [02]: fe80::6ae7:8490:c59e:9cb8
                           [02]: Intel(R) Ethernet Connection (13) I219-LM
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
                           [03]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
Hyper-V Requirements:      A hypervisor has been detected. Features required for Hyper-V will not be displayed.
