### ISSUE TITLE
Cannot create transition matrix (frequencies of transitions after behaviors)

### ISSUE THREAD

**Issue by AlbertFok** [olivierfriard/BORIS#812]
BORIS version: 8.27.10
OS: Windows 11 10.0.22631
CPU: AMD64 Intel64 Family 6 Model 167 Stepping 1, GenuineIntel
Python 3.12.4 (64-bit)
Qt 5.15.2 - PyQt 5.15.11
MPV library version: 2.3
MPV API version: (2, 3)
MPV library file path: C:\Users\ahkfo\Downloads\boris-8.27.10-win64\Lib\site-packages\boris\misc\libmpv-2.dll

Error succeded at 2024-12-11 15:54

Traceback (most recent call last):
  File "C:\Users\ahkfo\Downloads\boris-8.27.10-win64\Lib\site-packages\boris\connections.py", line 162, in <lambda>
    self.actionFrequencies_of_transitions_after_behaviors.triggered.connect(lambda: self.transitions_matrix("frequencies_after_behaviors"))
                                                                                    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MainWindow' object has no attribute 'transitions_matrix'

System info
===========

Host Name:                 DESKTOP-1VGSC39
OS Name:                   Microsoft Windows 11 Pro
OS Version:                10.0.22631 N/A Build 22631
OS Manufacturer:           Microsoft Corporation
OS Configuration:          Standalone Workstation
OS Build Type:             Multiprocessor Free
Registered Owner:          sabrinachierzi@gmail.com
Registered Organization:   N/A
Product ID:                00330-54381-21775-AAOEM
Original Install Date:     2024-01-24, 12:14:42 AM
System Boot Time:          2024-11-18, 2:35:55 PM
System Manufacturer:       LENOVO
System Model:              30EQ01VXUS
System Type:               x64-based PC
Processor(s):              1 Processor(s) Installed.
                           [01]: Intel64 Family 6 Model 167 Stepping 1 GenuineIntel ~2496 Mhz
BIOS Version:              LENOVO M3KKT2DA, 2021-11-01
Windows Directory:         C:\WINDOWS
System Directory:          C:\WINDOWS\system32
Boot Device:               \Device\HarddiskVolume1
System Locale:             en-us;English (United States)
Input Locale:              en-us;English (United States)
Time Zone:                 (UTC-05:00) Eastern Time (US & Canada)
Total Physical Memory:     32,464 MB
Available Physical Memory: 19,071 MB
Virtual Memory: Max Size:  34,512 MB
Virtual Memory: Available: 18,436 MB
Virtual Memory: In Use:    16,076 MB
Page File Location(s):     C:\pagefile.sys
Domain:                    WORKGROUP
Logon Server:              \\DESKTOP-1VGSC39
Hotfix(s):                 5 Hotfix(s) Installed.
                           [01]: KB5045935
                           [02]: KB5027397
                           [03]: KB5048685
                           [04]: KB5044620
                           [05]: KB5046729
Network Card(s):           3 NIC(s) Installed.
                           [01]: Intel(R) Wi-Fi 6 AX201 160MHz
                                 Connection Name: Wi-Fi
                                 DHCP Enabled:    Yes
                                 DHCP Server:     192.168.0.1
                                 IP address(es)
                                 [01]: 192.168.0.111
                                 [02]: fe80::e22f:10b7:2fcd:c6ad
                           [02]: Bluetooth Device (Personal Area Network)
                                 Connection Name: Bluetooth Network Connection
                                 Status:          Media disconnected
                           [03]: Realtek PCIe GbE Family Controller
                                 Connection Name: Ethernet
                                 Status:          Media disconnected
Hyper-V Requirements:      VM Monitor Mode Extensions: Yes
                           Virtualization Enabled In Firmware: Yes
                           Second Level Address Translation: Yes
                           Data Execution Prevention Available: Yes

**Comment by florianduclot** [comment]
I encountered the same issue while working on #832. Debug log:
```
BORIS version: 9.0.6
OS: Windows 10 10.0.19045
CPU: AMD64 Intel64 Family 6 Model 60 Stepping 3, GenuineIntel
Python 3.12.6 (64-bit)
Qt 6.8.0 - PySide 6.8.0.2
MPV library version: 2.3
MPV API version: (2, 3)
MPV library file path: C:\Tools\Repos\BORIS\boris\misc\libmpv-2.dll

Error succeded at 2025-02-28 15:50

Traceback (most recent call last):
  File "C:\Tools\Repos\BORIS\boris\connections.py", line 163, in <lambda>
    self.actionFrequencies_of_transitions_after_behaviors.triggered.connect(lambda: self.transitions_matrix("frequencies_after_behaviors"))
                                                                                    ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'MainWindow' object has no attribute 'transitions_matrix'
```

I could fix it by simply adjusting the following:
```diff
-    self.actionFrequencies_of_transitions_after_behaviors.triggered.connect(lambda: self.transitions_matrix("frequencies_after_behaviors"))
+    self.actionFrequencies_of_transitions_after_behaviors.triggered.connect(lambda: transitions.transitions_matrix(self, "frequencies_after_behaviors"))
```

**Comment by olivierfriard** [comment]
Hi,
thank you for reporting this issue.
It should be fixed in the pre-release of v. 9.1.1 see https://github.com/olivierfriard/BORIS/releases/tag/v9.1.1

Please test it and let me known
