### ISSUE TITLE
Error happening when I try and open the modifier on a behavior imported from an XLSX file

### ISSUE THREAD

**Issue by crow242** [olivierfriard/BORIS#813]
This is the error message that came up, 

BORIS version: 8.27.10
OS: Windows 11 10.0.26100
CPU: AMD64 Intel64 Family 6 Model 154 Stepping 4, GenuineIntel
Python 3.12.4 (64-bit)
Qt 5.15.2 - PyQt 5.15.11
MPV library version: 2.3
MPV API version: (2, 3)
MPV library file path: C:\Users\joshc\BORIS\Lib\site-packages\boris\misc\libmpv-2.dll

Error succeded at 2024-12-19 19:20

Traceback (most recent call last):
  File "C:\Users\joshc\BORIS\Lib\site-packages\boris\project.py", line 826, in twBehaviors_cellDoubleClicked
    addModifierWindow = add_modifier.addModifierDialog(
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshc\BORIS\Lib\site-packages\boris\add_modifier.py", line 75, in __init__
    dummy_dict: dict = json.loads(modifiers_str) if modifiers_str else {}
                       ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshc\BORIS\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\joshc\BORIS\Lib\json\decoder.py", line 340, in decode
    raise JSONDecodeError("Extra data", s, end)
json.decoder.JSONDecodeError: Extra data: line 1 column 5 (char 4)

System info
===========

Host Name:                     THEMPUTER
OS Name:                       Microsoft Windows 11 Home
OS Version:                    10.0.26100 N/A Build 26100
OS Manufacturer:               Microsoft Corporation
OS Configuration:              Standalone Workstation
OS Build Type:                 Multiprocessor Free
Registered Owner:              josh.crow24@gmail.com
Registered Organization:       N/A
Product ID:                    00342-21297-87735-AAOEM
Original Install Date:         12/6/2024, 2:37:57 PM
System Boot Time:              12/19/2024, 12:11:45 AM
System Manufacturer:           Dell Inc.
System Model:                  Inspiron 15 3520
System Type:                   x64-based PC
Processor(s):                  1 Processor(s) Installed.
                               [01]: Intel64 Family 6 Model 154 Stepping 4 GenuineIntel ~1200 Mhz
BIOS Version:                  Dell Inc. 1.28.0, 9/6/2024
Windows Directory:             C:\Windows
System Directory:              C:\Windows\system32
Boot Device:                   \Device\HarddiskVolume1
System Locale:                 en-us;English (United States)
Input Locale:                  en-us;English (United States)
Time Zone:                     (UTC-05:00) Indiana (East)
Total Physical Memory:         7,877 MB
Available Physical Memory:     1,159 MB
Virtual Memory: Max Size:      14,277 MB
Virtual Memory: Available:     3,624 MB
Virtual Memory: In Use:        10,653 MB
Page File Location(s):         C:\pagefile.sys
Domain:                        WORKGROUP
Logon Server:                  \\THEMPUTER
Hotfix(s):                     5 Hotfix(s) Installed.
                               [01]: KB5045934
                               [02]: KB5048779
                               [03]: KB5048667
                               [04]: KB5047621
                               [05]: KB5049685
Network Card(s):               2 NIC(s) Installed.
                               [01]: Realtek 8821CE Wireless LAN 802.11ac PCI-E NIC
                                     Connection Name: Wi-Fi
                                     DHCP Enabled:    Yes
                                     DHCP Server:     192.168.88.1
                                     IP address(es)
                                     [01]: 192.168.88.185
                                     [02]: fe80::67eb:6784:12a1:65ef
                               [02]: Bluetooth Device (Personal Area Network)
                                     Connection Name: Bluetooth Network Connection
                                     Status:          Media disconnected
Virtualization-based security: Status: Running
                               Required Security Properties:
                                     Base Virtualization Support
                               Available Security Properties:
                                     Base Virtualization Support
                                     Secure Boot
                                     DMA Protection
                                     UEFI Code Readonly
                                     SMM Security Mitigations 1.0
                                     Mode Based Execution Control
                                     APIC Virtualization
                               Services Configured:
                                     Hypervisor enforced Code Integrity
                               Services Running:
                                     Hypervisor enforced Code Integrity
                               App Control for Business policy: Enforced
                               App Control for Business user mode policy: Audit
                               Security Features Enabled:
Hyper-V Requirements:          A hypervisor has been detected. Features required for Hyper-V will not be displayed.

I'm assuming the problem is I don't know how to format the JSON in the Excel spreadsheet. The goal is to have multiple names for a behavior, like for the behavior agonistic pucker I'd like to have modifiers such as "Elicited" and "Food related" and I would pick one when coding the behavior in boris. I've been typing them like this.
 {"0": {"name": "Elicited", "type": "checkbox"},"1": {"name": "Food Related", "type": "checkbox"}}

If anyone could help correct if I'm typing it out wrong, I'd appreciate the help! This is my first time using Boris and I'm new to stuff like this.

**Comment by olivierfriard** [comment]
Hi,
can you send me the XLSX file that create the issue?
By email if you prefer

**Comment by crow242** [comment]
Hello,

I’m sorry, I don’t have the file anymore. The problem was that i was trying to use it on my mac, and I’ve never tried anything related to coding anymore so I was very out of water with it. 

I solved it by using another computer. 

I appreciate you checking in though to try to help! 
Hope your day is going well. 

Best regards, 
Joshua
